In [1]:
import pandas as pd
import torch
import torch.nn as nn
import numpy as np
from preprocessor import preprocessor

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
import pickle
def load_pkl(pkl_file):
    with open(pkl_file, 'rb') as inp:
        pickled_obj = pickle.load(inp)
    return pickled_obj

In [4]:
pre = load_pkl("pre_user_keywords.pkl")

In [5]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",ज्ञानेन्द्र भ्रम राजा अन्याय भट्टराई कटाक्ष तप...
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व...",कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरे...
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...","हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, ..."
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्...

In [23]:
pre.df.keywords.iloc[0], type(pre.df.keywords.iloc[0])

([13073,
  27456,
  12617,
  6083,
  31465,
  19698,
  12934,
  22223,
  25310,
  3877,
  220,
  23679,
  36243,
  34199,
  15598,
  124,
  28786,
  17785,
  19745,
  38483],
 list)

In [11]:
pre.keyword_enocder.get(pre.df.keywords.iloc[0][0])

'पैसा'

In [24]:
def get_keywords(keyword_list):
#     keywords = [pre.keyword_enocder.get(word) for word in keyword_list]
    keywords=" ".join(pre.keyword_enocder.get(word) for word in keyword_list)
    return keywords

In [25]:
get_keywords(pre.df.keywords.iloc[0])

'पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अमेरि रियालसम्म यस्तै दिराम युएई पाउण्ड रियाल युरो यसैगरी यस्तो राष्ट्र बैंक अनुसार नेपाल'

In [26]:
pre.df['keywords_words'] = pre.df.apply(lambda x: get_keywords(x['keywords']), axis=1)

In [27]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",ज्ञानेन्द्र भ्रम राजा अन्याय भट्टराई कटाक्ष तप...
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व...",कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरे...
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...","हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, ..."
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्...

In [81]:
pre.article_df = pre.df.drop_duplicates(subset = ['article_id']).reset_index(drop=True)

In [83]:
pre.article_df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,83ba6e048bfb2245baeff4a8c40a7372,https://www.ratopati.com/story/94749,[],['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,रातोपाटी संवाददाता,...,"सुस्मिता चुम्बन गरिरह भेटिए प्रेमी, फोटो चर्चि...","[5968, 30411, 14608, 14843, 9248, 1574, 8248, ...",3,1.520255,95385,31538,20,yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI,"[सुष्मिता, रोहमन, छुट्टी, तस्बिर, चुम्बन, प्रे...","सुष्मिता रोहमन छुट्टी तस्बिर चुम्बन प्रेमी, मु..."
2,a704f987e0bc79f6bc185228f1cdfe8a,https://www.ratopati.com/story/94766,[],['काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्ट...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,"सरकार वार्ता पक्ष देखिएन, युद्ध धकेल्न खोज्योः...","[27982, 34743, 30577, 20802, 28810, 27104, 253...",2,1.909831,120855,31547,21,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U,"[पक्ष, विवाद, पार्टी, अनुसार, संयुक्त, बैठक, आ...","विप्लव वार्ता युद्ध जबरजस्त धकेल्न शान्ति, सरक..."
3,a7c27e8ad54f246d33d92c85921c21eb,https://www.ratopati.com/story/94769,[],['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,सर्लाही छुट्टाछुट्टै दुर्घटना मृत्यु काठमाडौं–...,"[11916, 31053, 32043, 21744, 8895, 162, 10331,...",5,1.836916,121370,31549,13,2gafeJYipiE31yBVKVOTjGN2bCdzFUPHZ8ymiWoiIvk,"[लागि, पार्टी, तयार, सरकार, प्रधानमन्त्री, दुर...",मृत्यु दुर्घटना घाइते उपचार बालक मोटरसाइकल लाल...
4,1c58fbb11cd5d6aa48c87b9d5404fddb,https://www.ratopati.com/story/94721,[],['बुटवल-अनैतिक सम्बन्ध राखेको आरोपमा नवलपरासीक...,2076-04-06 00:00:00+05:45,https://ratopati.prixa.net/media/albums/arrest...,होटलमा अनैतिक सम्बन्ध राख्ने १० जना पक्राउ,समाचार,ratopati,रातोपाटी संवाददाता,...,होटल अनैतिक सम्बन्ध राख् पक्राउ बुटवल-अनैतिक स...,"[36721, 14183, 36254, 15011, 18182, 5073, 6950...",0,1.391775,20538,31529,31,UhK8tdrfsbFHVGSSnfApmu37DePbCDPedGr2whVu2AI,"[होटेल, होटल, अनैतिक, पक्राउ, नवलपरासी, सञ्चाल...",होटेल होटल अनैतिक पक्राउ नवलपरासी सञ्चालक प्रह...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38049,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
38050,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",ज्ञानेन्द्र भ्रम राजा अन्याय भट्टराई कटाक्ष तप...
38051,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व...",कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरे...
38052,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...","हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, ..."
38053,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्...

In [85]:
user_df = pre.df.drop_duplicates(subset = ['user']).reset_index(drop=True)

In [88]:
pre.user_df = user_df[['user','user_keywords']]

In [6]:
pre.user_df

,user,user_keywords
0,db783e901db42f2290736d314d08bdea,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
1,83ba6e048bfb2245baeff4a8c40a7372,"[सुष्मिता, रोहमन, छुट्टी, तस्बिर, चुम्बन, प्रे..."
2,a704f987e0bc79f6bc185228f1cdfe8a,"[पक्ष, विवाद, पार्टी, अनुसार, संयुक्त, बैठक, आ..."
3,d9c3dae87d793c35fea9620a293962f4,"[विप्लव, वार्ता, युद्ध, जबरजस्त, धकेल्न, शान्त..."
4,a7c27e8ad54f246d33d92c85921c21eb,"[लागि, पार्टी, तयार, सरकार, प्रधानमन्त्री, दुर..."
...,...,...
185312,452aa355ab3ea4de4742e5ff36320eaf,"[भर्सन, फिमेल, सार्वजनिक, लामा, भने।, कम्पोज, ..."
185313,5cb16210f5bc5f18bb852ab846f3b5a2,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्..."
185314,93c95988ec06dc1569a02ccb931c43a4,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा..."
185315,433f43b6a40299d0a8c70351a2b57324,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ..."
185316,72afa487553978646c986b80c6970d80,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प..."

In [7]:
def save_pkl(obj, filename):
    with open(filename, 'wb') as outp:  # Overwrites any existing file.
        pickle.dump(obj, outp, pickle.HIGHEST_PROTOCOL)

In [91]:
save_pkl(pre, "pre_user_keywords.pkl")

In [10]:
pre.df.article_id.unique(), len(pre.df.article_id.unique())

(array(['ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA',
        'yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI',
        'PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U', ...,
        'yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8',
        'bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA',
        'ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng'], dtype=object),
 38054)

In [15]:
pre.article_df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,83ba6e048bfb2245baeff4a8c40a7372,https://www.ratopati.com/story/94749,[],['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,रातोपाटी संवाददाता,...,"सुस्मिता चुम्बन गरिरह भेटिए प्रेमी, फोटो चर्चि...","[5968, 30411, 14608, 14843, 9248, 1574, 8248, ...",3,1.520255,95385,31538,20,yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI,"[सुष्मिता, रोहमन, छुट्टी, तस्बिर, चुम्बन, प्रे...","सुष्मिता रोहमन छुट्टी तस्बिर चुम्बन प्रेमी, मु..."
2,a704f987e0bc79f6bc185228f1cdfe8a,https://www.ratopati.com/story/94766,[],['काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्ट...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,"सरकार वार्ता पक्ष देखिएन, युद्ध धकेल्न खोज्योः...","[27982, 34743, 30577, 20802, 28810, 27104, 253...",2,1.909831,120855,31547,21,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U,"[पक्ष, विवाद, पार्टी, अनुसार, संयुक्त, बैठक, आ...","विप्लव वार्ता युद्ध जबरजस्त धकेल्न शान्ति, सरक..."
3,a7c27e8ad54f246d33d92c85921c21eb,https://www.ratopati.com/story/94769,[],['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,सर्लाही छुट्टाछुट्टै दुर्घटना मृत्यु काठमाडौं–...,"[11916, 31053, 32043, 21744, 8895, 162, 10331,...",5,1.836916,121370,31549,13,2gafeJYipiE31yBVKVOTjGN2bCdzFUPHZ8ymiWoiIvk,"[लागि, पार्टी, तयार, सरकार, प्रधानमन्त्री, दुर...",मृत्यु दुर्घटना घाइते उपचार बालक मोटरसाइकल लाल...
4,1c58fbb11cd5d6aa48c87b9d5404fddb,https://www.ratopati.com/story/94721,[],['बुटवल-अनैतिक सम्बन्ध राखेको आरोपमा नवलपरासीक...,2076-04-06 00:00:00+05:45,https://ratopati.prixa.net/media/albums/arrest...,होटलमा अनैतिक सम्बन्ध राख्ने १० जना पक्राउ,समाचार,ratopati,रातोपाटी संवाददाता,...,होटल अनैतिक सम्बन्ध राख् पक्राउ बुटवल-अनैतिक स...,"[36721, 14183, 36254, 15011, 18182, 5073, 6950...",0,1.391775,20538,31529,31,UhK8tdrfsbFHVGSSnfApmu37DePbCDPedGr2whVu2AI,"[होटेल, होटल, अनैतिक, पक्राउ, नवलपरासी, सञ्चाल...",होटेल होटल अनैतिक पक्राउ नवलपरासी सञ्चालक प्रह...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38049,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
38050,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",ज्ञानेन्द्र भ्रम राजा अन्याय भट्टराई कटाक्ष तप...
38051,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व...",कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरे...
38052,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...","हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, ..."
38053,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्...

In [16]:
docs = pre.article_df.keywords_words.values

In [17]:
docs, len(docs)

(array(['पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अमेरि रियालसम्म यस्तै दिराम युएई पाउण्ड रियाल युरो यसैगरी यस्तो राष्ट्र बैंक अनुसार नेपाल',
        'सुष्मिता रोहमन छुट्टी तस्बिर चुम्बन प्रेमी, मुस्कुराइरह फोटो सुस्मिता भेटिए सेल्फी गाला आफ्ना होला, नायि मिडियामार्फत् इन्टरनेट मनाइरह उत्सव एउटा',
        'विप्लव वार्ता युद्ध जबरजस्त धकेल्न शान्ति, सरकार पक्ष कार्यकर्ता समृद्धि लगाएर देखिएन, कुप्रचार झूठो स्पष्टै झूटा नरहेर प्रतिवन्धित बढावा सकिन्छ’,',
        ...,
        'कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरेन्द्र मन्त्री सहभागी सिंह सरकार यादव प्रदेश तर्फबाट बन्दैछन्। सिँचाई मन्त्रालय, केन्द्र गरेकाे फुटाएर लागिसक',
        'हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, बेलायत, छन्। मुलुक कोरोनाबाट संक्रमित पेरु, थिए। जहाँ हजार, अछुतो टर्की, उच्च हालसम्म',
        'सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्रदेश कमिटी रावल माओवा समूह प्रभाव असफल फिर्ता संसदीय मतदान मन्त्री बोहरा, स्पष्टीकरण पटक–पटक'],
       dtype=object),
 38054)

In [18]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)
X

<38054x5032 sparse matrix of type '<class 'numpy.float64'>'
	with 599431 stored elements in Compressed Sparse Row format>

In [19]:
X.T.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
pre.tfidfVectors = pd.DataFrame(X.T.toarray(), index=vectorizer.get_feature_names())
pre.tfidfVectors

/home/prixa-ml/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,0,1,2,3,4,5,6,7,8,9,...,38044,38045,38046,38047,38048,38049,38050,38051,38052,38053
mन,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
अक,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
अकबर,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
अकर,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
अकल,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
९५३७,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
९७,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
९८,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
९९,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
९९९९९९,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
save_pkl(pre, "pre_user_keywords.pkl")

In [30]:
pre.tfidfVectors.shape[1]

38054

In [31]:
def get_similar_articles(q, pre):
  print("query:", q)
  print("Articles with high cosine similarity are: ")
  q = [q]
  q_vec = vectorizer.transform(q).toarray().reshape(pre.tfidfVectors.shape[0],)
  sim = {}
  for i in range(pre.tfidfVectors.shape[1]):
    sim[i] = np.dot(pre.tfidfVectors.loc[:, i].values, q_vec) / np.linalg.norm(pre.tfidfVectors.loc[:, i]) * np.linalg.norm(q_vec)
  
  sim_sorted = sorted(sim.items(), key=lambda x: x[1], reverse=True)
  
  for k, v in sim_sorted:
    if v != 0.0:
      print("Article Similarity:", v)
      print(docs[k], pre.article_df.url.iloc[k])
      print()

In [27]:
pre.article_df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,83ba6e048bfb2245baeff4a8c40a7372,https://www.ratopati.com/story/94749,[],['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,रातोपाटी संवाददाता,...,"सुस्मिता चुम्बन गरिरह भेटिए प्रेमी, फोटो चर्चि...","[5968, 30411, 14608, 14843, 9248, 1574, 8248, ...",3,1.520255,95385,31538,20,yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI,"[सुष्मिता, रोहमन, छुट्टी, तस्बिर, चुम्बन, प्रे...","सुष्मिता रोहमन छुट्टी तस्बिर चुम्बन प्रेमी, मु..."
2,a704f987e0bc79f6bc185228f1cdfe8a,https://www.ratopati.com/story/94766,[],['काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्ट...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,"सरकार वार्ता पक्ष देखिएन, युद्ध धकेल्न खोज्योः...","[27982, 34743, 30577, 20802, 28810, 27104, 253...",2,1.909831,120855,31547,21,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U,"[पक्ष, विवाद, पार्टी, अनुसार, संयुक्त, बैठक, आ...","विप्लव वार्ता युद्ध जबरजस्त धकेल्न शान्ति, सरक..."
3,a7c27e8ad54f246d33d92c85921c21eb,https://www.ratopati.com/story/94769,[],['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,सर्लाही छुट्टाछुट्टै दुर्घटना मृत्यु काठमाडौं–...,"[11916, 31053, 32043, 21744, 8895, 162, 10331,...",5,1.836916,121370,31549,13,2gafeJYipiE31yBVKVOTjGN2bCdzFUPHZ8ymiWoiIvk,"[लागि, पार्टी, तयार, सरकार, प्रधानमन्त्री, दुर...",मृत्यु दुर्घटना घाइते उपचार बालक मोटरसाइकल लाल...
4,1c58fbb11cd5d6aa48c87b9d5404fddb,https://www.ratopati.com/story/94721,[],['बुटवल-अनैतिक सम्बन्ध राखेको आरोपमा नवलपरासीक...,2076-04-06 00:00:00+05:45,https://ratopati.prixa.net/media/albums/arrest...,होटलमा अनैतिक सम्बन्ध राख्ने १० जना पक्राउ,समाचार,ratopati,रातोपाटी संवाददाता,...,होटल अनैतिक सम्बन्ध राख् पक्राउ बुटवल-अनैतिक स...,"[36721, 14183, 36254, 15011, 18182, 5073, 6950...",0,1.391775,20538,31529,31,UhK8tdrfsbFHVGSSnfApmu37DePbCDPedGr2whVu2AI,"[होटेल, होटल, अनैतिक, पक्राउ, नवलपरासी, सञ्चाल...",होटेल होटल अनैतिक पक्राउ नवलपरासी सञ्चालक प्रह...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38049,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
38050,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",ज्ञानेन्द्र भ्रम राजा अन्याय भट्टराई कटाक्ष तप...
38051,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व...",कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरे...
38052,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...","हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, ..."
38053,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्...

In [25]:
get_similar_articles('कांग्रेस माओवा मन्त्रालय', pre)

query: कांग्रेस माओवा मन्त्रालय
Articles with high cosine similarity are:
Article Similarity: 0.4866589567779995
सहायक बढुवा जनमुक्ति जंगी बाँस्कोटा समायोजन अड्डा अधिकारी रक्षा सरकार निर्णय सेना मन्त्रालय दर्जा गोकुल प्रतीक्षा मनोबल टुंगो माओवा मन्त्रिपरिषद https://www.thahakhabar.com/news/79785

Article Similarity: 0.4632434741392214
मन्त्री माओवा थापा रायमाझी, पत्र कारवाही केन्द्र गृहमन्त्री रामबहादुर चौधरी मन्त्रीमध्ये सिंचाइमन्त्री जलश्रोत सदस्य नेकपा पाँचै गौरीशंकर माओवादीबाट पूर्ववत् बाणिज्य https://www.ratopati.com/story/174681

Article Similarity: 0.4353373040142819
विश्वास धारा माओवा अविश्वास सरकार फिर्ता समर्थन संविधान अर्थात्, एमाल विभाजित अदालत प्रस्ताव दिनभित्र राजनीति फागुन प्रधानमन्त्री सांसद ढिक् माओवादीबीच https://www.ratopati.com/story/172926

Article Similarity: 0.4345693563279929
बैठक सांगठनिक स्थगित दुरुस्त चुस्त धारणा सैद्धान्तिक पार्टी नेता वार्ता माओवा बोले दोस्रो माओवादीबाट पेरिसडाँडा केहीदिन टुंग एकतावद्ध स्पष्टिकरण सोमबार https://www.ratopati.com/story/171844

Article Similarity: 0.4297799572231364
फिर्ता मन्त्री माओवा पत्र हुनेबारे हुलाक दावा प्रभु तामाङ निर्देशनसहित एमालेतिर चिठ्ठी जवाफ गौरीशंकर माओवादीबाट बैठक पेरिसडाँडा समयभित्र रायमाझी, सोमबारसम्म https://www.ratopati.com/story/171891

Article Similarity: 0.42785896176779337
रिजाल अपराधिक मिनेन्द्र क्रियाकलाप नेता बाटो निर्देशन द्वन्द्वकाल माओवा मन्त्रालय तनहुँ आरोप लामिछा शाखा शिलान्यास अनेक दुःख प्रतिबन्ध हिंसा अन्तरक्रिया https://www.thahakhabar.com/news/80688

Article Similarity: 0.4254702310454217
मातृ प्रभु मधेश यादव अन्तरसंघर्ष बाबुराम संघर्ष तत्कालिन प्रचण्ड पार्टी मन्त्री समूह नेता अवसर दुवैजना बताइन् मधेशी पक्ष माओवा माओवादीबाट https://www.ratopati.com/story/162980

Article Similarity: 0.42165995375263166
सारु दवाव बालि गाउँ भित्र्याई बालिका महिला गुल्मी मुद्धा काँग्रेस बृद्ध बलात्कार वर्षीया पक्राउ पैसा राना माओवा नेता त्यस्तो फिर्ता https://www.ratopati.com/story/118639

Article Similarity: 0.4193503677295688
मन्त्रिपरिषद कर्मचारी मामिला मुख्यमन्त्री मन्त्रालय कार्यालय कामकाज संक्रमण आन्तरिक कोरोना बन्द मन्त्री मन्त्रालय, निषेध यादव, विकास पुष्टि सामाजिक नम्बर प्रदेशसभा https://www.ratopati.com/story/141674

Article Similarity: 0.4158216688457471
ठेक् कार्यकर्ता मेलम्ची बिनाप्रतिस्पर्धा पूर्वमाओवा कन्स्ट्रक्सन आयोजना रुपैयाँ धमाधम करोड माओवा कँडेल श्रेष्ठ ठेकेदार निर्णय मोदनाथ अभिषेक जाली अर्ब मन्त्रिपरिषद् https://www.ratopati.com/story/94853

Article Similarity: 0.40907550066187015
उहाँ माधव पहिचान नेता माओवा हारेर म्याद प्रभु प्रचण्ड चुनाव औषधि थपे, गर्नुभ नेपाल, कमिटी नारायणकाजी एमाल प्रयोग नेपालप्रति माओवाद https://www.thahakhabar.com/news/115489

Article Similarity: 0.4068669114623215
कमिटी केन्द्रीय बैठक स्थगित राजनीतिक निम्ति केन्द्र) पछाडी नेकपा(माओवा अनिश्चितकाल संगठनात्मक पुन, भनाई कार्यभार पुनरावलोकन तत्कालिन पार्टी सुरुवात वार्ता माओवा https://www.ratopati.com/story/171866

Article Similarity: 0.39610678980963315
समीकरण सत्ता माओवा दलबीच अनिश्चित दलहरुबीच समाजवा वार्ता सहमति वार्ताबारे थाहा बैठक नयाँ माओवादीबीच लेनदेन काँग्रेस काँग्रेस, देउवा फर्के छैन’, https://www.ratopati.com/story/171808

Article Similarity: 0.3927355439667188
राजदूत सचिव सरकार सरुवा राणा कांग्रेस स्वास्थ्य तत्कालीन फिर्ता माओवा नियुक्त कोइराला पराजुली सासू मन्त्रालय नेता खगराज पाला रामप्रसाद लीलामणि https://www.lokaantar.com/story/102028

Article Similarity: 0.39055050586483286
ढुंगेल पक्ष हत्या सजाय पूर्वमाओवा छन्‌। प्रचण्ड छुटे माओवा जेलबाट बालकृष्ण गौतम थिएनन्। तत्कालिन अभियोग कारण श्रेष्ठ जनयुद्ध नेता योगदान https://www.thahakhabar.com/news/115326

Article Similarity: 0.3855386915095278
सुरुङ थियो। भयो। हामी योजना निस्क ब्रेक सुर्खेत पानी गिरफ्तार गरियो। बाहिर सुरक्षा पोष्ट हाम्रो माओवा थिए। विभिन्न थाहा खुला https://www.thahakhabar.com/news/89105

Article Similarity: 0.37848119222035603
सभामुख पार्टी पूर्वमाओवा राष्ट्रपति निवास प्रधानमन्त्री भागवण्डा महरा राजीना पूर्व एकता तर्क भविष्य माओवा नेकपा तत्कालीन दबाब पार्टीभित्र बैठक अडान https://www.ratopati.com/story/113774

Article Similarity: 0.3774519364685098
नेकपा घोषणा पार्टी माओवा सम्मेलन पत्रकार नेतृत्व केन्द्र कार्यकर्ता क्लब पुरानो रहेर सदस्यीय आरोप बाध्य राखे सचिवालय सिंह मुद् तत्कालीन https://www.ratopati.com/story/141407

Article Similarity: 0.37312807252666846
प्रदेशसभा रेग्मी सूचना त्याग पदमुक्त कर्णाली माओवा केन्द्र सचिवालय प्रकाशित जानकारी प्रवेश प्राप्त जीवराज सचिव सदस्य त्यागेर धर्मराज मनोनीत दैलेख https://www.thahakhabar.com/news/122727

Article Similarity: 0.371187347102374
मन्त्री सुनसान मन्त्रालय हल्ला मन्त्रालय, हटाउ सचिवालय महासेठ चहलपहल सबभन् कर्मचारी यादव मन्त्रीज्यू पण्डित रघुवीर खनाल कार्यकक्ष भिडभाड जिज्ञासा गृहमन्त्रालय https://www.ratopati.com/story/106804

Article Similarity: 0.3687696381489316
महरा प्रकरण राजीना सभामुख नेकपा नेतृ सचिवालय महिला अनुशासन नेता संसद् मनोवैज्ञानिक नेकपाभित्र उजुरी ठूलो यस्ता समस्या तत्कालीन अधिवेशन माओवा https://www.ratopati.com/story/102385

Article Similarity: 0.36766507540465154
थापा सेयर स्टाटस कार्यकर्ता तपाईं छन्, एकता माओवा पूर्वमाओवा तत्कालीन पार्टी छन्। एउटा सल्लाहकार फेसबुक भन्‍ पक्षबीच समाचार प्रचण्ड सूर्य https://www.thahakhabar.com/news/86088

Article Similarity: 0.3588492924776115
साँझ मन्त्री अलावा स्रोत गराइ साह, टोपबहादुर मन्त्रिमण्डल प्रभु नवनियुक्त पुनर्गठन रायमाझी पूर्वमाओवा विस्तार मन्त्रिपरिषद प्रधानमन्त्री त्यस्तै मन्त्रिपरिषद् बालुवाटार सहभागी https://www.thahakhabar.com/news/114820

Article Similarity: 0.3562039832741347
जिम्मेवारी खेलकुदमन्त्री हेरफेर विघटित गौरीशंकर दावा विश्वकर् विमला टोपबहादुर पूर्वमाओवा प्रभु मन्त्रिपरिषद् बालबालि राज्यमन्त्री ग्रहण मन्त्री उद्योग जुलीकुमारी राज्यमन्त्रीसहित मन्त्रालय https://www.ratopati.com/story/160602

Article Similarity: 0.3526019563390211
सभामुख पूर्वमाओवा नेता पक्ष अध्यक्ष पूर्वएमा भेला मनोविज्ञान नेम्बाङ दाहाल एकता भैंसेपाटी पार्टी अप्ठेरो सचिवालय निर्णय सापकोटा समीकरण अनुमोदन सहमत https://www.lokaantar.com/story/98283

Article Similarity: 0.3510370472258099
रेग्मी माओवा कँडेल प्रदेश धर्मराज सुर्खेत सांसद मुख्यमन्त्री पक्ष एमाल विष्ट शाही कर्णाली निर्वाचित उल्टै मनोनित विरुद्ध अविश्वास केन्द्रबाट इन्चार्ज https://www.ratopati.com/story/171499

Article Similarity: 0.3487758357887352
पक्ष प्रचण्ड–माधव केपी सदस्य केन्द्रीय प्रदेश पूर्वमाओवा पूर्व नेकपा सुदूरपश्चिम कमिटी विभाजन सदस्यमध्ये भट्ट समूह माओवा प्रदेशबाट अस्तित्व जनामध्ये सचिव https://www.ratopati.com/story/163461

Article Similarity: 0.3487592628185517
जसपा माओवा काँग्रेस गठबन्धन संवाद चेञ्जर एमाले–माओवा देउवा सरकार ढाल्न योबीच प्रचण्ड छलफल अग्रसरता दलबीच निर्णय बूढानीलकण्ठ अर्थपूर्ण टेलिफोन निधि https://www.ratopati.com/story/175090

Article Similarity: 0.3460326818543528
माओवा सांसद पत्र दर्ता सचिवालय निलम्बन संसद गुरुङ कारबाही कारबाही, गौरी सोबारे चारै रायमाझी, गराइसक भट्ट, प्रभु लेखराज मन्त्री स्पष्टीकरण https://www.ratopati.com/story/174723

Article Similarity: 0.3450677565043573
माओवा कांग्रेस प्रतिपक्षी प्रमुख प्रदेश सांसद प्रतिपक्ष बानियाँ भूमि बागमती एमाले केन्द्र सुविधा प्रदेशसभा सभामुखसहित जमरकट्टेल कमाल हुनुपूर्व एमाले–माओवा खुम्च https://www.ratopati.com/story/175364

Article Similarity: 0.34194426370297143
सम्पत्ति नेकपा विवरण गाडी नेता पार्टी तत्कालीन बाबुराम माओवा सचिव बुढाथोकी केन्द्र श्रीराम प्रतिबन्धित अन्य नेत्रविक्रम कार्यालय पूर्वप्रधानमन्त्री विप्लव रामकृष्ण https://www.ratopati.com/story/102436

Article Similarity: 0.33718906002416565
प्रतिनिधिसभा विघटन पूर्वमाओवा सरकार टोपबहादुर पक्ष सामेल इजलास फैसला धरापमा, रनभुल्ल वहिर्गमन वर्तमान संवैधानिक माओवा अघिमात्र हुनासाथ पूर्व रायमाझी, केही https://www.ratopati.com/story/169182

Article Similarity: 0.3371778890479113
पानी मन्त्रालय कार्यालय खर्च कार्टुन सहसचिव सचिव पाण्डे मन्त्रिपरिषद पाण्ड कर्मचारी प्रवक्ता दैनिक रुपैयाँ सरकार भइरह बालुवाटार आधुनिक मन्त्री प्रशासन https://www.ratopati.com/story/149832

Article Similarity: 0.3371518783271922
शय्या रोल्पा गाउँपालिका, अस्पताल मन्त्री आधारभूत शिलान्यास जनता गाउँपालिका सिंहदरबार विगत माडी त्रिवेणी सरकार अधिकार पालिका निर्माण स्वास्थ्य माओवा भनाइ https://www.ratopati.com/story/157097

Article Similarity: 0.336748609900374
मन्त्री भुसाल कृषि चर्चा कृषिमन्त्री जिसी पशुपन्छी मन्त्रालय बसेर सचिव बोल् व्यक्ति जस्तो सचिवालय कर्मचारी छैनन् केही जागिरबाट बितिसक् सम्हाल https://www.lokaantar.com/story/102043

Article Similarity: 0.3346829549952804
राजीना ज्वाला कर्णाली मन्त्री मामिलामन्त्री प्रदेश एमाल प्रकाश समर्थन नन्दसिंह माओवा ज्वाला, नेकपा फिर्ता वातावरणमन्त्री तीनैजना निर्णय आर्थिक केन्द्र पर्यटन, https://www.ratopati.com/story/174533

Article Similarity: 0.3333880448008624
सचिव सेवानिवृत्त कानुन मन्त्रालय निवृत्त विनोद सेवा श्रम कोही सञ्चार क्रम प्रविधि कार्यालय प्रधानमन्त्री अवधि गौतम केसी, घिमिरे, बिडारी मन्त्रिपरिषद् https://www.ratopati.com/story/128620

Article Similarity: 0.3332991314908651
माओवा एमाले प्रवेश सांसद नेता माओवादीबाट प्रधानमन्त्री प्रदेश कारवाही केही देशैभरि एमाल ढिक् एमालेबाट प्रलोभन भन्यो, तल्लो प्रवाह क्रम थापा, https://www.ratopati.com/story/175458

Article Similarity: 0.32705792854409266
बैठक सचिवालय प्रचण्ड अध्यक्षता सिंगापुर पार्टी अध्यक्ष पहिलो गराईरह टुङ्गाउ कार्यालय जानुभन् नेकपा एकता पार्टी(नेकपा) घण्टा पदाधिकारी, पालैपालो माओवादीबीच प्रवास https://www.ratopati.com/story/98171

Article Similarity: 0.32688704553620146
माओवा मुख्यमन्त्री सम्हाल् जनमोर्चा गण्ड गुरुङ जिम्मेवारी समर्थन बस्नेत मन्त्रालय लेखबहादुर गिराउ भूमि, सरकार सरकारबाट फकाउ प्रदेश पृथ्वीसुब्बा मामिला केन्द्र https://www.ratopati.com/story/175144

Article Similarity: 0.32529799501032114
विज्ञान दिवस मनाउन शिक्षा, विद्यालय सातौँ निकाय, गिरिराजमणि जोडि आग्रह क्षेत्र, मन्त्रालय गराइ गठित प्रतिनिधित्व प्रदेश आ–आफ्नो प्रविधिमन्त्री स्थानीय ढङ्ग https://www.ratopati.com/story/99007

Article Similarity: 0.32376177019708285
कमिटी पार्टी प्रदेशबाट केन्द्रीय रिपोर्टिङ रिर्पोटिङ हाम्रो तर्फबाट श्रेष्ठ कार्यभार बैठक मन्त्री मर्म नेकपा(माओवा सुसूचित केन्द्र इन्चार्ज काफ्ले, मायाप्रसाद सरकारबाट https://www.ratopati.com/story/171722

Article Similarity: 0.32245184747649436
मन्त्रालय, विधेयक, २०७७ जवाफ कार्यसूची प्रस्तुत मन्त्री गरियोस् विनियोजन शीर्षक विभिन्न अध्यादेश प्रस्ताव यस्तै, प्रश्न मामिला प्रविधि कार्यसुची विचार मन्त्रालय https://www.ratopati.com/story/133652

Article Similarity: 0.321932206766731
मन्त्रालय मन्त्रालय, मन्त्री शहरी जिम्मेवारी मन्त्रिमण्डल हेरफेर महिना पटक, कर्मचारीतन्त्र वाग् नेतृत्व अस्थिर नियुक्त राज्यमन्त्री विकास अवधि कृष्णगोपाल यादव अवस्था https://www.ratopati.com/story/161181

Article Similarity: 0.3218447339673054
विधेयक प्रदेश प्रस्ताव गठबन्धन बैठक पुरानै अधिवेशन माओवा लुम्बिनी ब्युँतिए सातौं सचिव विभाजित छलफल कुर्सी दुर्लभ सरकार सैद्धान्तिक मन्तव्य सम्बन्धि https://www.ratopati.com/story/173883

Article Similarity: 0.3194925112356836
मोरालेस बोलिभियाली मेक्सिको राजिना शरणार् विदेश स्वीकार विदेशमन्त्री इमान्दारिता मन्त्रालय, मानवीयता मार्सेलो राष्ट्रपतिबाट राजनीतिक बोलिभिया राजिनामा मेक्सि गराइ मन्त्रालय दिनुभ https://www.ratopati.com/story/106064

Article Similarity: 0.31690351506977843
पार्टी नेकपा परिवर्तन संशोधन सचिवालय निर्णय कमिटी कम्युनिष्ट माओवा लागु अध्यक्षता फेरि बढ्न सत्तारुढ स्थापना पारित थियो। तत्काल प्रवक्ता स्थायी https://www.thahakhabar.com/news/85978

Article Similarity: 0.3141055866156174
परीक्षा बाटो सञ्चालन स्थगित शैक्षिक संस्था खुला उपस्थिति धमाधम विश्वविद्यालय विद्यालय भौतिक सिफारिस विद्यार् मन्त्रालय विद्यालय, विश्वविद्यालय, सरकार गरिद गर्नेगरी https://www.ratopati.com/story/150255

Article Similarity: 0.31393239323776073
तत्कालीन तर्फबाट हटाउ मन्त्री प्रधानमन्त्री टुंगो राख् प्रचण्ड निश्चित एमाल अधिकार यादव स्थगित माओवा खनाल सल्लाहकार प्रेस सचिवालय कार्यव्यस्तता भट्ट https://www.ratopati.com/story/107058

Article Similarity: 0.31096025546715905
अविश्वास फिर्ता प्रस्ताव राईविरुद्ध माओवा प्रदेशसभा संसदीय प्रदेश हस्ताक्षर मुख्यमन्त्री कर्णाली घण्टाभित्र राजीना बैठक धरापमा, नन्दसिंह गुलावजंग एमाले–माओवा ज्वाला, मार्गप्रशस्त https://www.ratopati.com/story/174515

Article Similarity: 0.30916188308016046
विभाग स्कूल नेता नियमावली तत्कालिन महत्त्वपूर्ण पार्टी कमरेड नेकपा माओवा सचिवालय पोखरेल कमिटी दावी जनवाद’ स्कुल मानि कार्यनीति प्रशिक्षण जिम्मेवारी https://www.ratopati.com/story/94921

Article Similarity: 0.30915745961698043
सरुवा सह–सचिव नियन्त्रक मन्त्रालय मामिला मन्त्रालय, कोइराला शोभाकान्त प्रदेश प्रशासन भुपाल महालेखा संघीय सरुवा, सामान्य आयोग, अर्थमन्त्रालय बराल अन्र्तगत प्रवक्ता https://www.ratopati.com/story/137345

Article Similarity: 0.30398087936227025
चीनबाट नेपाली ढकाल मन्त्रिपरिषद क्वारेन्टाइन संक्रमण मन्त्री छलफल राख् मन्त्रालय क्रम चिन्ता सातासम्म ल्याइ नेपाल वार्ड स्वास्थ्यमन्त्री बैठक भानुभक्त ल्याउ https://www.ratopati.com/story/116765

Article Similarity: 0.3030169441371288
संशोधन संविधान कानुन यादव प्रस्ताव पार्टी समाजवा मन्त्रालय सत्ताधारी उपेन्द्र तयार मन्त्री मन्त्रिपरिषद् प्रकृया बारे बताए एउटा मन्त्रालयबाट विषय सरकार https://www.ratopati.com/story/107693

Article Similarity: 0.30261347672631334
युद्ध जनयुद्ध माओवा छोरा पत्रकारिता पीडित संघर्ष शान्ति अधिकार समाचार आश्रम बालक राजन दैलेख पक्ष बाँच खुसी छोडेर दुःख पार्टी https://www.thahakhabar.com/news/108474

Article Similarity: 0.3022571672531469
सहमति क्रान्तिकारी बुँदे नेतृत्व सहकार्य केन्द्रबीच पार्टीबीच नेत्र नेकपा केन्द्र) बुढाथो विक्रम विप्लव पार्टी वैज्ञानिक माओवा चन्द राखी कम्युनिस्ट समाजवा https://www.ratopati.com/story/171599

Article Similarity: 0.30222286390327896
सचिव सरुवा आयोग मन्त्रालय मन्त्रिपरिषद् कार्यालय दर्जन वित्त प्रधानमन्त्री लोकसेवा खेलकुद निकाय यस्तै, स्रोत वाणिज्य युवा शिक्षा उद्योग अख्तियार निर्वाचन https://www.ratopati.com/story/167717

Article Similarity: 0.30172145593490307
मन्त्रालय कोरोना संक्रमण निर्देशनालय अपडेट स्वाव प्रदेश पीसीआर पुष्टि बुटवल सामाजिक नेगेटिभ संकलन सम्पर्क अधिकारी रिपोर्ट विकास उच्च मन्त्री कर्मचारी https://www.ratopati.com/story/142704

Article Similarity: 0.300888388835531
माओवा मन्त्री प्रभु एमालेतिर नफर्क बादल, ओलीतिर फिर्ता दावा सदस्यसहित निर्देशन निर्देश थापा केन्द्र पार्टी भट्ट, कोटा साह, कोटेश्वर लेखराज https://www.ratopati.com/story/171539

Article Similarity: 0.3005961810314369
जसपा लुम्बिनी प्रदेश सरकार माओवा तानातान समीकरण केन्द्र समर्थन मन्त्री भौतिक बराल भैरह निर्णायक बताइरह पर्छ। हाम्रो सामाजिक गठबन्धन चौधरी https://www.thahakhabar.com/news/120705

Article Similarity: 0.30047166238370665
पार्टी यादव मन्त्री प्रधानमन्त्री राजीना उपेन्द्र कुरा समाजवा बारे इस्तियाक नेता मन्त्रालय पार्टीभित्र सम्बन्ध पत्र राम्रो सरकारबाट पदबाट दुवैजना कार्यालय https://www.ratopati.com/story/111751

Article Similarity: 0.3004144563553935
बजेट पूँजीगत कार्यान्वयन खर्च पौडेल अर्थमन्त्री विकासे मन्त्रालय मन्त्रालय, आर्थिक खर्ब चालु श्रेष्ठ मन्त्री अवस्थाबारे तयारी आयोजना पुनर्निर्माण बढ्न बढाउन https://www.ratopati.com/story/154250

Article Similarity: 0.299947107517478
मन्त्री प्रचण्ड केपी चाहँ स्थिति पाइला हरिबोल प्रभु अध्यक्ष पूर्वमाओवा हटाउ कोही होइन सचिव प्रधानमन्त्री कुमारप्रसाद तोडेर सूत्रधार गरौं तारेख https://www.ratopati.com/story/151140

Article Similarity: 0.2991205811313418
विश्वकर्मा राखेप मनोनयन मन्त्री सदस्य खेलकूद बोर्ड निरौला राष्ट्रिय चितवन मन्त्रालय उपाध्यक्ष सचिव श्रेष्ठ बागलुङ मनोनित साहसिक क्षेत्रबाट ग्रहण नुवाकोट https://www.ratopati.com/story/140792

Article Similarity: 0.29814288458080884
ज्वाला शाही कठोर क्रस’ नेतृत्व सांसद एमाल शिक्षा निर्णय पार्टी कर्णाली कारबाही प्रकाश बाध्य मुख्यमन्त्री भोग्न ह्वीप माओवा सरकार बुढा https://www.thahakhabar.com/news/123046

Article Similarity: 0.29794913792795324
मन्त्री धारा सांसद पुनर्नियुक्ति संविधान नियुक्त प्रधानमन्त्री गौरीशंकर चौधरी चारै रायमाझी, टोपबहादुर प्रभु स्वतः लेखराज माओवा व्यवस्था नेम्वाङ भट्ट पदबाट https://www.ratopati.com/story/175041

Article Similarity: 0.29775456656792815
अविश्वास साबिक नेता ओलीविरुद्ध दाहाल–नेपाल कहिल्यै प्रस्ताव लैजान त्यस गरे। राजनीति संसदीय पार्टी माओवा सर्वोच्च चुचुरो पाए। लागे। फर्किए। मोर्चाबन् https://www.ratopati.com/story/171124

Article Similarity: 0.2976666196320437
प्रस्ताव जसपा सहकार्य प्रतिगमन राजनीतिक उल्लेख नाङ्गै अध्यक्ष मधेस केन्द्र माओवा काँग्रेस त्यस शासन यादव धर्मनिरपेक्षता संविधान संसद परिस्थिति लागि https://www.ratopati.com/story/172532

Article Similarity: 0.2964330740410276
सचिव कोइराला सरुवा अर्याल कडाइ मन्त्रिपरिषद गरियो,’ मन्त्रालय स्वास्थ्य कार्यालय खोज् यादव राम्रो तानेर प्रधानमन्त्री ठाउँ लक्ष्मण सम्हाल् नपुग् पूर्वाधार https://www.ratopati.com/story/131948

Article Similarity: 0.29576666096822646
खान् आर्मी ट्याक्सी सेना मेरो धेरै पुस्तक फिल्म थिएँ राष्ट्रपति हेर् लाग् अन्तर्वार्ता सिपाही एकपटक दुःख अवकाश भनेर माओवा बेलु https://www.ratopati.com/story/174256

Article Similarity: 0.29574612271621153
तत्कालिन स्कूल विभाग नेता सहमति आयोग उपप्रमुख माओवा एमाल अनुशासन प्रस्तावित बैठक प्रमुख सचिवालय यसअघिनै छलफल दुवै आईतबार पोख्रेल वालुवाटार https://www.ratopati.com/story/95331

Article Similarity: 0.2951530074485607
खर्च पुँजीगत मन्त्रालय, मन्त्रालय लक्ष्य प्रतिशत बजेट अर्ब आयोग, महालेखा रुपैंया वर्ष अवधि करोड मन्त्रालयगत सरकारी खर्ब आर्थिक विनियोजित आयोजना https://www.ratopati.com/story/114290

Article Similarity: 0.29482068001083034
नारा बहिर्गमन विश्वासपात्र कमिसन बाँस्कोटा दिन्न नौलो बास्कोटा बाहिरिन भिन्न अर्थपूर्ण टाँस लेनदेन बाहिरि मन्त्रिपरिषद्बाट बिहीवार बाहिरिए मन्त्रालय निर्वाचित प्रविधिमन्त्री https://www.lokaantar.com/story/101209

Article Similarity: 0.29462210114098786
शुल्क स्कुल नीजि सत्र विद्यालय शैक्षिक सरकार अभिभावक प्रस्ताव राख् बाटो निर्देशिका शिक्षक,कर्मचारी मात्र विद्यार्थीबाट शिक्षा,विज्ञान मन्त्रालय निर्देशि अनुरुप दिपक https://www.thahakhabar.com/news/106639

Article Similarity: 0.2944989928960986
प्रचण्ड अध्यक्ष शान्ति वरियता नेकपा दुबै समान निर्वाह पार्टी हैसियत तत्कालिन महासचिव नेपाल माओवा भूमि विद्रोही विवाद ल्याई लागिपर नेपालबीच https://www.ratopati.com/story/98028

Article Similarity: 0.2937818775724958
पुत्ला धनुषा क्रान्तिकारी जनगणतान्त्रिक प्रधामन्त्री माओवा मोर्चा नेकपा जनकपुर सेक्रेटरी संयुक्तरुप प्रम बिरोध वैद्य शीतल प्रधानमन्त्री चौधरी, मिथिला कर्ण किरण https://www.ratopati.com/story/105824

Article Similarity: 0.29305293507547064
समिति आदेश पारित पञ्चाङ्ग विसं प्राडा निर्णायक शाखाप्रमुख कार्यालय सञ्चालन २०६१ संस्कृति मन्त्रिपरिषद् मन्त्रिपरिषद्बाट मन्त्रालय स्थापना प्रकाशन माधव जोशी गौतम https://www.ratopati.com/story/164692

Article Similarity: 0.2926215430822735
तत्कालीन इञ्चार्ज इन्चार्ज माओवा जिल्ला टुंगो सह–इन्चार्ज नामावली एमाल टुंगाउ पार्टी भन्नेकुरा पुगि नजुटे विभाग बैठक सहइन्चार्ज टुंग सहमति सचिवालय https://www.ratopati.com/story/94581

Article Similarity: 0.29147949405715834
सुर्खेत सहकारी कृषि केन्द्र कार्यालय खोल् प्रस्ताव मन्त्रालय केन्द्र, व्यवस्था, रजिस्ट्रार भूमि, हुम्ला, भूमि डोल्पा, संरचना सल्यान विकास प्रदेश तालिम https://www.lokaantar.com/story/55183

Article Similarity: 0.2904295571273279
कार्यक्रम असोज विद्यालय आन्दोलन शिक्षक,कर्मचारी निजी संस्थागत भुक्तानी शिक्षक विरोध घोषणा मन्त्रालय अल्टिमेटम एकीकरण कोणसभा चाडबाड मन्त्रालय, युनियन समायोजन विकास https://www.thahakhabar.com/news/108172

Article Similarity: 0.28988683864633535
सचिव सरुवा मन्त्रालय कार्यालय मन्त्रीपरिषद् मन्त्रालयबाट महालेखा नियन्त्रक भूमिसुधार लोकसेवा श्रम आयोग वाणिज्य आपूर्ति अनुगमन शिक्षा ढकाल बेलवासे मोहनकृष्ण वैकुण्ठ https://www.ratopati.com/story/97645

Article Similarity: 0.28956294288280127
विद्यालय निजी भर्ना अभियान कोरोना मन्त्रालय शुल्क शिक्षा सुरु नयाँ जारी संक्रमण प्रष्ट शैक्षिक सामाजिक सामुदायिक विद्यार् दूरी कसरी निर्णय https://www.ratopati.com/story/132404

Article Similarity: 0.2889003659617348
बालुवाटार खाली सचिवालय विषय बैठक पाण्डे मन्त्री पठाउ सहमित मन्त्रालय सवैधानिक शुरु छलफल पुनर्गठन, नियुक्ति, स्रोत अध्यक्षद्धय पाटी पार्टी अर्थमन्त्रालय https://www.ratopati.com/story/150055

Article Similarity: 0.2860370130502443
जनमोर्चा माओवा सरकार गुरुङ मुख्यमन्त्री सांसद समर्थन केन्द्र काँग्रेस समीकरण नेतृत्व समाजवा छलफल मन्त्री नयाँ गण्ड काँग्रेस, पार्टी जनता सहकार्य https://www.ratopati.com/story/175327

Article Similarity: 0.28508276433351976
पार्टी नेकपा माओवा फेरि तत्कालीन उठाए विस्तारित वैचारिक पेरिसडाँडा २०६५ सिद्धान्त स्थगन मुख्यालय विषय सिर्जना चर्चा पार्टीभित्र थियो, एकता प्रचण्ड https://www.ratopati.com/story/6040

Article Similarity: 0.2845493428034479
मोर्चा चौथो चुनाव जसपा हामी चाहिं माओवा मिल् केपी प्रचण्ड तालमेल झार् नम्बर राम्रो पार्टी बनाएर चुनावी घोषणा एउटा आगामी https://www.ratopati.com/story/175254

Article Similarity: 0.28402709633566825

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [69]:
pre.df.user_keywords.iloc[55]

['सांसद',
 'एसएसपी',
 'पेस्तोल',
 'नियन्त्रण',
 'प्रहरी',
 'पोखरेल',
 'बानेश्वर',
 'घटना',
 'दोषीउपर',
 'हतियारधारी',
 'वानेश्वर',
 'आक्रमणकारी',
 'कठघरा',
 'धम्क्या',
 'बृत्त',
 'भत्र्सना',
 'पक्राउ',
 'संसद',
 'अनुसन्धान',
 'फिल्ड']

In [34]:
def get_user_recommendation(user_keywords):
    keywords=" ".join(word for word in user_keywords)
    return get_similar_articles(keywords,pre)

In [35]:
get_user_recommendation(pre.df.user_keywords.iloc[108])

query: सांसद एसएसपी पेस्तोल नियन्त्रण प्रहरी पोखरेल बानेश्वर घटना दोषीउपर हतियारधारी वानेश्वर आक्रमणकारी कठघरा धम्क्या बृत्त भत्र्सना पक्राउ संसद अनुसन्धान फिल्ड
Articles with high cosine similarity are:
Article Similarity: 1.0000000000000002
सांसद एसएसपी पेस्तोल नियन्त्रण प्रहरी पोखरेल बानेश्वर घटना दोषीउपर हतियारधारी वानेश्वर आक्रमणकारी कठघरा धम्क्या बृत्त भत्र्सना पक्राउ संसद अनुसन्धान फिल्ड https://www.ratopati.com/story/55709

Article Similarity: 0.43074572502316016
थाइल्याण्ड विद्रोही आक्रमणकारी दक्षिणी स्थानीयबासी सैनिक क्षेत्र सङ्घर्ष सशस्त्र आक्रमण परिचालन सर्वसाधारण कानुन सक्रिय बौद्धमार्गी लुटेर तालिमप्राप्त प्रयुत प्रान्त कठघरा https://www.ratopati.com/story/105380

Article Similarity: 0.39124042536205655
हत्या प्रहरी अभियोग महिला नियन्त्रण पक्राउ वीरेन्द्र अभियुक्त पत्नी चौधरी प्रकृति वर्षीया हेर् देखिए घटनास्थल फेला नायब वर्षीय उपरीक्षक अनुसन्धान https://www.ratopati.com/story/131922

Article Similarity: 0.3378212664980179
आक्रमणकारी हत्या आक्रमण बासिन् दर्दनाक बृद्धबृद्धा गाउँले अन्धाधुन्ध प्रहरी बन्दुकधारी बालबालि स्थानीय गाउँ घटना मृत्यु उत्तरपश्चिमी विभत्स अधिकारी क्रुर छन्,” https://www.ratopati.com/story/118363

Article Similarity: 0.33614669128889707
एसिड आक्रमण सांसद दोषी घटना ध्यानाकर्षण बेटी मुस्कान खातुन कारवाही महतो कानुन सरकार भत्र्सना चाल्न जोगाउ कुमारी सुरक्षा गरिन् गर्न https://www.ratopati.com/story/99680

Article Similarity: 0.33034491989635567
ढोरपाटन पक्राउ वर्षीय अभियोग प्रहरी वर्षीया नगरपालिका–८ परियार घटनास्थल बलेवा नायब उपरीक्षक टोली अनुसन्धान आधार बागलुङ नियन्त्रण पाँच कार्यालय जिल्ला https://www.ratopati.com/story/173119

Article Similarity: 0.32617266250558147
आइपुग फ्रान्स प्रवेश चर्च हमला आक्रमणकारी प्रहरी वर्षीय नोट्रे चार्ली रेलबाट सिल्भा सीसीटिभी सिमोन इन्च हत्या महिनामात्र रेस्टुरेन्ट धारिलो आक्रमण https://www.ratopati.com/story/152859

Article Similarity: 0.32489563058854365
झापा हतियार हत्या अनुहार राकेश प्रहरी नगरपालिका– वर्षीय प्रहार घटनास्थल युवक चौधरी फेला नायब थापा प्रयोग अनुसन्धान टोली उपरीक्षक सूचना https://www.ratopati.com/story/151255

Article Similarity: 0.31457137285037695
आक्रमण केसी प्रशासकीय विज्ञप्ति नगरपालिका गोपाल अधिकृत निमित्त कारबाही आक्रमणकारी टाउका पिछा निका दोषीउपर धारिलो हतियार कार्य कामकाज गीता नभएसम्म https://www.thahakhabar.com/news/86714

Article Similarity: 0.2963933853948065
चर्च महिला आक्रमणकारी मेयर प्रहरी घटना फ्रान्स नोट्रे क्रिस्टियन फ्रेन्च हत्या छुरा मरिन मोहमद चक्कु आक्रमण, यसमध्ये शिक्षक पेरिस आतंकवा https://www.ratopati.com/story/152799

Article Similarity: 0.29201790602852085
वडाअध्यक्ष आक्रमण प्रहरी चौकी रुकुम मुसिकोट तिम्सिना आक्रमणकारी केसी हतियार फरार डीएसपी नगरपालिका–१३ नगरपालिका–१४ नेतृत्व लोकनाथ साँझ खाइरह भत्काउ खोजीकार्य https://www.ratopati.com/story/132804

Article Similarity: 0.28904281552598293
हिन्दू हत्या युवा समिति विश्व धर्म दोषी सुर्खेत एवम् मान् जङ्ग कठघरा उभ्याउन खसालेर मिलोमतो अन्तर्राष्ट्रिय धामी, नरोके भत्सर्ना भीरबाट https://www.ratopati.com/story/99125

Article Similarity: 0.28780549827199287
संसद काँग्रेस अधिवेशन बैठक विशेष बोलाउन लागि चौथाइ बोलाउ जनता जसपा तर्क हतार सांसद पार्टी संसदीय सभापति समाजवा संसद् तत्काल https://www.ratopati.com/story/154850

Article Similarity: 0.28724213218676214
धमाधम पक्राउ शक्ति शृंखला कानुनी उखान थाले निरन्तरता अपराध यस्ता सांसद अनुभूत नेताविरुद्ध कर्म जतिसु पुर्जी सोध्न एक्सन निर्वा्चित परिचित https://www.ratopati.com/story/103325

Article Similarity: 0.2825879779374855
दसैं भत्ता फिर्ता विष्ट गोकर्ण सांसद अनुपयुक्त उपनेता छु,’ सांसद् भोगिरह नलाग नेकपा आक्रान्त बापत कोराना कठिनाइ सुवास निर्णय नेम्वाङ https://www.ratopati.com/story/151873

Article Similarity: 0.28094865606041036
बर्दिबास बालिका आक्रोशित स्थानीय हत्या महोत्तरी प्रदर्शन चापागाईं नियन्त्रण प्रहरी नायव राखेर उपरीक्षक वर्षीया नदिइरह नगरपालि तनाव, दिनुपर्ने’ फासी बस्तीबाट https://www.ratopati.com/story/156053

Article Similarity: 0.28009277666348875
भागर किशोरी प्रहरी भट्ट मृतक अनुसन्धान घटना बैतडी गाउँ टोली चडेपानी हत्या फेला पीडा बलात्कार छोरी गुमाउँ छुट्टै उपरीक्षक शिवराज https://www.ratopati.com/story/166823

Article Similarity: 0.27900686450556816
किशोरी विवाह मौलाना सांसद उमेर वर्ष पाकिस्तान स्कूल अनुसन्धान प्रहरी पाकिस्तानी बलूचिस्तान सज्जाद इन्स्पेक्टर अनुसार रिपोर्ट प्रिभेन्सन नपुग एएनआई छात्रा https://www.ratopati.com/story/169158

Article Similarity: 0.27340943121303346
राष्ट्रियता गिरी बताइन् जातिय आक्रमण बंगलादेश संशोधन महिला नबिर्स संविधान सांसद सन्धिअनुसार १८१६ नाउँ भइराख नक्सा अस्वीकृत सेल्फ संसद सन्धि https://www.ratopati.com/story/134270

Article Similarity: 0.27297004657309093
पक्राउ प्रहरी धनुषा महतो वर्षीय हतियार गाउँपालि गाउँ निरीक्षक मंगलबार जनाए आधार सोही कार्यालय सूचना सहित अनुसन्धान टोली नियन्त्रण भइरह https://www.ratopati.com/story/113832

Article Similarity: 0.27227247059001963
अर्जुन विभत्स हत्या श्रीमती श्रीमान धरान खोला प्रहरी मनमुटाव घरायसी ढुङ्गा साँझ अनुसन्धानबाट न्यौपा पक्राउ डीएसपी प्रारम्भिक विवाद बुधबार वर्षीया https://www.ratopati.com/story/104708

Article Similarity: 0.27161607648838343
निर्वाचन विकास प्रणाली शासकीय जनाउँ तामाङ स्वरुप प्रत्यक्ष आह्वान परिवर्तन भ्रष्टाचार कार्यकारी खर्च सांसद आकांक्षा खर्चभन् जनताप्रति महंगो मौलाउँ बृहत् https://www.lokaantar.com/story/101600

Article Similarity: 0.2699849573249411
सांसद महिला बलात्कार बच्चन महिलाविरुद्ध बलात्कारी निम्ति घटना सामूहिक हत्या निन् न्याय भारत बोल् वर्षीया चिकित्सक हिंसा भारतीय कारबाही संसद https://www.ratopati.com/story/108614

Article Similarity: 0.2686496177403129
प्रदेश तथ्याङ्क सांसद जना, डेंगु मन्त्री यादव महाशाखा ज्वरो संक्रमण साउन जिल्ला बुधबार उपप्रधानमन्त्री प्रतिनिधिसभा नियन्त्रण संसद गतेसम्म असोज मृत्यु https://www.ratopati.com/story/100909

Article Similarity: 0.26650563497994273
गुल्मी बुढा बलात्कार युवक बालिका गाउँपालि पक्राउ आरोप प्रहरी बालि प्राप्त घटनाबारे भनेर वर्षीया हुन्। भइरह वर्षीय अनुसन्धान कार्यालय अखिल https://www.lokaantar.com/story/101706

Article Similarity: 0.2646323857036239
बैङ्क पिटर पानस प्रहरी तामाङ, रेमिट पक्राउ एसएसपी निकाल महाशाखा ह्याक खुल्न कृषि थापा ह्याकर खाता विकास ट्रान्सफर पैसा अनुसन्धानबाट https://www.ratopati.com/story/101583

Article Similarity: 0.2629155615100862
वायुसेना आक्रमणकारी अमेरिका गोलीबारी भारतीय जहाज घटना आक्रमण मार्शल आधुनिकरण महासागर अन्धाधुन्ध आक्रमण, वाहन बन्दुक अधिकारी तैनाथ मृत्यु दौरान लिइरह https://www.ratopati.com/story/108839

Article Similarity: 0.2616111701743064
बिवाह धमेन्द्र बिवाद बोनी दुबै डिबोर्स बिवाहित विवाह इस्लाम नितु प्रेम श्रीदेवी उनीहरुबीच अमृता धर्म सम्बन्ध कारण परिवर्तन विवाद रिलेसन https://www.ratopati.com/story/116499

Article Similarity: 0.26091818652438264
हत्या कार्की चौधरी सिसिक्यामेरा घरेलु घटना मुना प्रहरी अर्जुन फुटेज कार् अनुसन्धान कामदार श्रीमती देखिन् टाउको कारण सोमबार वर्षीय एसपी https://www.lokaantar.com/story/100413

Article Similarity: 0.26080067641666826
कामदार छोरा हत्या घटना आत्महत्या मिनेट कार्की लगाएर वर्षीय प्रहरी जारी उक्त अनुसन्धान भित्र व्यवहार उपरीक्षक गर्छन्। बताउँछन्। विदेश खाना https://www.thahakhabar.com/news/91106

Article Similarity: 0.2600001119439167
प्रेमि युवक हत्या रौतहट खड्का थिचेर घाँटी प्रहरी अनुसन्धानबाट अनुसन्धान उपरीक्षक गौरबाट बाँधेर राति बताए। नगरपालिका-८ किनार भेट्न मोहम्मद स्थानीय https://www.thahakhabar.com/news/91030

Article Similarity: 0.2568538269129802
हत्या धनुषा पक्राउ विषय विवाद कुमार अनिल प्रहरी सोमबार शनिबार गाउँपालि वर्षीया नम्बर परिवार उपरीक्षक स्थित वर्षीय जनकपुर कर्तव्य घाँटी https://www.ratopati.com/story/116658

Article Similarity: 0.2564273397176492
विघटन संसद जनादेश नयाँ संसद् अनुशासित दावी जनताप्रति समर्पित शंकर जनप्रतिनिधि उपस्थिति हत्या खोजी गर्नुपर्ना असंवैधानिक, पोखरेल बर्षे पुर्नस्थापना केपी https://www.ratopati.com/story/163883

Article Similarity: 0.2557673156292251
श्रीमती हत्या पक्राउ अभियोग रामबहादुर प्रहरी जंगल परियार सम्बन्ध आफ्नै पाल्पा वर्षीया सोही अनुसन्धान गरिरह वर्षीय कारण जानकारी अगाडि अघिल्लो https://www.ratopati.com/story/167324

Article Similarity: 0.2546658888582319
प्रहरी डिएसपी पोखरा हमाल पक्राउ अनुसन्धान नियन्त्रण मोबाइल साथबाट बरामद वर्षिय साढे दिउँसो सुवास अन्तर्गत प्रवक्ता ल्या लिएर कास्की अनुसार https://www.ratopati.com/story/151631

Article Similarity: 0.2545859883413744
संसद शब्द सभामुख रेकर्डबाट हटाउन प्रधानमन्त्री सांसद कुण्ठा माफी कांग्रेस प्रतिपक्षी अर्थ माग् काँग्रेस मर्या निर्देशन विरोध कर्कश सुषुप्त भत्सर्ना https://www.ratopati.com/story/87056

Article Similarity: 0.25422143819214166
सांसद प्रधानमन्त्री संसद भ्रष्टाचार कोरिया हेलिकप्टर महिला सरकार थापा बास्कोटा प्रतिवेदन राजीना नेपाली दिक्षित दुर्घटना आयोग आश्वस्त अन्तिम मृत्यु गिरी https://www.ratopati.com/story/119492

Article Similarity: 0.25302221161810273
पक्राउ सहित प्रहरी वर्षीय जाँच हतियार बाँक सम्बन्ध फेला स्थित आधार लाग् पाँच सूचना सोही विशेष अनुसन्धान गरिरह उक्त क्रम https://www.ratopati.com/story/150164

Article Similarity: 0.25269517476307735
पक्राउ अवज्ञा मेयर हिँड् प्रहरी ड्रोन फ्रान्स आदेश लकडाउन नागरिक समेत आवागमन रुपैयाँ विशेषगरी सुना अपनाउँ आक्रामक क्रिस्चियन जरिवाना धमाधम https://www.lokaantar.com/story/103713

Article Similarity: 0.2521200192602748
विघटन संविधान प्रतिनिधि प्रम अविश्वास प्रधान व्यवस्था संसद प्रस्ताव मन्त्री प्रधानमन्त्री संसदीय बाधा गर्न बेलायत हाम्रो २०४७ मिल्दैन राजा जापान https://www.ratopati.com/story/161039

Article Similarity: 0.2515469295241001
ट्याक्सी हुँ’ राखेर अपहरण पैसा व्यक्ति महाशाखा थापा असुल् पुर्या बालाजु म्यासेज प्रहरी गिरोह हेर् क्रम घटनाबारे एसएसपी स्थानीय अन्य https://www.ratopati.com/story/154526

Article Similarity: 0.2504126024181385
बानियाँ सांसद ढुंगेल संसद विधेयक पुस्तक विनियोजन सभामुख टेबुल बजेट किताब आक्रोशित मन्त्री बागमती श्रेष्ठ भनेर प्रतिपक्ष बैठक योजना कांग्रेस https://www.thahakhabar.com/news/100789

Article Similarity: 0.2499806401755744
प्रहरी आक्रमणकारी उपचार अस्पताल आत्महत्या पिछा घटनास्थल विरामी क्षेत्रीय गोली क्रम आक्रमण: प्राग कम्ती उक्त सम्लग्नता मृत्यु एक्कासी वार्ड परिचय https://www.ratopati.com/story/109488

Article Similarity: 0.2499069926143633
भेला संविधान विघटन खनाल बताए प्रधानमन्त्री संसद चुल्हो वरिष्ठ कुनैपनि कम्युनिष्ट आक्रमण ग्यास नजिर नेता अस्थिरता मान् चुनाव भड्काउ विरोधी https://www.ratopati.com/story/161229

Article Similarity: 0.2495239927769679
प्रहरी गिलगित गोली अज्ञात आक्रमणकारी गाडी उत्तरी बाल्टिस्तान केटाकेटी पाकिस्तान कम्ती मिर्जा व्यक्ति गरिरह क्षेत्रस्थित भ्यान घाइते आक्रमण यात्रुवाहक समूह https://www.ratopati.com/story/173174

Article Similarity: 0.24872343228484098
अधिकारी प्रहरी कास्की बलात्कार सशस्त्र एसएसपी हिरासत पक्राउ म्याद उपरीक्षक प्रकृति, दंगा जिल्ला शिक्षालय राखिसक अनुसन्धान दोस्रोपटक कन्ट्रोल आरोप अवलोकन https://www.ratopati.com/story/139707

Article Similarity: 0.24824672509696988
भत्ता सांसद रुपैयाँ करोड वर्ष खर्च हजार बुझ् आर्थिक संसद् सचिवालय लागि २०७५÷७६ धेरै स्रोतबाट लाखभन् तथ्यांकअनुसार खाता चालु सुवे https://www.ratopati.com/story/101850

Article Similarity: 0.2475677529555514
प्रहरी स्थानीय जर्मनी गोली कम्ती आक्रमण गरेर कालो बजेतिर हेलिकप्टर आक्रमणकारी गाडी पहिचान समयअनुसार सशस्त्र घटनास्थल खोजी गइरह केही मृत्यु https://www.lokaantar.com/story/101146

Article Similarity: 0.24753723553138804
पोखरी युवती फेला प्रहरी कपडा घुम्न जनकपुरधाम देखे अवस्था निस्क धनुषा थिइन् वर्षीया घटना बजार मानिस अनुसन्धान बिहान स्थानीय विषय https://www.lokaantar.com/story/103046

Article Similarity: 0.24716723412869515
अर्घाखाँची सन्धीखर्क नम्वर रुपन्देही मिटर बुटवल दुर्घटना भक्तबहादुर दुर्गादेवी परिवार बिनोद सैनामैना दुर्घटना, अनियन्त्रित मृत्यु करीब विष्ट अगाडी डिएसपी प्रहरी https://www.ratopati.com/story/105342

Article Similarity: 0.246974603027118
मुद् प्रदेश वर्षीया प्रहरी लकडाउन घटना हत्या उपरिक्षक दर्ता दलित मानिस अवधि उद्योग वरिष्ठ महिला कार्यालय अर्थात घरेलु चैत्र दुरी https://www.ratopati.com/story/132455

Article Similarity: 0.246352921809256
आणविक परीक्षण अमेरिका आरोप सन्धि रिपोर्ट प्रमाणित पुरा छन्, स्थल दावी सांसद हतियार अप्ना जिरो नियन्त्रण, आन्तारिक प्रतिज्ञा इन्कार स्ट्रीट https://www.ratopati.com/story/126489

Article Similarity: 0.24594231204320713
केटी प्राइस लैजान पूर्व कपडा घरबाट पुलिस फिर्ता प्रेमी दिइन् अनुसार मोल्न धम्की, धम्की आक्रोशित मार् चाहँदैनन् खतरा सोधे ज्यान https://www.ratopati.com/story/109271

Article Similarity: 0.2453388065676307
सांसद अमेरि प्रतिनिधि अनुभव संसद खर्च एनजीओ सिनेट कर्मचारी हामी त्यस्तै पैसा गैरसरकारी हुँदैन छौँ, संस्था संसदीय माथिल्लो सुझाव नेपाल https://www.ratopati.com/story/106063

Article Similarity: 0.2453388065676307
सांसद अमेरि प्रतिनिधि अनुभव संसद खर्च एनजीओ सिनेट कर्मचारी हामी त्यस्तै पैसा गैरसरकारी हुँदैन छौँ, संस्था संसदीय माथिल्लो सुझाव नेपाल https://www.ratopati.com/story/106063/2019/11/12/us-ngo?fbclid=iwar29hz_c7j4cw1calfhnj4obdsp7keok0kb4yfdqoe1i_lvz-mxwyzrqocy](https://www.ratopati.com/story/106063

Article Similarity: 0.24515869165683393
पोखरेल छानविन प्रतिशोध विचारधारा हत्याकाण्ड लागू आपराधिक विषय घटना हिंसा बुझ् जुनसु पारे। हुनसक् ईश्वर सुशासन बताए। भ्रष्टाचार पक्राउ कुनै https://www.thahakhabar.com/news/82410

Article Similarity: 0.24454772928687807
जीवन श्रीमती प्रहरी थिमि तामाङ्ग श्रीमान जिवन युवती प्रहरीसँग कोठा वृत्त उपरिक्षक नायव वर्ष छलफल प्रेम लागेर सिन्धुपाल्चोक बाहिर अनुसन्धान https://www.ratopati.com/story/95498

Article Similarity: 0.24416699374791614
आक्रमण अनुहार लन्डन मेरो अवस्था चिनियाँ अक्सफोर्ड जोडेर फेसबूक फोटो बजेतिर आक्रमणकारी लेखे स्ट्रीट पूर्वी फागुन पूर्व मानिस पोस्ट बताए https://www.lokaantar.com/story/102223

Article Similarity: 0.24196632032932341
अधिवेशन संसद विशेष सांसद हिउँदे सरकार संसदीय जनता क्षेत्र, अन्त्य समस्या, समिति बैठक छलफल बोलाउन बेला सचेतक बोलाउ काँग्रेस भने– https://www.ratopati.com/story/155798

Article Similarity: 0.24151786089070534
पक्राउ खजुरा प्रहरी राना बाँक बाँके वर्षीय काटिरह गाउँपालिका–८ उपरीक्षक अब्दुल ओमबहादुर खेतबारी गाउँपालिकास्थित किलो परिणाम बारे घटना अनुसन्धान टोली https://www.ratopati.com/story/150982

Article Similarity: 0.24083233401308035
राधे पक्राउ प्रहरी गुण्डा नाइके भण्डारी गजुरी राधाकृष्ण उपाध्यक्षसमेत गुण्डागर् हतियारसहित धम्क्या स्थानीयबासी आक्रमणबाट गाउँपालिका–२ तरुण धादिङ हतियार सूची देखाउँ https://www.ratopati.com/story/89826

Article Similarity: 0.24056836143538365
सुस्मिता हत्या थापा ससुरा अनुसन्धान नन्द मृतक मकवानपुर वीभत्स प्रहरी श्रीमान घटनाबारे स्रोत भइरह दुर्घटना अवस्था पत्‍नी इन्द्रबहादुर ज्यानसम्बन्धी बिहिबार https://www.thahakhabar.com/news/100902

Article Similarity: 0.24051371582009948
छोरी हत्या बाबु घिमिरे अर्घाखाँची वर्षीया बस्नेत ठाडा सृष्टि माइत घटना प्रहरी इन्सपेक्टर घिमिर घरायसी वर्षीय बाबुराम सन्तोष श्रीमती बुटवल https://www.ratopati.com/story/165214

Article Similarity: 0.24002387011071033
त्रिपाठी स्वतन्त्र सत्ता नेकपा सांसद सिंहदरबारस्थित हृदयेश पक्ष सूर्य कोठा दिनेश छुट्टै चुनाव संसदीय प्रश्न संसद् लाग् कान्तिपुर कार्यालय दैनिक https://www.ratopati.com/story/98661

Article Similarity: 0.23985734238777942
फरार संक्रमित आईसोलेसन झ्याल तोडेर नायब धनुषा कार्की उपरीक्षक अस्पताल व्यक्ति कोरोना विहानै महोत्तरी, वर्षिय सर्लाही, भाग् रामेश्वर मानसिक सन्तुलन https://www.ratopati.com/story/131369

Article Similarity: 0.23890464987752014
सोनी दीपा हत्या आरोपी दीपक तारेख आदेश अदालत प्रहरी साधारण पुर्पक्ष मुद् परिवार सर्वोच्च अनुसन्धान विवाह नेपालगञ्ज भारत बाँके थुना https://www.ratopati.com/story/94288

Article Similarity: 0.23836517370326574
अर्घाखाँची बुटवल दुर्घटना सन्धिखर्क वर्षीय मृत्यु भट्टराई, ठाँउ भिरबाट मृतक सनाखत वर्षीया उपचार कपिलवस्तु घाइते अनियन्त्रीत पुरी, प्रशान्त प्रारम्भीक बाँसगढी https://www.thahakhabar.com/news/84923

Article Similarity: 0.23825703643227747
कुकुर अधिकारकर्मी छोरा तीनकु कान्छो पोष्ट मंसिर टोक् फोटो हतार–हतार जाहेरी घटनाबारे सोचेर धम्क्या वृत्त काठमाडौँ पुगे अस्पताल सम्पर्क महानगरीय https://www.ratopati.com/story/110240

Article Similarity: 0.2377206062486723
वर्षीय झापा नगरपालि त्रास प्रवेश श्रेष्ठ नायव क्वारेन्टाइन उपरीक्षक रोजगारी प्रहरी कैलाली भारतबाट गाउँपालि नियन्त्रण उनकाअनुसार मेचीनगर सुजन सुमन युवराज https://www.thahakhabar.com/news/94991

Article Similarity: 0.2370826123428324
प्रहरी आक्रमण यादव चोटपटक प्रहरीटोली मौलापुर स्थानिय राकेश एकजना गाँउले ढुंगामुढा आक्रमणकारी संक्रमित लाठीचार्ज रौतहट गाँउ राउण्ड आक्रमणबाट यादव, महतो https://www.ratopati.com/story/132163

Article Similarity: 0.23678183720250515
प्रहरी अनुसन्धान हत्या भट्ट किशोर पक्राउ दोषी विद्यालयबाट मङ्गलबार स्थानीयवासी एसएसपी पत्ता बैतडी दिनेश बलात्कार सुवे राति लगाएर सहित टोली https://www.thahakhabar.com/news/118556

Article Similarity: 0.2366744563472751
नियुक्ति सर्वोच्च संसद छलेर शुन्य संवैधानिक शून्य सुनुवाइ फैसला कर्ण विघटन निकाय प्रतिनिधि संसदीय अधिवक्ता थापा अदालत वरिष्ठ स्वतः राजीना https://www.ratopati.com/story/169244

Article Similarity: 0.23641271782703843
थापा सांसद् खर्च सामाजिक सुविधा जनता आरोप प्रदेश सांसद कांग्रेस कार्य लगाए सम्पूर्ण हैसियत कास् सरकार नेकपा क्षेत्र राजनीति सेवा https://www.ratopati.com/story/165352

Article Similarity: 0.23632271275228137
आक्रमणकारी सुरक्षाकर्मी प्रहरी सशस्त्र समूह खोजी बाल्टिस्तान सञ्चारमाध्यम क्षेत्र गिलगित पाकिस्तान घटनास्थलबाट पार्दासम्म झडप, स्थानीय घेरा घटना आपराधिक पु¥या बिहानै https://www.ratopati.com/story/140494

Article Similarity: 0.23628533156615877
प्रहरी डडेल्धुरा विद्यार् बलात्कार अनुसन्धान बैतडी उपरीक्षक न्याय घटना कार्यालय प्रदर्शन जिल्ला किशोरी दोषी बुझा भट्ट कारबाही वरिष्ठ हुन्। छन्। https://www.thahakhabar.com/news/118177

Article Similarity: 0.2358742990450356
निकास अदालत संसद थापा जान् संवैधानिक फैसला संसदीय शम्भु मार्न छनौट राजनैतिक स्थायित्व साक्षात्कार अधिकार संविधान राजीना सुशासन आवाज सुनाए https://www.ratopati.com/story/169304

Article Similarity: 0.23550400310794906
संजय आत्महत्या बनावटी छोरी हत्या कुमारी पर्सा खुल्न प्रहरी सोनार घाटी वर्षीया वीरगंज नाटक पक्राउ अनुसन्धान नारायणी पारी अनुसन्धानबाट क्रम https://www.ratopati.com/story/126913

Article Similarity: 0.23519842302609592
दसैं पाठक संसद खाता भत्ता सांसद सूर्य सचिवालय संघीय महामारीकाबीच दाखिला घोषणा कट्टा आइतवार पारिश्रमिक आफ्नो आलोचना पत्र फिर्ता अनुरोध https://www.ratopati.com/story/151757

Article Similarity: 0.23518712991199586
छोरी बुवा पिता अनुसन्धान छोरा अनुसन्धाता निष्कर्ष बाँच् सन्तान खासै प्रकाशित खुसी तथ्य वर्षसम्म अनुसार संख्या भावना दुबै धेरै अध्ययन https://www.ratopati.com/story/148595

Article Similarity: 0.2347660688196651
आयोग पीडित द्वन्द्व उजुरी स्रोत संक्रमणकालीन कानुन टुङ्गो न्याय मुकाम बेपत्ता निर्णय संशोधन अदालत पदाधिकारी किसिम अनुसार वर्ष परिपूरण पुराउन https://www.ratopati.com/story/155598

Article Similarity: 0.23431059883545077
भैँसी करणी हत्या लाठी देवीराम युवा प्रहरी वृद्ध भण्डारी तिरा बेसी चन्द्रकोट देउराली ढुङ्गा वर्षीय वर्ष स्रोत खड्का अनुसन्धान एसपी https://www.ratopati.com/story/111283

Article Similarity: 0.2341781146389664
कर्मचारी भत्ता, सहुलियतपूर्ण खतिवडा बताए भत्ता लागि सुविधा बजेट भैपरी रोकथाम सारि सेमिनार, खर्च इन्धन, गरिने, फर्निचर, मर्मत, सदाचार वर्ष https://www.ratopati.com/story/132025

Article Similarity: 0.2340980108120361
गौतम पोखरेल राष्ट्रियसभा व्यवस्थापन नेता संसद् जितेर विवाद संसदीय निर्वाचन आन्तरिक प्राध्यापक द्वन्द्व मन्त्री दाहाल चुनौती बनाउँ ईश्वर रामबहादुर शीर्ष https://www.ratopati.com/story/147375

Article Similarity: 0.23381922102519087
भागर बैतडी भट्ट प्रहरी घटना संघर्ष दोषी बलात्कार पत्ता हत्यारा हत्या अनुसन्धान नायब छौँ, सामूहिक उपरीक्षक प्रयोगशाला आफन्त नहुँ नजिक https://www.ratopati.com/story/167703

Article Similarity: 0.232970196588087
डेङ्गु स्वास्थ्यमन्त्री सांसद रुलिङ सरकार सभामुख महामारी सुतेर संकटकाल आतंक सत्तापक्ष प्रकोप विरुद्ध देशभरी तत्काल संसद नियन्त्रण बोलाएर गरेर बोल्दैन https://www.ratopati.com/story/100170

Article Similarity: 0.23290218816164887
प्रहरी काठमाडौँ बैङ्क एसएसपी अपराध प्रकरण ज्ञवाली पूर्वराजदूत दसैं अनुसन्धान सुरक्षागार्ड ह्याकिङ हत्या एटीएम सुरक्षा महाशाखा नपाउँ सुल्झा चोरी कान्छाराम https://www.ratopati.com/story/102091

Article Similarity: 0.23282508875062172
समिति निर्देशन संसदीय सभापति सरकार संसद पालना मन्त्री अनुकूल लेखा उत्तरदायी विडारी सांसद तिमी अन्तरगत अन्र्तगत तर्क पुगिहाल् प्रधानमन्त्री कतिपय https://www.ratopati.com/story/98972

Article Similarity: 0.23202588980211716
भर्त्सना विद्यार् दिल्ली आक्रमण घटना घाइते पुलिस क्याम्पस भएलगत्तै आक्रमणकारी हिंसा ट्वीट जयशंकर एजेन्सी जवाहरलाल एएनआई गान्धी दिल्लीस्थित अमित समाचार https://www.ratopati.com/story/112653

Article Similarity: 0.23180654730287226

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

 https://www.ratopati.com/story/161404

Article Similarity: 0.03566287197799298
पर्यटन सङ्घ पोखरा अभियान’ पत्रकार चलायमान सुस्ता अभियान कार्यक्रम होटल शुरु आन्तरिक अन्र्तगत आयोजक जगाउ पश्चिमाञ्चल व्यवसायी, समेट वीरगञ्ज शुरुआत https://www.ratopati.com/story/158188

Article Similarity: 0.03566165460160765
दम्पती फेदीखोला नेगेटिभ संक्रमित युवती दिए। कोरोना परीक्षण क्वारेन्टाइन स्वाब रिपोर्ट कुरुम्वाङ गाउँपालिका कतारबाट टेकु कतार घनश्याम ज्वरो रामबहादुर सुवे https://www.lokaantar.com/story/104288

Article Similarity: 0.03566150353891642
कोरोना गण्ड सङ्क्रमित प्रदेश हजार सङ्क्रमण डा.विनोदविन्दु एवम् गण्डकी निर्देशनालय आइसोलेसन कास् शर्मा निर्देशक रोकथाम पुष्टि हालसम्म प्रवक्ता सङ्ख्या तयारी https://www.ratopati.com/story/151743

Article Similarity: 0.03566149281231759
महान्यायाधिवक्ता बडाल खरेल पदभार बिदाइ ग्रहण नियुक्त पालना कानून राष्ट्रपति पूर्व शपथग्रहण गोपनीयता व्यवस्थाअनुसार संविधान, संविधानअनुसार अवसर अगाडि कार्यालय सोही https://www.ratopati.com/story/172654

Article Similarity: 0.03565780602597881
बैठक क्याबिनेट एकाएक औपचारिकता बोला प्रशासनिक मन्त्रिपरिषद् उहाँ प्रस्ताव मन्त्री हुनुभए दैनिक पर्नुभ जगजाहेर बैठकलगत्तै गर्नुबाहेक खोजिए बोलेनन् तर्साउन ल्याउ https://www.ratopati.com/story/155298

Article Similarity: 0.0356571457129748
हिसिला ठक्कर स्कुटर मोटरसाइकल दुर्घटना सवार समाजवा पार्टी भर्ना ग्वार्को खुलाउन तस्वीर स्वास्थ्यलाभ नेतृ काठमाडौँ– बाहिरी अस्पताल पत्नी फेसबुक बाबुराम https://www.ratopati.com/story/99780

Article Similarity: 0.035654290738318786
टमटा पक्राउ पत्रअनुसार मलेसिया बौद्ध ललितपुर प्रहरी परिषद् उजुरी महानगरी सिंह नवौँ होटेल एनआरएन महिला बुझाइसक गैरआवासीय बुझाउन काठमाडौँ– सदस्य https://www.ratopati.com/story/103515

Article Similarity: 0.035652872968456914
आरोपपत्र दायर उपदफा अदालत मण्डल जनकपुरधाम सहयोगी २०५९ विशेष कार्यालय निवारण भ्रष्टाचार अख्तियार वडाध्यक्ष बर्दिवासबाट काठमडौं प्रमाणसहित घुसबापत मागदाबी हजार https://www.ratopati.com/story/151362

Article Similarity: 0.03564303597980644
भूभाग पश्चिमी मध्य पूर्वी हिमाली स्थान बदली सम्भावना पहाडी हिमपात उच्च वर्षा मध्यम सामान्य हल्का आंशिक थोरै केही महाशाखा मंगलबार https://www.lokaantar.com/story/99093

Article Similarity: 0.035634247511496936
शरीर जागिरबाट अस्पताल भारती कर्मचारी निकाल बयलपाटा छर्केर गुमे आफ्नै कोहलपुर सरसफाइ अछाम समयअघि जागिर हेलिकप्टर तनाव दीपक डिएसपी प्रहरी https://www.ratopati.com/story/133536

Article Similarity: 0.03563386680646394
टिभी दुर्घटना ट्रक सिंह डिसुजा मृत्यु इन्डियाज कलर्स ठोक्क उर्फ निभाएर ड्राइभर टेलिश्रृङ्खला बेस्ट दिउँसो सोनी गम्भीर गरिरह छोडेर बुवा https://www.ratopati.com/story/94375

Article Similarity: 0.03563292243985006
धुर्मुस फाउण्डेसन रंगशाला महानगर सुन्तली भरतपुर करोड निर्माण दाहाल रुपैयाँ सहयोग प्रशासकीय हस्तान्तरण प्रमुख बढाउन महानगरबाट सहयोगार्थ अधिकृत महायज्ञ सिताराम https://www.ratopati.com/story/165360

Article Similarity: 0.03563283704025208
बसपार्क कुँवर टिकट यात्रु समेत सवारी सञ्चालन केही नयाँ भाडा व्यवस्थित व्यवस्था जाँच साधन सहकार्य घण्टा छैनन् करीब संस्था ध्यान https://www.lokaantar.com/story/76523

Article Similarity: 0.03563018539590582
दृश्यावलोकन स्तम्भ निर्माण पर्यटक ठाउँ डाँडा विन्दु भण्डारी वडाध्यक्ष दृश्य मन्दिर आन्तरिक गाउँपालिका राना वर्ष उचाइ सम्भावना बताए स्थानीयवासी जानकारी https://www.ratopati.com/story/155385

Article Similarity: 0.03562327540577955
तरकारी मूल्य अचाक्ली होलसेल मूल्यवृद्धि बढेर महँगो वर्षा प्रतिशत वृद्धि बजार खुर्सानी रुपैँया नजिकिए रुपैयाँ व्यावसायी विनय प्रतिकेजी अस्वाभाविक कालीमाटी https://www.ratopati.com/story/101849

Article Similarity: 0.03562091364679728
पक्राउ सिमावर्ती जनकपुर उप्रेती किलो नम्बर एकजना बरामद सशस्त्र अबैधरुप चाँदीसहित क्षेत्रतर्फ प्लास्टिक जनकपुरबाट भरतकुमार भारततर्फ जनकपुर– मोटरसाईकल राजेश बुझाउ https://www.ratopati.com/story/101808

Article Similarity: 0.035617201045330796
आँधी वर्षा भिक्टोरिया वेल्स न्यू साउथ दिउँसै धुलो आइतबार प्रतिघण्टा डढेलो मौसम आपतकालीन अष्ट्रेलिया देख्न किलोमिटर पूर्वी लिसा उत्तर–पूर्व विभाग https://www.ratopati.com/story/114683

Article Similarity: 0.03561554914586776
महाधिवेशन कांग्रेस महामन्त्री केही परिमार्जन नेता कार्यतालि विषय आइरह मिति सभापति तयारी वरिष्ठ नबोली पदाधिकारीसहित शुभेच्छुक पूर्णबहादुर पौडेल ब्याक विवाद https://www.ratopati.com/story/154501

Article Similarity: 0.03561162732298354
प्रधानमन्त्री प्रचण्ड पार्टी अध्यक्ष फुट् उहाँ अर्को भनेर कुरा दुवै हामी हटाउ कमजोरी स्थायी स्टेप केके अध्यादेश समिति केपी पुरानै https://www.ratopati.com/story/154262

Article Similarity: 0.03560989212821248
कार्यदल नेम्वाङ देवकोटा छलफल सोमवार नेता समसामयीक बैठक नेपाल संविधान कोटेश्वर संशोधन छैन,’ सहमत बिहान कुरा विषय जनाए मूर्तरूप सकिँदैन,’ https://www.lokaantar.com/story/101516

Article Similarity: 0.03560692957747937
ठेक् कम्पनी निर्माण सम्झौता नयाँ प्रक्रियाबाट बनाउन विभाग बिजुलीबजारस्थित जमानत तोडे फिर्ता त्रुटि प्रविधि वर्ष २०७१ शहरी आयोजना प्राविधिक मूल्य https://www.ratopati.com/story/154167

Article Similarity: 0.035599393842716744
महानगर सहकारी साधारणसभा मसान्तभित्र निर्देशन प्रतिवेदन साधारण महानगरपालि आधारभूत निर्वाचन समिति अनुरुप कानुन, परिपालन मर्यादित सक्न आग्रह सदस्य तालिका सम्पन्न https://www.ratopati.com/story/153978

Article Similarity: 0.035598745407637536
डेंगु जिल्ला सङ्क्रमण लामखुट्टे देवकोटा अस्पताल कास्की ढाक् उच्च पोखरा बागलुङ वरपर तयार अनुसार लगाउ जनचेतना लामखुट्ट ठाउँ छौँ। भनाई https://www.thahakhabar.com/news/78792

Article Similarity: 0.03559278281296373
हजार देशभर गौतम शुक्रबार रहेकाे संक्रमित प्रवक्ता प्राडा यसबारे विगत मिडिया बताए। संक्रमित, नेपाल जागेश्वर छन्। फेरि संख्या ललितपुर उपत्यका https://www.thahakhabar.com/news/105886

Article Similarity: 0.03558855631092687
हजार संक्रमित संख्या भारत मृत्यु कोरोना त्यसैगरी राज्य केन्द्रीय प्रभावित घण्टा मन्त्रालय संक्रमणमुक्त तमिलनाडु भइसक भाइरस नाघ् कल्याण अत्यन्त एकैदिन https://www.ratopati.com/story/138950

Article Similarity: 0.03558764293461999
फलोअर्स मिलियन इन्स्टाग्राम विराट लिस्ट चोपडा प्रियं कोहली लिन् अमेरि भारतीय पोस्ट करोड स्पोन्सर स्थान रुपियाँ शुरुवात कमाउँ एकमात्र हप्ता https://www.ratopati.com/story/118930

Article Similarity: 0.03557810466336244
संस्था महिला बिहे सामाजिक संचालन गुरुङ भइन् प्रदान जन्म सभापति जीवन समाजसेवा कार्य पुरस्कार गरिन् अध्यक्ष चौथो संगठन पोखरा कुराकानी https://www.lokaantar.com/story/103132

Article Similarity: 0.03557698031423348
असिना चट्याङ्ग, पश्विमी मेघगर्जन, बदली आंशिक भू–भाग पूर्वानुमान थोरै वर्षा हावाहुरी स्थान सम्भावना वायु मध्य मौसम देशभर प्रभाव महाशाखा सहित https://www.ratopati.com/story/126241

Article Similarity: 0.0355658660541547
त्रिपाठी नियुक्ति सिफारिस अधिवक्ता सुनुवाइ संवैधानिक अध्यादेश पदाधिकारी असंवैधानिक वरिष्ठ परिषद् नगराउन समिति पत्र नलाग् आयोग दिनेश परिषद टुङ्गो अर्याल https://www.ratopati.com/story/166313

Article Similarity: 0.035565319551877105
कम्पनी करोड सम्झौता मन्त्री खरिद युरोपेली भ्याक्सिन निर्माण बजार तयार स्वास्थ्य आलोचना जुटिरह राजनीतिक ल्याइ जिम् फ्रान्स, बेलायती छन्। भाइरसविरुद्ध https://www.thahakhabar.com/news/100466

Article Similarity: 0.03556096150957744
फाँसी शुक्रराज शहीद बाग्मती जोशी अन्तिम बाहिर पकाउँ १९९७ कहालीलाग् गोविन्दप्रसाद हेरे डोरी तर्साउन प्राण ताजा नदिएर थिएँ मारेर मुखबाट https://www.ratopati.com/story/115986

Article Similarity: 0.035560695791413306
भारतीय भारत लिपुलेक भूमि इशारा काली विवाद सेना अतिक्रमण नेपाल कुनै निर्माण नेपाली कालापानी–लिपुलेक वर्गकिमि विरोधाभाष छाङरु त्रिदेशीय आफूतिर प्रमुख https://www.ratopati.com/story/130244

Article Similarity: 0.03555758398528559
नियुक्त आयुर्वेद चिकित्सा ठाकुर परिषद् पत्रसमेत अध्यक्ष पदबहाली रजिस्ट्रार परिषद्, निर्मल रजिष्ट्रार नियुक्ति भुसाल सन्तोष छन्। मन्त्रिपरिषद् मंगलबार बिहीबार दुवै https://www.ratopati.com/story/175677

Article Similarity: 0.0355536780916811
हजार संख्या घण्टा देशभर कोरोनाभाइरसबाट हालसम्म आइसोलेशन संक्रमित सक्रिय गौतम संक्रमित, पुष्टि मृत्यु पछिल्लो यस्तै जागेश्वर कोरोना संस्थागत ब्रिफिङ पीसीआर https://www.ratopati.com/story/151483

Article Similarity: 0.03555034972072934
उहाँ मेरो सामान छोरा थिएँ वाइन मेरा लकडाउन आफ्नो केही कुरा केहि गरिरह हुनुभ लागि पछाडि एक्लो खुसी होला त्यसकारण https://www.ratopati.com/story/133637

Article Similarity: 0.03554722997892345
भुक्तानी कालोपत्र कम्पनी टुङ्गो निर्माण ठेकेदार आपूर्तिकर्ता खाल्डा सिएमसी बानेश्वर, सहायक ज्याला कतिपय गर्न मेलम्ची कार्य भइसक कामदार चालू भइरह https://www.ratopati.com/story/109682

Article Similarity: 0.035543025461400965
सरुवा सहसचिव त्यस्तै उपसचिव गृहमन्त्रालय पाल्पा मन्त्रालय प्रशासन सुर्खेत जिल्ला कार्यालय उच्चपदस्थ पदस्थापना हिरालाल सरुवा, सहित) अधिकारीसहित सिडिओ यदुनाथ कार्य https://www.thahakhabar.com/news/99462

Article Similarity: 0.03554024815090141
राउत प्रहरी महिला विमानस्थल अन्तर्राष्ट्रिय गायि पोष्ट त्रिभुवन आस्था फोटो प्रशंसा फेसबुक धरौटी प्रशंशा श्रमिक नेपालगञ्ज गालीगलौज झापा अपशब्द खिचा https://www.ratopati.com/story/121153

Article Similarity: 0.03553839860833211
अदालत अवहेलना आदेश सर्वोच्च मुद् प्रहरी अवज्ञा प्रत्यक्षीकरण चलाउन पक्राउ कारबाही सजाय अधिकारीविरुद्ध पटकपटक अवरोध सम्पादन दर्ता फैसला गेटबाटै कारवाही https://www.ratopati.com/story/119896

Article Similarity: 0.03553737395760877
महिला सजाय जाहेरी बलात्कार झुठो वीरेन्द्रनगर वर्ष सुर्खेत लगाउ साढे अदालत थिइन् पत्राचार इजलास आरोप शर्मा जिल्ला न्यायाधीश आचार्य नगरपालिका https://www.ratopati.com/story/171875

Article Similarity: 0.0355367081916691
सञ्चालक कलेज भर्ना विद्यार् मेडिकल शुल्क बीडीएस आयोग एमबीबीएस तोके सकेर चिकित्सा छनोट चेतावनी पटक–पटक शिक्षण अन्योल निर्धारण परीक्षा शिक्षा https://www.ratopati.com/story/103610

Article Similarity: 0.03553560209906105
डम्पिङ साइट विमानस्थल पोखरा विमानस्थलबाट जोखिम अन्तर्राष्ट्रिय चराचुरुङ्गी हटाउ उडान छैन् हवाई किलोमिटर निर्माण बर्ड साइटबाट भित्र गुरागाईं डिभाइस लगायतबाट https://www.ratopati.com/story/151730

Article Similarity: 0.03553325441541563
शबनम मृत्युदण्ड सन्त माफी दुर्भाग्य महिला नाता अयोध्या प्रेमी अपिल अपराध शक्ति अमरोहा पुरुषभन् महन्त १४–१५ अध्याय शास्त्र सलिम निम्त्याउँ https://www.ratopati.com/story/168950

Article Similarity: 0.03553249980336725
उमेश सुरा सुराकी दरबारमार्ग श्रेष्ठ पक्र प्रहरी सिआरभी आधाकिलो प्रशन्न अप्रेशन’ कठायत रन्जन महानगरीय सुराक पोशाक अप्रेशन सेयर केजी सुचना https://www.ratopati.com/story/140873

Article Similarity: 0.03553142931638558
लिपपोत भण्डारी अनेरास्ववियु ताप्लेजुङ स्मृति घरसहित जन्मघर चालु जननेता जन्म मर्मतसम्भार निरौला लिम्बू आर्थिक जग्गा वर्ष संरक्षण सरसफाइ विनियोजन नेता https://www.ratopati.com/story/152163

Article Similarity: 0.03552938936062965
विस्तार निर्माण स्तरोन्नति दशमलव ट्र्याक नागढुङ्गा गर्न चौडाइ सडकखण्ड नसकि गल्छी राजमार्ग त्यस सुधार किमी थापा योजना वर्ष तयारी विकल्प https://www.ratopati.com/story/118073

Article Similarity: 0.035525330381585916
श्रीलङ्का आदेश जारी सूचनाअनुसार ४ः३० दिउसो बुधबार बन्दरगाह प्रहरी ठाउँ अधिकारी लागु हुनेगरी फैलिन कोरोना नदिन फर्क सङ्क्रमण घोषणा भाइरस https://www.ratopati.com/story/122356

Article Similarity: 0.035518121447644296
एयरलाइन्स हिमालयन विमानस्थल बेइजिङ चिनियाँ अन्तर्राष्ट्रिय ट्राभल थालिसक भर्खरै लक्ष्मी सञ्चारमाध्यम लम्साल एजेन्सी टिकट थिएनन् नेपाल तीनवटा अनलाइन विमान सूची https://www.ratopati.com/story/98148

Article Similarity: 0.035500401433001205
मूल्य इन्धन ग्यास हवाई निगम उडानतर्फ मट्टीतेल डिजेल, अन्तर्राष्ट्रिय एलपी पेट्रोल अमेरि पाइपलाइनबाट गोइत मूल्यअनुसार इन्डियन प्रतिलिटर कायम बताउनुभ घटेर https://www.ratopati.com/story/101068

Article Similarity: 0.03549725076571317
नेपाली खरिपाटी प्राधिकरण क्वारेन्टाइन राख् चाँगुनारायण फर्का विरोध खाली राख्न निर्णय सरकार भक्तपुर चीनबाट कर्मचारी माथिल्लो ठाउँ विभाग जानकारी बस्ती https://www.lokaantar.com/story/100152

Article Similarity: 0.03549265279550949
निवासी संक्रमित वर्षीया काठमााडौं दहचोक बालक, मन्त्रालय जनकपुर, संक्रमण, बिहीबार योसहित संख्या किशोरी धादिङ स्वास्थ्य तीनै कोरोना जनस्वास्थ्य धनुषा प्रयोगशाला https://www.ratopati.com/story/130118

Article Similarity: 0.03549223656126014
स्वदेश विभेद क्वारेन्टिन नागरिक नेपालीबीच पिछड बेच्न सरकार चढेर नेपाली श्रम परीक्षण नागरिकबीच लकडाउन किरिया वर्ग, होल्डिङ मुलुक धारा व्यवहार https://www.ratopati.com/story/133223

Article Similarity: 0.035487298571934785
संगठन विश्व परीक्षण स्वास्थ्य नमुना दाबी कोरोना चिकित्सक युरोप संक्रमण २०१९ फ्रान्स सुरुवातबारे डिसेम्बर क्रिश्चियन नभएको’ औंल्या हुनसक् निमोनिया स्वस्थ्य https://www.ratopati.com/story/128866

Article Similarity: 0.03548601305450044
साझा खुवा पुस्तक दशैं वर्ष बिक्रीबाट कर्मचारी अंग्रेजी बल्ल बेचेर लेखा नामक गराए। प्रकाशन २०७५ २०७४ फागुन समाचार भट्टराई विगत https://www.thahakhabar.com/news/80824

Article Similarity: 0.035481080964702844
रोहन श्रद्धा श्रेष्ठ विवाह हल्ला वरुण बाल्यकाल कपुर केटा शक्ति थोरै पिता निर्णय मात्र चाहन्छु’ छोरी सेटल दलाल सिरियस नताशा https://www.ratopati.com/story/165476

Article Similarity: 0.03547297712335657
कम्पनी होल्डिङ्स अर्ब करोड वर्ष विदेशी नाफाबाट ममता आर्जित २०७३/७४ एनसेल तथ्याकंअनुसार टेलिकम लगानीकर्ता बैंकबाट करीब आर्थिक २०७५/७६ लैजान स्वीकृति https://www.ratopati.com/story/111600

Article Similarity: 0.03546531467551529
र्‍याली प्रचण्ड–नेपाल धनगढी विरोधसभा समूह सुदूरपश्चिम चौराहा शक्ति प्रदर्शन, कार्यक्रमस्थल टुङ्ग बृहत क्याम्पस निकालेर सुरु कार्यक्रम तस्बिर प्रदेश इन्चार्ज नेकपा https://www.ratopati.com/story/165754

Article Similarity: 0.035464507487564335
क्षेत्रफल नक्सा सरकार जारी भूभाग सार्वजनिक प्राप्ति संविधान नक्साअनुसार पुस्तक गर्न वार्ता अनुसूची संशोधन कालापानी, प्रष्ट भूमि विश्वास भनेर संशोधित https://www.ratopati.com/story/149988

Article Similarity: 0.03546056574748224
हजार विधिबाट कोरोना संख्या आरडिटी परीक्षण पीसीआर संक्रमण कोरोनाभाइरस घण्टा बुधबारसम्म संक्रमित अपडेट पुष्टि, संक्रमणमुक्त जागेश्वर क्वारेन्टिन नेपाल ब्रिफिङ कोरोनाबाट https://www.ratopati.com/story/135815

Article Similarity: 0.03545710993691081
पहिरो प्रेमराज ज्यान कास्की नाती छोरा माछापुच्छ्रे नातिनी सकुशल दम्पती कुशल विक, वर्षीय समिर हमाल तीनै सुवास डिएसपी जिल्ला राती https://www.ratopati.com/story/138875

Article Similarity: 0.03545597525506699
पर्सा धनुषा पुरुष सिरहा बारा जनकपुर यस्तै संख्या संक्रमित ज्यान छन्। पछिल्लो प्रदेश महोत्तरी सप्तरी सर्लाही वर्षीय रौतहट घण्टा महिला https://www.thahakhabar.com/news/106759

Article Similarity: 0.0354559675507925
कारण तराई मिटर प्रदेश बाक्लो चिसो बोरा केही अनुसार कष्टकर नदेख बढ्न बालबालिका शीतलहर सिमरा जनजीवन हुस्सु बनाएर मानवीय क्षति https://www.ratopati.com/story/163487

Article Similarity: 0.03544531150362595
सिरहा कर्जन्हा घरायसी छोरा घाँटी प्रहरी मृत्यु उपचार शालिग्राम अनुन्धान कुटाइबाट रामजान गराइए कुटाईबाट बोक्सी जिल्ला थिचेर जनकपुरस्थित घाईते खुवाउ https://www.ratopati.com/story/153019

Article Similarity: 0.035440548008622313
सेना द्रुतमार्ग सामग्री खरिद आयोजना प्रचलित कार्य नेपाली गुणस्तर प्रतिकार्य दशमलव अन्तर्राष्ट्रियस्तर परामर्शदाता रोकथाम, पारदर्शी सहायक डिजाइन सुपरिवेक्षण प्रक्रिया नेपाल https://www.ratopati.com/story/124927

Article Similarity: 0.035436148144070166
वर्ष विगत घरभित्र पर्व मनाउँ भन्छिन्, हरितालि कोरोना निषेधाज्ञा व्यस्त श्रीमान् पीडा मनाउ मनाउन पाउँ महिला तर्क बताउँ सकारात्मक खल्लो https://www.ratopati.com/story/143487

Article Similarity: 0.03542798531500366
युवती कश्मीर विवाह कश्मीरी प्रहरी हामी अदालत अपहरण धारा युवा खारेज जम्मु–कश्मीर बिहार जोडी पक्राउ युवक न्यायाधीश बस्न आफ्नो जिल्ला https://www.ratopati.com/story/98707

Article Similarity: 0.03542112257066442
बालविवाह शाही फैसला वर्ष अदालत आदेश उमेर दोस्रो विवाह बालिका जिल्ला खत्याड जबरजस्तीकरणी हुँदाहुँ नपुग क्षतिपूर्ति मुगु पत्नी मुद् जरिवाना https://www.thahakhabar.com/news/80226

Article Similarity: 0.035417952456685116
मेगा एक्सटेन्सन काउन्टर भक्तपुर नगरपालिका बैंक ललितपुर कार्यालयहरु, सूर्यविनायक एटीएम, टोखा विस्तार विश्वास काठमाडौँ– शाखारहित महानगरपालिका जित् सेवाग्राही बढिरह उपत्यका https://www.ratopati.com/story/113512

Article Similarity: 0.03541767865759128
रिजाल अपराधिक मिनेन्द्र क्रियाकलाप नेता बाटो निर्देशन द्वन्द्वकाल माओवा मन्त्रालय तनहुँ आरोप लामिछा शाखा शिलान्यास अनेक दुःख प्रतिबन्ध हिंसा अन्तरक्रिया https://www.thahakhabar.com/news/80688

Article Similarity: 0.035415857642791426
समर्थक धरौटी चितवन दुरुत्साहन अभियुक्त शालिकराम रिहा आत्महत्या शर्त अदालत मुद् तारेख अस्मिता लामिछा कँडेल पुडासैनी युवराज मुख्य कार्यक्रम कार्की https://www.thahakhabar.com/news/77934

Article Similarity: 0.03541515776961953
बैंक नाफा बैंक, लाभांश अर्ब वर्ष क्षमता सेयरधनी बाँड्न प्रतिशत बाँकीमध्ये रुपैंया आम्दानी नबिल स्ट्यान्डर्ड चार्टर्ड वाणिज्य पुँजी एभरेष्ट, यस्तो https://www.ratopati.com/story/142788

Article Similarity: 0.03541419117823375
मृत्यु संक्रमित संख्या इटाली योसहित हजार इरान चौबिस भाइरस त्यस्तै जर्मनी स्थिति खराब संक्रमण फ्रान्स युरोप नयाँ घण्टा अहिलेसम्म मुलुक https://www.ratopati.com/story/121974

Article Similarity: 0.035412852618638274
युगान्डा प्रहरी वाइन प्रदर्शन हिंसात्मक बिहीबार उम्मेदवार गायक क्रम यहाँ पक्राउ घाइते हुन् सोमबार राष्ट्रपति समर्थक मुसेभेनी विरोध प्रदर्शन, प्रदर्शनकारीबीच https://www.ratopati.com/story/155467

Article Similarity: 0.03541239093115975
जितबहादुर जवान तुलसीपुर प्रहरी आत्महत्या झुण्डिएर सुनिता माइती सोधपु भैरहवा पत्नी चौधरी इप्र फेला बिसी मंगलवार बर्षीया पक्राउ आफ्नी पोष्टमार्टम https://www.ratopati.com/story/158182

Article Similarity: 0.03541235475355017
पुष्टि उपत्यका संक्रमण घण्टा बढे, मन्त्रालय ललिपुर कोरोना प्रयोगशालाबाट कारोना संक्रमित संख्या ह्वात्तै संक्रमणमुक्त हजार स्वास्थ्य जागेश्वर जसमध्ये स्वाब ब्रिफिङ https://www.ratopati.com/story/137454

Article Similarity: 0.03540983776701142
महासंघ न्यूनतम गर्न सातै श्रेष्ठ स्थापना गाउँपालि आग्रह संयन्त्र उल्लेख प्रयोगशाला अध्यक्ष सामाग्री प्रदेश लक्षण नागरिक संस्था विज्ञप्ति गाउँपालिका बनाउन https://www.thahakhabar.com/news/94590

Article Similarity: 0.03540283508367993
हवल्दार अख्तियार रकमसहित पक्राउ सशस्त्र बुटवल सहायक अुनसन्धान प्रतापपुर सेमरी प्रकाउ आयोग रंगेहात प्रहरी किराना सूचना क्याम्प बुटवल– घरायसी अधिकारी https://www.ratopati.com/story/101827

Article Similarity: 0.03540135706267227
जोशी रिमाल शिक्षा शिक्षाविद् आध्यात्मिक निधन विसं क्याम्पस प्रकाशन योगदान आणविक छर्न अन्त्यष्टि पद्मकन्या ऐश्वर्य चिन्तक नारी १९८८ जन्मनुभ डिल्लीबजार https://www.ratopati.com/story/135286

Article Similarity: 0.03539969738053917
टेनिस उमेर जित् उपाधि अतुलनीय गर्नेछु,’ सक्दिन भनिन् अस्ट्रिया बताइन् क्षण वर्षीया कहिल्यै २०१७ साता फ्रेन्च आफ्ना राम्रो खेलाडी फाइनल https://www.ratopati.com/story/103038

Article Similarity: 0.03539536034065907
पौडेल कृयाशील पार्टी सदस्यता विधान सभापति विपरीत देउवा प्रतिरोध पक्ष महाधिवेशनसम्म प्रवेश तेजोबध भिजा अन्यायपूर्ण परम्परा काँग्रेस हचुवा नेता मिच् https://www.ratopati.com/story/140767

Article Similarity: 0.03539338157827923
पार्टी समस्या नेपाल दिशा संघर्ष विघटन माधव प्रतिज्ञा समस्याप्रति पार्टीभित्र नआत्तिन समाधान दिँदैनौ नेता हुँदैन’, एकता, विचलित विवाद हामी पर्दैन https://www.ratopati.com/story/119715

Article Similarity: 0.035391817145548024
आयोजना डाइभर्सन जलश्रोत निर्माण भेरी–बबई सिंचाइ लगानी मोडालिटी कर्णाली प्रतिशत, बहुउद्देश्यीय प्रदेश सुरुङ आयोजनाबाट मन्त्रालय सह–सचिव ऊर्जा, उक्त मन्त्री जलविद्युत https://www.ratopati.com/story/140271

Article Similarity: 0.03539018196199013
पुरस्कृत कविता महोत्सव कृति प्रकाशन वर्ष सम्पादक प्राडा विसं २०४६ एउटै प्राज्ञ सम्म राष्ट्रिय नेपाल इतिहास बारे साथै गर्न परिषद् https://www.ratopati.com/story/158224

Article Similarity: 0.03538951970584659
कीरा वैज्ञानिक किरा वायु आर्याल नेपाल सर्लाही बिरुवा प्राविधिक एकदम भारत छलफल बाली न्युन शुरु ल्याब नष्ट कारण मन्त्रालय पाकिस्तान https://www.ratopati.com/story/136207

Article Similarity: 0.035388796108197645
नर्स कोरोना बेलायत ट्रष्ट अस्पताल मृत्यु संक्रमण उहाँ चिकित्सक गर्भवती लडाई बालिका भैरह पोजेटिभ दुःख एण्ड वर्षीया जन्म संक्रमित त्यहाँ https://www.ratopati.com/story/126490

Article Similarity: 0.0353847318558185
मधेस तराई कार्यक्रम समृद्धि विकास सञ्चालन जैविक कृषि पूर्वाधार वर्ष निर्माण पछाडि स्थानीय नागरिक सामाजिक सरकार कल्भर्ट, केन्द्र, जीवनस्तर सडक) https://www.ratopati.com/story/157331

Article Similarity: 0.03538268286397787
कतार विज्ञप्ति विभाग प्रहरी अन्तर्वार्ता सचेत अवैध वैदेशिक रोजगार पठाउ युवा कुनै आग्रह कतारस्थित दूतावासबाट मागपत्र पूर्वस्वीकृति लिने, लागि गर्नेलगायत https://www.ratopati.com/story/174652

Article Similarity: 0.03537737045050382
फिल्म शाहरुख भिलेन एक्सन टक्कर सिद्धार्थ दमदार जस्ता भूमिका समेत देशभक्ति अभिनय भूमिकाबाट अब्राहम मुख्य यशराज दर्शक निर्बाह भूमि अभिनयबाट https://www.ratopati.com/story/151507

Article Similarity: 0.03537592409981558

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)