In [1]:
print('-------importing modules-----------------')
import pandas as pd
import torch
import torch.nn as nn
import numpy as np
import os
from loader import load_pkl, load_checkpoint
from itertools import islice
import operator
import ast
from collections import Counter
import pickle

-------importing modules-----------------

In [2]:
pre = load_pkl("../data-processing/processed_data/train_data/pre.pkl")

pkl file is being used:  ../data-processing/processed_data/train_data/pre.pkl

In [4]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"['खनाल-नेपाल', 'समूह', 'नेता', 'सरकार', 'सहभाग...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"['बाबुरामप्रति', 'लिङ्देन', 'कटाक्ष', 'आखिर', ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"['प्रदेश', 'कांग्रेस', 'माओवा', 'सरकार', 'प्रद...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"['कोरोना', 'संक्रमण', 'उच्च', 'विश्व', 'कोरोना...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","['सुदूरपश्चिम', 'रावल', 'शक्ति,', 'पक्ष', 'पटक...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng

In [12]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"['खनाल-नेपाल', 'समूह', 'नेता', 'सरकार', 'सहभाग...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"['बाबुरामप्रति', 'लिङ्देन', 'कटाक्ष', 'आखिर', ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"['प्रदेश', 'कांग्रेस', 'माओवा', 'सरकार', 'प्रद...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"['कोरोना', 'संक्रमण', 'उच्च', 'विश्व', 'कोरोना...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","['सुदूरपश्चिम', 'रावल', 'शक्ति,', 'पक्ष', 'पटक...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng

In [15]:
def get_user_keywords(user_id):
    user_df = user_group.get_group(user_id)
#     user_df = user_df.drop_duplicates(subset=['url'])
    keyword_array = np.array([keywords for keywords in user_df.keywords]).flatten()
#     Counter = Counter(all_arrays)
#     most_occur = Counter.most_common(20)
    user_keywords = [pre.keyword_enocder.get(keywords) for keywords,_ in Counter(keyword_array).most_common(20)]
    return user_keywords

In [16]:
get_user_keywords('f36ea9dcc163903032c205df6b97d9fb')

['प्रहरी',
 'पार्टी',
 'प्रधानमन्त्री',
 'अध्यक्ष',
 'नेता',
 'प्रचण्ड',
 'निर्णय',
 'बैठक',
 'हजार',
 'कोरोना',
 'अस्पताल',
 'ट्रम्प',
 'संक्रमण',
 'राष्ट्रपति',
 'मृत्यु',
 'नेपाल',
 'प्रस्ताव',
 'बाइडेन',
 'सचिवालय',
 'आफ्नो']

In [13]:
user_df = pre.df.drop_duplicates(subset=['user','article_id'])

In [14]:
user_df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
11,83ba6e048bfb2245baeff4a8c40a7372,https://www.ratopati.com/story/94749,[],['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,रातोपाटी संवाददाता,...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...","['सुस्मिता', 'चुम्बन', 'गरिरह', 'भेटिए', 'प्रे...","सुस्मिता चुम्बन गरिरह भेटिए प्रेमी, फोटो चर्चि...","[5968, 30411, 14608, 14843, 9248, 1574, 8248, ...",3,1.520255,95385,31538,20,yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI
12,a704f987e0bc79f6bc185228f1cdfe8a,https://www.ratopati.com/story/94766,[],['काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्ट...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...","['सरकार', 'वार्ता', 'पक्ष', 'देखिएन,', 'युद्ध'...","सरकार वार्ता पक्ष देखिएन, युद्ध धकेल्न खोज्योः...","[27982, 34743, 30577, 20802, 28810, 27104, 253...",2,1.909831,120855,31547,21,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U
13,d9c3dae87d793c35fea9620a293962f4,https://www.ratopati.com/story/94766,[],['काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्ट...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...","['सरकार', 'वार्ता', 'पक्ष', 'देखिएन,', 'युद्ध'...","सरकार वार्ता पक्ष देखिएन, युद्ध धकेल्न खोज्योः...","[27982, 34743, 30577, 20802, 28810, 27104, 253...",2,1.410368,157500,31547,21,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U
14,a7c27e8ad54f246d33d92c85921c21eb,https://www.ratopati.com/story/94769,[],['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,रातोपाटी संवाददाता,...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,"['सर्लाही', 'छुट्टाछुट्टै', 'दुर्घटना', 'मृत्य...",सर्लाही छुट्टाछुट्टै दुर्घटना मृत्यु काठमाडौं–...,"[11916, 31053, 32043, 21744, 8895, 162, 10331,...",5,1.836916,121370,31549,13,2gafeJYipiE31yBVKVOTjGN2bCdzFUPHZ8ymiWoiIvk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"['खनाल-नेपाल', 'समूह', 'नेता', 'सरकार', 'सहभाग...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"['बाबुरामप्रति', 'लिङ्देन', 'कटाक्ष', 'आखिर', ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"['प्रदेश', 'कांग्रेस', 'माओवा', 'सरकार', 'प्रद...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"['कोरोना', 'संक्रमण', 'उच्च', 'विश्व', 'कोरोना...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","['सुदूरपश्चिम', 'रावल', 'शक्ति,', 'पक्ष', 'पटक...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng

In [17]:
user_group = user_df.groupby(['user'])

In [19]:
pre.df['user_keywords'] = pre.df.apply(lambda x: get_user_keywords(x['user']), axis=1)

In [20]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,"['खनाल-नेपाल', 'समूह', 'नेता', 'सरकार', 'सहभाग...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्..."
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,"['बाबुरामप्रति', 'लिङ्देन', 'कटाक्ष', 'आखिर', ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा..."
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,"['प्रदेश', 'कांग्रेस', 'माओवा', 'सरकार', 'प्रद...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व..."
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,"['कोरोना', 'संक्रमण', 'उच्च', 'विश्व', 'कोरोना...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ..."
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"['सुदूरपश्चिम', 'रावल', 'शक्ति,', 'पक्ष', 'पटक...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प..."

In [22]:
def save_pkl(obj, filename):
    with open(filename, 'wb') as outp:  # Overwrites any existing file.
        pickle.dump(obj, outp, pickle.HIGHEST_PROTOCOL)

In [23]:
save_pkl(pre, "pre_user_keywords.pkl")

In [2]:
pre_user_keywords_df = load_pkl("pre_user_keywords.pkl")

pkl file is being used:  pre_user_keywords.pkl

In [3]:
pre_user_keywords_df

In [3]:
pre.user_df

,user,user_keywords
0,db783e901db42f2290736d314d08bdea,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम..."
1,83ba6e048bfb2245baeff4a8c40a7372,"[सुष्मिता, रोहमन, छुट्टी, तस्बिर, चुम्बन, प्रे..."
2,a704f987e0bc79f6bc185228f1cdfe8a,"[पक्ष, विवाद, पार्टी, अनुसार, संयुक्त, बैठक, आ..."
3,d9c3dae87d793c35fea9620a293962f4,"[विप्लव, वार्ता, युद्ध, जबरजस्त, धकेल्न, शान्त..."
4,a7c27e8ad54f246d33d92c85921c21eb,"[लागि, पार्टी, तयार, सरकार, प्रधानमन्त्री, दुर..."
...,...,...
185312,452aa355ab3ea4de4742e5ff36320eaf,"[भर्सन, फिमेल, सार्वजनिक, लामा, भने।, कम्पोज, ..."
185313,5cb16210f5bc5f18bb852ab846f3b5a2,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्..."
185314,93c95988ec06dc1569a02ccb931c43a4,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा..."
185315,433f43b6a40299d0a8c70351a2b57324,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ..."
185316,72afa487553978646c986b80c6970d80,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प..."