In [1]:
import pandas as pd 
import re

In [2]:
thahakhabar_df = pd.read_csv('unprocessed_data/thahakhabar_scrapped.csv')
lokaantar_df = pd.read_csv('unprocessed_data/lokaantar_scrapped.csv')

ratopati_df = pd.read_csv('unprocessed_data/ratopati_scrapped.csv')
ratopati_df['author'] = 'रातोपाटी संवाददाता'
ratopati_df['author_img'] = 'https://ratopatis.prixacdn.net/media/Untitled-min-min-min-min-min.png'

In [3]:
len(thahakhabar_df), len(lokaantar_df), len(ratopati_df)

(6484, 3564, 208742)

In [4]:
thahakhabar_df.columns

Index(['additional_images', 'author', 'author_img', 'content', 'date',
       'head_image', 'heading', 'label', 'source', 'url'],
      dtype='object')

In [5]:
news_list = [ratopati_df, thahakhabar_df, lokaantar_df]

In [6]:
all_join_df = pd.concat(news_list,ignore_index=True)

In [7]:
all_join_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img
0,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,https://www.ratopati.com/story/94744/2019/7/23...,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
1,[],['बाढी पूर्वानुमान महाशाखाले देशका प्रमुख तथा ...,2076-04-07,https://ratopati.prixa.net/media/albums/weathe...,आजको बाढी र मौसमको पूर्वानुमान यस्तो छ,मुख्य समाचार,ratopati,https://www.ratopati.com/story/94754/2019/7/23...,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
2,[],['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,2076-04-07,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,https://www.ratopati.com/story/94749/2019/7/23...,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
3,[],['काठमाडौं – अभिनेता रमित ढुंगाना ‘राजा साहेब’...,2076-04-07,https://ratopati.prixa.net/media/albums/raja_s...,‘राजा साहेब’ बन्दै रमित,मनोरञ्जन,ratopati,https://www.ratopati.com/story/94764/2019/7/23...,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
4,[],['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,2076-04-07,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,https://www.ratopati.com/story/94769/2019/7/23...,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
...,...,...,...,...,...,...,...,...,...,...
218785,[],[' स्वास्थ्य मन्त्रालयले कोरोनाको नयाँ संक्रमि...,2076-12-16,https://lktcdn.prixa.net/media/brifing_new_Vet...,हिजो दिनभर : हालसम्म नेपालमा ५ जनामा कोरोना स...,सम–सामयिक,lokaantar,https://www.lokaantar.com/story/104369/2020/3/...,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...
218786,[],['मलेसियाको अग्रणी पञ्जा कम्पनी टप ग्लोभ कर्पो...,2076-12-16,https://lktcdn.prixa.net/media/gloves_KGS3jodC...,नेपाली कामदारहरू भएको मलेसियाको अग्रणी पञ्जा ...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104376/2020/3/...,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...
218787,[],['कोरोना भाइरस रोकथामका लागि आवश्यक सामाग्री च...,2076-12-16,https://lktcdn.prixa.net/media/Corona_9Oh9kgp5...,चीनबाट आइपुग्यो कोरोना रोकथामका लागि आवश्यक स...,मुख्य समाचार,lokaantar,https://www.lokaantar.com/story/104373/2020/3/...,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...
218788,[],['संसारभरि कोरोनाभाइरस फैलिएपछि चीन तथा चिनिया...,2076-12-16,https://lktcdn.prixa.net/media/twitter_0MpuBkI...,कोरोनाभाइरस फैलिएपछि चिनियाँहरूविरुद्धको घृणा...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104379/2020/3/...,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...
218789,[],['यतिखेर कोरोना भाइरस कोभिड- १९ विरुद्धको लडाई...,2076-12-16,https://lktcdn.prixa.net/media/Dilnishani_Arti...,कोरोनाविरुद्ध लडाईंमा अग्रपंक्तिका सिपाही प्र...,आलेख,lokaantar,https://www.lokaantar.com/story/104380/2020/3/...,दिलनिशानी मगर,https://lktcdn.prixacdn.net/media/dilnisani.jpg

In [8]:
len(all_join_df.url.unique())

218790

In [9]:
def url_filter(url):
    try:
        regex_search_term = '(http[s]*://.*?\w.com[.np]*/)(.*)([a-z]+)/([0-9]+)'
        regex_replacement = re.search(regex_search_term, url).group()
        filtered_url = url.replace(url, regex_replacement)
        if re.search(r'(http[s]*://www.)', url):
            filter_url = filtered_url
        else:
            filter_url = re.sub('(http[s]*://)', r'\1www.', filtered_url)
            return filter_url
    except:
#         print(url)
        filter_url = url
    return filter_url

In [10]:
all_join_df.url = all_join_df.url.apply(lambda x: url_filter(x))

In [11]:
len(all_join_df.url.unique())

42977

In [12]:
all_join_df.drop_duplicates(subset =['url','label'],keep = 'last', inplace = True)

In [13]:
all_join_df.reset_index(drop=True,inplace=True)
all_join_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img
0,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,https://www.ratopati.com/story/94744,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
1,[],['बाढी पूर्वानुमान महाशाखाले देशका प्रमुख तथा ...,2076-04-07,https://ratopati.prixa.net/media/albums/weathe...,आजको बाढी र मौसमको पूर्वानुमान यस्तो छ,मुख्य समाचार,ratopati,https://www.ratopati.com/story/94754,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
2,[],['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,2076-04-07,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,https://www.ratopati.com/story/94749,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
3,[],['काठमाडौं – अभिनेता रमित ढुंगाना ‘राजा साहेब’...,2076-04-07,https://ratopati.prixa.net/media/albums/raja_s...,‘राजा साहेब’ बन्दै रमित,मनोरञ्जन,ratopati,https://www.ratopati.com/story/94764,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
4,[],['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,2076-04-07,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,https://www.ratopati.com/story/94769,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...
...,...,...,...,...,...,...,...,...,...,...
42972,[],[' स्वास्थ्य मन्त्रालयले कोरोनाको नयाँ संक्रमि...,2076-12-16,https://lktcdn.prixa.net/media/brifing_new_Vet...,हिजो दिनभर : हालसम्म नेपालमा ५ जनामा कोरोना स...,सम–सामयिक,lokaantar,https://www.lokaantar.com/story/104369,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...
42973,[],['मलेसियाको अग्रणी पञ्जा कम्पनी टप ग्लोभ कर्पो...,2076-12-16,https://lktcdn.prixa.net/media/gloves_KGS3jodC...,नेपाली कामदारहरू भएको मलेसियाको अग्रणी पञ्जा ...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104376,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...
42974,[],['कोरोना भाइरस रोकथामका लागि आवश्यक सामाग्री च...,2076-12-16,https://lktcdn.prixa.net/media/Corona_9Oh9kgp5...,चीनबाट आइपुग्यो कोरोना रोकथामका लागि आवश्यक स...,मुख्य समाचार,lokaantar,https://www.lokaantar.com/story/104373,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...
42975,[],['संसारभरि कोरोनाभाइरस फैलिएपछि चीन तथा चिनिया...,2076-12-16,https://lktcdn.prixa.net/media/twitter_0MpuBkI...,कोरोनाभाइरस फैलिएपछि चिनियाँहरूविरुद्धको घृणा...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104379,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...
42976,[],['यतिखेर कोरोना भाइरस कोभिड- १९ विरुद्धको लडाई...,2076-12-16,https://lktcdn.prixa.net/media/Dilnishani_Arti...,कोरोनाविरुद्ध लडाईंमा अग्रपंक्तिका सिपाही प्र...,आलेख,lokaantar,https://www.lokaantar.com/story/104380,दिलनिशानी मगर,https://lktcdn.prixacdn.net/media/dilnisani.jpg

In [14]:
all_join_df[all_join_df.source == 'thahakhabar']

,additional_images,content,date,head_image,heading,label,source,url,author,author_img
33967,[],['\xa0अन्तर्राष्ट्रिय नेपाली साहित्य समाज (अने...,2076-04-06,http://cdn3.thahanews.com/media/albums/Chhapro...,अनेसास सर्वोत्कृष्ट पुस्तक पुरस्कार २०१९ को घोषणा,प्रवास,thahakhabar,https://www.thahakhabar.com/news/75139,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...
33968,[],['ईश्वरपुरमा मोटरसाइकलको ठक्करबाट एक जनाको महि...,2076-04-06,http://cdn3.thahanews.com/media/albums/death_O...,"मोटरसाइकलको ठक्करबाट एक महिलाको मृत्यु, एक घाइते",समाज,thahakhabar,https://www.thahakhabar.com/news/75108,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...
33969,[],['मोरङको कटहरी गाउँपालिकाका इन्जिनियरले उपभोक्...,2076-03-29,http://cdn3.thahanews.com/media/uploads/2017/0...,"कटहरीका इन्जिनियरको धन्दा : घुस दिए बाटो पास, ...",सुरक्षा/अपराध,thahakhabar,https://www.thahakhabar.com/news/74464,अर्जुन आचार्य,https://thahacdn.prixacdn.net/media/arjun_acha...
33970,['http://cdn3.thahanews.com/media/albums/lok_s...,[' लोकसेवा आयोगको विज्ञापन खारेजीको माग गर्दै ...,2076-04-03,http://cdn3.thahanews.com/media/albums/lok_sew...,लोकसेवाको विज्ञापन खारेजी माग गर्दै प्रधानमन्त...,फोटो फिचर,thahakhabar,https://www.thahakhabar.com/news/74907,दिपक केसी,https://thahacdn.prixacdn.net/media/deepak_kc.jpg
33971,[],['\xa0नेपालले आईसीसी ट्वान्टी–२० एसियाली क्वाल...,2076-04-06,http://cdn3.thahanews.com/media/albums/nepali-...,बलियो नेपाललाई केही कमजोर कतारको डर,खेलकुद,thahakhabar,https://www.thahakhabar.com/news/75159,नमीन ढकाल,https://thahacdn.prixacdn.net/media/Namin_Dhak...
...,...,...,...,...,...,...,...,...,...,...
40020,[],['प्रधानमन्त्री तथा नेकपा (एमाले) का अध्यक्ष क...,2078-02-25,https://thahacdn.prixacdn.net/media/albums/Bir...,"'ओलीले लात हानिरहने, अझ दुई लात थप्नुस् भनेर ह...",विचार,thahakhabar,https://www.thahakhabar.com/news/127793,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...
40021,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,https://www.thahakhabar.com/news/127379,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...
40022,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,https://www.thahakhabar.com/news/127900,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...
40023,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,https://www.thahakhabar.com/news/127783,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...
40024,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,https://www.thahakhabar.com/news/127887,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...

In [14]:
import pandas as pd 
import time
import nepali_datetime 
import snowballstemmer
import ast
from itertools import chain
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [15]:
stop_words = []
with open('non-potential-topic-word-list.txt', 'r', encoding="utf8") as reader:
    for line in reader:
        line = line.strip('\n')
        stop_words.append(line)
                
stemmer = snowballstemmer.NepaliStemmer()
stopwords = set(stop_words)

def tokenizer(text): 
    tokenized_word = []
    

    stem_list = stemmer.stemWords(text.split())


    tokenized_word = list(filter(word_filter, stem_list))
    # final_tokenized_word = [word for word in tokenized_word if len(word)>3]

    return tokenized_word

def word_filter(stem_word):
    nepali_word = True
    # print('stem_word: ',stem_word)
    if len(stem_word) > 3:
        for letter in stem_word:
            if not 0x0090 <= ord(letter) <= 0x97F:
                nepali_word = False
            return nepali_word 
    else:
        return False

In [16]:
all_join_df['content'] =  all_join_df['content'].apply(lambda x: ast.literal_eval(x))

In [17]:
all_join_df['all_content'] = all_join_df['content'].apply(lambda x: " ".join(x))

In [18]:
all_join_df['all_content']

0        नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अमे...
1        बाढी पूर्वानुमान महाशाखाले देशका प्रमुख तथा मझ...
2        बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरनेट...
3        काठमाडौं – अभिनेता रमित ढुंगाना ‘राजा साहेब’बन...
4        काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाहीम...
                               ...
42972     स्वास्थ्य मन्त्रालयले कोरोनाको नयाँ संक्रमित ...
42973    मलेसियाको अग्रणी पञ्जा कम्पनी टप ग्लोभ कर्पोरे...
42974    कोरोना भाइरस रोकथामका लागि आवश्यक सामाग्री चीन...
42975    संसारभरि कोरोनाभाइरस फैलिएपछि चीन तथा चिनियाँह...
42976    यतिखेर कोरोना भाइरस कोभिड- १९ विरुद्धको लडाईंम...
Name: all_content, Length: 42977, dtype: object

In [19]:
all_join_df['all_content'].iloc[0]

'नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अमेरिकी डलरको खरिददर १०९ रुपैयाँ ९७ पैसा र बिक्रीदर ११० \xa0रुपैयाँ ५७ रुपैयाँ रहेको छ ।\xa0 यस्तै युरो एकको खरिददर १२३ रुपैयाँ २९ पैसा र बिक्रीदर १२३ रुपैयाँ ९६, पाउण्ड एकको खरिददर १३७ रुपैयाँ ०१ पैसा र बिक्रीदर १३७ रुपैयाँ ७६ पैसा रहेको छ । \xa0 यसैगरी कतारी रियाल एकको खरिददर ३० रुपैयाँ २० पैसा र बिक्रीदर ३० रुपैयाँ ३७ पैसा रहेको छ । यस्तै युएई दिराम एकको खरिददर २९ रुपैयाँ ९४ पैसा \xa0र बिक्रीदर ३० रुपैयाँ १० पैसा रहेको छ ।\xa0'

In [20]:
type(all_join_df['all_content'].iloc[0])

str

In [21]:
all_join_df['all_content'] = all_join_df['heading'] + ' ' + all_join_df['all_content']

In [22]:
all_join_df['all_heading_content_list'] = all_join_df.all_content.apply(tokenizer)
all_join_df['all_heading_content']  = all_join_df['all_heading_content_list'].apply(lambda x: " ".join(x))

In [23]:
all_join_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content
0,['https://ratopati.prixa.net/media/albums/666_...,[नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अम...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,https://www.ratopati.com/story/94744,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...
1,[],[बाढी पूर्वानुमान महाशाखाले देशका प्रमुख तथा म...,2076-04-07,https://ratopati.prixa.net/media/albums/weathe...,आजको बाढी र मौसमको पूर्वानुमान यस्तो छ,मुख्य समाचार,ratopati,https://www.ratopati.com/story/94754,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,आजको बाढी र मौसमको पूर्वानुमान यस्तो छ बाढी पू...,"[बाढी, मौसम, पूर्वानुमान, यस्तो, बाढी, पूर्वान...",बाढी मौसम पूर्वानुमान यस्तो बाढी पूर्वानुमान म...
2,[],[बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरने...,2076-04-07,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,https://www.ratopati.com/story/94749,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...","[सुस्मिता, चुम्बन, गरिरह, भेटिए, प्रेमी,, फोटो...","सुस्मिता चुम्बन गरिरह भेटिए प्रेमी, फोटो चर्चि..."
3,[],[काठमाडौं – अभिनेता रमित ढुंगाना ‘राजा साहेब’ब...,2076-04-07,https://ratopati.prixa.net/media/albums/raja_s...,‘राजा साहेब’ बन्दै रमित,मनोरञ्जन,ratopati,https://www.ratopati.com/story/94764,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,‘राजा साहेब’ बन्दै रमित काठमाडौं – अभिनेता रमि...,"[साहेब’, रमित, काठमाडौं, अभिनेता, रमित, ढुंगान...",साहेब’ रमित काठमाडौं अभिनेता रमित ढुंगाना साहे...
4,[],[काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाही...,2076-04-07,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,https://www.ratopati.com/story/94769,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,"[सर्लाही, छुट्टाछुट्टै, दुर्घटना, मृत्यु, काठम...",सर्लाही छुट्टाछुट्टै दुर्घटना मृत्यु काठमाडौं–...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42972,[],[ स्वास्थ्य मन्त्रालयले कोरोनाको नयाँ संक्रमित...,2076-12-16,https://lktcdn.prixa.net/media/brifing_new_Vet...,हिजो दिनभर : हालसम्म नेपालमा ५ जनामा कोरोना स...,सम–सामयिक,lokaantar,https://www.lokaantar.com/story/104369,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,हिजो दिनभर : हालसम्म नेपालमा ५ जनामा कोरोना स...,"[हिजो, दिनभर, हालसम्म, नेपाल, कोरोना, संक्रमण,...","हिजो दिनभर हालसम्म नेपाल कोरोना संक्रमण, काठमा..."
42973,[],[मलेसियाको अग्रणी पञ्जा कम्पनी टप ग्लोभ कर्पोर...,2076-12-16,https://lktcdn.prixa.net/media/gloves_KGS3jodC...,नेपाली कामदारहरू भएको मलेसियाको अग्रणी पञ्जा ...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104376,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...,नेपाली कामदारहरू भएको मलेसियाको अग्रणी पञ्जा ...,"[नेपाली, कामदार, मलेसिया, अग्रणी, पञ्जा, कम्पन...",नेपाली कामदार मलेसिया अग्रणी पञ्जा कम्पनी भन्छ...
42974,[],[कोरोना भाइरस रोकथामका लागि आवश्यक सामाग्री ची...,2076-12-16,https://lktcdn.prixa.net/media/Corona_9Oh9kgp5...,चीनबाट आइपुग्यो कोरोना रोकथामका लागि आवश्यक स...,मुख्य समाचार,lokaantar,https://www.lokaantar.com/story/104373,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,चीनबाट आइपुग्यो कोरोना रोकथामका लागि आवश्यक स...,"[चीनबाट, आइपुग्, कोरोना, रोकथाम, लागि, आवश्यक,...",चीनबाट आइपुग् कोरोना रोकथाम लागि आवश्यक सामाग्...
42975,[],[संसारभरि कोरोनाभाइरस फैलिएपछि चीन तथा चिनियाँ...,2076-12-16,https://lktcdn.prixa.net/media/twitter_0MpuBkI...,कोरोनाभाइरस फैलिएपछि चिनियाँहरूविरुद्धको घृणा...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104379,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...,कोरोनाभाइरस फैलिएपछि चिनियाँहरूविरुद्धको घृणा...,"[कोरोनाभाइरस, फैलिए, चिनियाँहरूविरुद्ध, घृणास्...",कोरोनाभाइरस फैलिए चिनियाँहरूविरुद्ध घृणास्पद अ...
42976,[],[यतिखेर कोरोना भाइरस कोभिड- १९ विरुद्धको लडाईं...,2076-12-16,https://lktcdn.prixa.net/media/Dilnishani_Arti...,कोरोनाविरुद्ध लडाईंमा अग्रपंक्तिका सिपाही प्र...,आलेख,lokaantar,https://www.lokaantar.com/story/104380,दिलनिशानी मगर,https://lktcdn.prixacdn.net/media/dilnisani.jpg,कोरोनाविरुद्ध लडाईंमा अग्रपंक्तिका सिपाही प्र...,"[कोरोनाविरुद्ध, लडाईं, अग्रपंक्ति, सिपाही, प्र...",कोरोनाविरुद्ध लडाईं अग्रपंक्ति सिपाही प्रहरी स...

In [25]:
all_join_df['all_heading_content']

0        यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...
1        आजको बाढी र मौसमको पूर्वानुमान यस्तो छ बाढी पू...
2        सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...
3        ‘राजा साहेब’ बन्दै रमित काठमाडौं – अभिनेता रमि...
4        सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...
                               ...
42972    हिजो दिनभर  : हालसम्म नेपालमा ५ जनामा कोरोना स...
42973    नेपाली कामदारहरू  भएको मलेसियाको अग्रणी पञ्जा ...
42974    चीनबाट आइपुग्यो  कोरोना रोकथामका लागि आवश्यक स...
42975    कोरोनाभाइरस फैलिएपछि  चिनियाँहरूविरुद्धको घृणा...
42976    कोरोनाविरुद्ध लडाईंमा  अग्रपंक्तिका सिपाही प्र...
Name: all_heading_content, Length: 42977, dtype: object

In [26]:
all_join_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content,all_heading_content_list
0,['https://ratopati.prixa.net/media/albums/666_...,[नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अम...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,https://www.ratopati.com/story/94744,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अमे...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने..."
1,[],[बाढी पूर्वानुमान महाशाखाले देशका प्रमुख तथा म...,2076-04-07,https://ratopati.prixa.net/media/albums/weathe...,आजको बाढी र मौसमको पूर्वानुमान यस्तो छ,मुख्य समाचार,ratopati,https://www.ratopati.com/story/94754,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,बाढी पूर्वानुमान महाशाखाले देशका प्रमुख तथा मझ...,आजको बाढी र मौसमको पूर्वानुमान यस्तो छ बाढी पू...,"[बाढी, मौसम, पूर्वानुमान, यस्तो, बाढी, पूर्वान..."
2,[],[बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरने...,2076-04-07,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",मनोरञ्जन,ratopati,https://www.ratopati.com/story/94749,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरनेट...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...","[सुस्मिता, चुम्बन, गरिरह, भेटिए, प्रेमी,, फोटो..."
3,[],[काठमाडौं – अभिनेता रमित ढुंगाना ‘राजा साहेब’ब...,2076-04-07,https://ratopati.prixa.net/media/albums/raja_s...,‘राजा साहेब’ बन्दै रमित,मनोरञ्जन,ratopati,https://www.ratopati.com/story/94764,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,काठमाडौं – अभिनेता रमित ढुंगाना ‘राजा साहेब’बन...,‘राजा साहेब’ बन्दै रमित काठमाडौं – अभिनेता रमि...,"[साहेब’, रमित, काठमाडौं, अभिनेता, रमित, ढुंगान..."
4,[],[काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाही...,2076-04-07,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,प्रदेश मुख्य समाचार,ratopati,https://www.ratopati.com/story/94769,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाहीम...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,"[सर्लाही, छुट्टाछुट्टै, दुर्घटना, मृत्यु, काठम..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42972,[],[ स्वास्थ्य मन्त्रालयले कोरोनाको नयाँ संक्रमित...,2076-12-16,https://lktcdn.prixa.net/media/brifing_new_Vet...,हिजो दिनभर : हालसम्म नेपालमा ५ जनामा कोरोना स...,सम–सामयिक,lokaantar,https://www.lokaantar.com/story/104369,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,स्वास्थ्य मन्त्रालयले कोरोनाको नयाँ संक्रमित ...,हिजो दिनभर : हालसम्म नेपालमा ५ जनामा कोरोना स...,"[हिजो, दिनभर, हालसम्म, नेपाल, कोरोना, संक्रमण,..."
42973,[],[मलेसियाको अग्रणी पञ्जा कम्पनी टप ग्लोभ कर्पोर...,2076-12-16,https://lktcdn.prixa.net/media/gloves_KGS3jodC...,नेपाली कामदारहरू भएको मलेसियाको अग्रणी पञ्जा ...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104376,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...,मलेसियाको अग्रणी पञ्जा कम्पनी टप ग्लोभ कर्पोरे...,नेपाली कामदारहरू भएको मलेसियाको अग्रणी पञ्जा ...,"[नेपाली, कामदार, मलेसिया, अग्रणी, पञ्जा, कम्पन..."
42974,[],[कोरोना भाइरस रोकथामका लागि आवश्यक सामाग्री ची...,2076-12-16,https://lktcdn.prixa.net/media/Corona_9Oh9kgp5...,चीनबाट आइपुग्यो कोरोना रोकथामका लागि आवश्यक स...,मुख्य समाचार,lokaantar,https://www.lokaantar.com/story/104373,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,कोरोना भाइरस रोकथामका लागि आवश्यक सामाग्री चीन...,चीनबाट आइपुग्यो कोरोना रोकथामका लागि आवश्यक स...,"[चीनबाट, आइपुग्, कोरोना, रोकथाम, लागि, आवश्यक,..."
42975,[],[संसारभरि कोरोनाभाइरस फैलिएपछि चीन तथा चिनियाँ...,2076-12-16,https://lktcdn.prixa.net/media/twitter_0MpuBkI...,कोरोनाभाइरस फैलिएपछि चिनियाँहरूविरुद्धको घृणा...,विश्व/प्रवास,lokaantar,https://www.lokaantar.com/story/104379,एजेन्सी,https://lktcdn.prixacdn.net/media/Lokaantar_Lo...,संसारभरि कोरोनाभाइरस फैलिएपछि चीन तथा चिनियाँह...,कोरोनाभाइरस फैलिएपछि चिनियाँहरूविरुद्धको घृणा...,"[कोरोनाभाइरस, फैलिए, चिनियाँहरूविरुद्ध, घृणास्..."
42976,[],[यतिखेर कोरोना भाइरस कोभिड- १९ विरुद्धको लडाईं...,2076-12-16,https://lktcdn.prixa.net/media/Dilnishani_Arti...,कोरोनाविरुद्ध लडाईंमा अग्रपंक्तिका सिपाही प्र...,आलेख,lokaantar,https://www.lokaantar.com/story/104380,दिलनिशानी मगर,https://lktcdn.prixacdn.net/media/dilnisani.jpg,यतिखेर कोरोना भाइरस कोभिड- १९ विरुद्धको लडाईंम...,कोरोनाविरुद्ध लडाईंमा अग्रपंक्तिका सिपाही प्र...,"[कोरोनाविरुद्ध, लडाईं, अग्रपंक्ति, सिपाही, प्र..."

In [25]:
grouped_df = all_join_df.groupby(by=["label"])

In [26]:
uniq_label = grouped_df.label.unique()

In [27]:
all_grouped_df = []
for label in uniq_label:
    label_df = grouped_df.get_group(label[0])
    all_grouped_df.append(label_df)

In [28]:
import operator
label_with_len = {}
for group in all_grouped_df:
    if len(group) > 100:
        label = group.label.unique()[0]
        label_with_len[label] = len(group)
sorted_label_with_len = dict(sorted(label_with_len.items(),  key=operator.itemgetter(1)))
sorted_label_with_len

{'बागमती प्रदेश': 101,
 'धर्म-संस्कृति/रितिथिति': 108,
 'शिक्षा': 109,
 'ब्लग': 129,
 'मधेस प्रदेश': 129,
 'गण्डकी प्रदेश': 141,
 'लुम्बिनी प्रदेश': 162,
 'अनौठो संसार': 165,
 'फिचर': 179,
 'प्रवास': 184,
 'अन्तर्वार्ता': 197,
 'छापा': 201,
 'रोचक': 218,
 'विज्ञान/प्रविधि': 220,
 'साहित्य': 247,
 'ज्योतिष कुना': 259,
 'देश': 260,
 'विश्व/प्रवास': 296,
 'रातोपाटी स्पेसल': 298,
 'फोटो फिचर': 367,
 'स्वास्थ्य/जीवनशैली': 369,
 'स्वास्थ्य': 374,
 'विचार/दृष्टिकोण': 388,
 'छापामा': 418,
 'सुरक्षा/अपराध': 459,
 'कोभिड-१९ {अपडेट}': 490,
 'सम–सामयिक': 563,
 'क्राइम': 633,
 'स्वास्थ्य शैली': 665,
 'प्रदेश मुख्य समाचार': 803,
 'खेलकुद': 1111,
 'राजनीति': 1548,
 'समाज': 1911,
 'पत्रपत्रिकाबाट': 2549,
 'मनोरञ्जन': 2596,
 'अर्थ': 3036,
 'विश्व': 3707,
 'समाचार': 7095,
 'मुख्य समाचार': 8685}

In [29]:
class tfidf():
    def __init__(self, df,num_keywords):
        self.df = df
#         print("len of df: ", len(df))
        self.corpus = self.df["all_heading_content"].tolist()
        self.documents = self.df["all_heading_content_list"].tolist()
        self.n_documents = len(self.documents)
        self.flatten_list = list(chain.from_iterable(self.documents))
        words = Counter(self.flatten_list)
        # print('words before dic: ',words)
        words = {k:v for k,v in words.items()}
        self.word2idx = {o:i for i,o in enumerate(words)}
        self.idx2word = {i:o for i,o in enumerate(words)}
        print('Total word count: ',len(words))
#         self.countvectorizer = CountVectorizer(analyzer = 'word',min_df = 5,max_features = 100000,tokenizer = self.fake_tokenizer)
        self.tfidfvectorizer = TfidfVectorizer(analyzer = 'word',min_df =3,max_features = 100000,tokenizer = self.fake_tokenizer)
        self.top_n = int(num_keywords)
        
        
    def fake_tokenizer(self,text):
        return text.split()
    
    
    def get_keywords(self):
#         count_wm =  self.countvectorizer.fit_transform(self.corpus)
        tfidf_wm =  self.tfidfvectorizer.fit_transform(self.corpus)

#         print('count_wm.shape,tfidf_wm.shape :',count_wm.shape,tfidf_wm.shape)
        
#         count_tokens = self.countvectorizer.get_feature_names()
        tfidf_tokens = self.tfidfvectorizer.get_feature_names()
        
#         df_countvect = pd.DataFrame(data = count_wm.toarray(),columns = count_tokens)
        df_tfidfvect = pd.DataFrame(data = tfidf_wm.toarray(),columns = tfidf_tokens)
        
        keywords_df = pd.DataFrame({n: df_tfidfvect[:].T[col].nlargest(self.top_n).index.tolist() for n, col in enumerate(df_tfidfvect[:].T)}).T
        keywords_df['keywords'] = keywords_df.values.tolist()
#         print(keywords_df['keywords'])
        return keywords_df['keywords']

In [30]:
for grouped_df in all_grouped_df:
    if len(grouped_df) > 100:
        print("len of df before: ", len(grouped_df))
        print(f"Finding keywords for {grouped_df.label.unique()[0]}")
        grouped_df.reset_index(inplace=True)
        tfidf_obj = tfidf(grouped_df,20)
        keyword_df = tfidf_obj.get_keywords()
        
        grouped_df['keywords'] = keyword_df
        grouped_df.dropna(inplace=True)
        print("len of df after: ", len(grouped_df))
        print("----------------------------------------------------------------------")
#         print(grouped_df.head(5))

len of df before:  165
Finding keywords for अनौठो संसार
Total word count:  4619
len of df after:  165
----------------------------------------------------------------------
len of df before:  197
Finding keywords for अन्तर्वार्ता
Total word count:  24959

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  197
----------------------------------------------------------------------
len of df before:  3036
Finding keywords for अर्थ
Total word count:  51666

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  3036
----------------------------------------------------------------------
len of df before:  490
Finding keywords for कोभिड-१९ {अपडेट}
Total word count:  9784

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  490
----------------------------------------------------------------------
len of df before:  633
Finding keywords for क्राइम
Total word count:  13092

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  633
----------------------------------------------------------------------
len of df before:  1111
Finding keywords for खेलकुद
Total word count:  18941

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  1111
----------------------------------------------------------------------
len of df before:  141
Finding keywords for गण्डकी प्रदेश
Total word count:  6115
len of df after:  141
----------------------------------------------------------------------
len of df before:  201
Finding keywords for छापा
Total word count:  6024
len of df after:  201
----------------------------------------------------------------------
len of df before:  418
Finding keywords for छापामा

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

Total word count:  18216
len of df after:  418
----------------------------------------------------------------------
len of df before:  259
Finding keywords for ज्योतिष कुना
Total word count:  5525

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  259
----------------------------------------------------------------------
len of df before:  260
Finding keywords for देश
Total word count:  7809
len of df after:  260
----------------------------------------------------------------------
len of df before:  108
Finding keywords for धर्म-संस्कृति/रितिथिति
Total word count:  18315

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  108
----------------------------------------------------------------------
len of df before:  2549
Finding keywords for पत्रपत्रिकाबाट
Total word count:  34119

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  2549
----------------------------------------------------------------------
len of df before:  803
Finding keywords for प्रदेश मुख्य समाचार
Total word count:  21824

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  803
----------------------------------------------------------------------
len of df before:  184
Finding keywords for प्रवास
Total word count:  7905
len of df after:  184
----------------------------------------------------------------------
len of df before:  179
Finding keywords for फिचर
Total word count:  19135

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  179
----------------------------------------------------------------------
len of df before:  367
Finding keywords for फोटो फिचर
Total word count:  10657

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  367
----------------------------------------------------------------------
len of df before:  101
Finding keywords for बागमती प्रदेश
Total word count:  4129
len of df after:  101
----------------------------------------------------------------------
len of df before:  129
Finding keywords for ब्लग
Total word count:  19266

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  129
----------------------------------------------------------------------
len of df before:  129
Finding keywords for मधेस प्रदेश
Total word count:  4725
len of df after:  129
----------------------------------------------------------------------
len of df before:  2596
Finding keywords for मनोरञ्जन
Total word count:  37806

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  2596
----------------------------------------------------------------------
len of df before:  8685
Finding keywords for मुख्य समाचार
Total word count:  98905

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  8685
----------------------------------------------------------------------
len of df before:  1548
Finding keywords for राजनीति
Total word count:  30994

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  1548
----------------------------------------------------------------------
len of df before:  298
Finding keywords for रातोपाटी स्पेसल
Total word count:  34029

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  298
----------------------------------------------------------------------
len of df before:  218
Finding keywords for रोचक
Total word count:  8124
len of df after:  218
----------------------------------------------------------------------
len of df before:  162
Finding keywords for लुम्बिनी प्रदेश
Total word count:  6717

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  162
----------------------------------------------------------------------
len of df before:  388
Finding keywords for विचार/दृष्टिकोण
Total word count:  45886

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  388
----------------------------------------------------------------------
len of df before:  220
Finding keywords for विज्ञान/प्रविधि
Total word count:  15497
len of df after:  220
----------------------------------------------------------------------
len of df before:  3707
Finding keywords for विश्व
Total word count:  51922

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)
/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  3707
----------------------------------------------------------------------
len of df before:  296
Finding keywords for विश्व/प्रवास
Total word count:  7278
len of df after:  296
----------------------------------------------------------------------
len of df before:  109
Finding keywords for शिक्षा
Total word count:  7215

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  109
----------------------------------------------------------------------
len of df before:  7095
Finding keywords for समाचार

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

Total word count:  82952
len of df after:  7095
----------------------------------------------------------------------
len of df before:  1911
Finding keywords for समाज
Total word count:  37156

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  1910
----------------------------------------------------------------------
len of df before:  563
Finding keywords for सम–सामयिक
Total word count:  17248

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  563
----------------------------------------------------------------------
len of df before:  247
Finding keywords for साहित्य
Total word count:  23093

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  247
----------------------------------------------------------------------
len of df before:  459
Finding keywords for सुरक्षा/अपराध
Total word count:  11868

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  459
----------------------------------------------------------------------
len of df before:  374
Finding keywords for स्वास्थ्य
Total word count:  12327

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  374
----------------------------------------------------------------------
len of df before:  665
Finding keywords for स्वास्थ्य शैली
Total word count:  27761

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

len of df after:  665
----------------------------------------------------------------------
len of df before:  369
Finding keywords for स्वास्थ्य/जीवनशैली
Total word count:  12325
len of df after:  369
----------------------------------------------------------------------

/tmp/ipykernel_296885/3183923651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df['keywords'] = keyword_df
/tmp/ipykernel_296885/3183923651.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_df.dropna(inplace=True)

In [44]:
health_df = all_grouped_df.get_group('स्वास्थ्य/जीवनशैली')
health_df

AttributeError: 'list' object has no attribute 'get_group'

In [47]:
all_join_df[all_join_df.label == 'स्वास्थ्य/जीवनशैली']

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content,all_heading_content_list
69,['https://ratopati.prixa.net/media/albums/inje...,[अमेरिकामा सार्वजनिक स्वास्थ्य र खाद्य मामलामा...,2076-04-05,https://ratopati.prixa.net/media/albums/vyales...,'फिमेल भियाग्रा'मा किन मच्चिरहेको छ बबाल ?,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/94533,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,अमेरिकामा सार्वजनिक स्वास्थ्य र खाद्य मामलामा ...,'फिमेल भियाग्रा'मा किन मच्चिरहेको छ बबाल ? अमे...,"[भियाग्रा', मच्चिरह, बबाल, अमेरिका, सार्वजनिक,..."
105,['https://ratopati.prixa.net/media/albums/coup...,[नेपालमा सेक्स यस्तो मसला हो जसमा रुची त सबैको...,2076-04-02,https://ratopati.prixa.net/media/albums/couple...,सेक्सबारे यसरी परिवर्तन हुन थालेको छ सोच,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/94247,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,नेपालमा सेक्स यस्तो मसला हो जसमा रुची त सबैको ...,सेक्सबारे यसरी परिवर्तन हुन थालेको छ सोच नेपाल...,"[सेक्सबारे, यसरी, परिवर्तन, नेपाल, सेक्स, यस्त..."
122,['https://ratopati.prixa.net/media/albums/mens...,[२७ वर्षकी लौरा टेक्सीरिय हरेक महिना महिनावारी...,2076-04-08,https://ratopati.prixa.net/media/albums/mens_G...,महिनावारीको रगत अनुहारमा लगाउने युवती,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/94869,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,२७ वर्षकी लौरा टेक्सीरिय हरेक महिना महिनावारीक...,महिनावारीको रगत अनुहारमा लगाउने युवती २७ वर्षक...,"[महिनावारी, अनुहार, लगाउ, युवती, वर्ष, लौरा, ट..."
253,[],[६२ वर्षीय मुकेश अम्बानी एसियाकै धनी हुन् । उन...,2076-03-24,https://ratopati.prixa.net/media/albums/mukesh...,सामान्य परिवारका मुकेश अम्बानी कसरी बने धनी ?,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/93275,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,६२ वर्षीय मुकेश अम्बानी एसियाकै धनी हुन् । उनी...,सामान्य परिवारका मुकेश अम्बानी कसरी बने धनी ? ...,"[सामान्य, परिवार, मुकेश, अम्बानी, कसरी, वर्षीय..."
283,[],[‘मादक पदार्थ स्वास्थका लागि हानिकारक छ ।’ माद...,2076-04-02,https://ratopati.prixa.net/media/albums/Beer-h...,टाउको दुखाइमा ‘पेनकिलर’ भन्दा राम्रो ‘बियर’,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/94255,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,‘मादक पदार्थ स्वास्थका लागि हानिकारक छ ।’ मादक...,टाउको दुखाइमा ‘पेनकिलर’ भन्दा राम्रो ‘बियर’ ‘म...,"[दुखाइ, राम्रो, पदार्थ, स्वास्थ, लागि, हानिकार..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33547,[],[पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको...,2077-12-29,https://ratopatis.prixacdn.net/media/albums/dr...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175315,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको ...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ पछ...,"[प्रतिरोधात्मक, क्षमता, बढाउ, पेयपदार्थ, पछिल्..."
33724,[],[मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आ...,2077-10-17,https://ratopatis.prixacdn.net/media/albums/ma...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/165720,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आव...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,"[सबैभन्, सजिलो, तरिकाः, यौनसम्बन्ध, उत्कृष्ट, ..."
33769,[],[कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्...,2077-12-30,https://ratopatis.prixacdn.net/media/albums/co...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175493,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्क...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,"[भाइरस–फ्लूबाट, टाढा, लागि, डाइट, सामेल, खानेक..."
33816,[],[गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै म...,2077-12-31,https://ratopatis.prixacdn.net/media/albums/pr...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175593,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै मा...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक गर्भाध...,"[धेरै, सुत्, गर्भवती, महिला, लागि, खतरनाक, गर्..."
33831,[],[प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवक...,2077-12-28,https://ratopatis.prixacdn.net/media/albums/co...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175234,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवकल...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,"[यौनसम्बन्ध, प्रेमिका, अचम्म, तनाव, प्रेमी,, म..."

In [31]:
combined_df = pd.concat(all_grouped_df)

In [32]:
combined_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content,index,keywords
22368,['https://ratopati.prixacdn.net/media/albums/%...,[अदालतलाई न्यायको आस्थालयका रुपमा पुजिन्छ । न्...,2077-05-30,https://ratopati.prixacdn.net/media/albums/cou...,सर्वोच्च अदालतमा २ रुपैयाँ समेत ‘घुस’,अदालत/प्रशासन,ratopati,https://www.ratopati.com/story/147003,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,सर्वोच्च अदालतमा २ रुपैयाँ समेत ‘घुस’ अदालतलाई...,"[सर्वोच्च, अदालत, रुपैयाँ, समेत, अदालत, न्याय,...",सर्वोच्च अदालत रुपैयाँ समेत अदालत न्याय आस्थाल...,NaN,NaN
22453,['https://ratopati.prixacdn.net/media/albums/c...,[काठमाडौं । भोलि असोज १ गते देशभरका सबै अदालत ...,2077-05-31,https://ratopati.prixacdn.net/media/albums/sar...,भोलि देशभरका अदालत बन्द हुने,अदालत/प्रशासन,ratopati,https://www.ratopati.com/story/147195,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,भोलि देशभरका अदालत बन्द हुने काठमाडौं । भोलि अ...,"[भोलि, देशभर, अदालत, बन्द, काठमाडौं, भोलि, असो...",भोलि देशभर अदालत बन्द काठमाडौं भोलि असोज देशभर...,NaN,NaN
22893,[],[सर्वोच्च अदालतले कोटेश्वरका व्यापारी रामहरि श...,2077-06-15,https://ratopati.prixacdn.net/media/albums/cou...,कोटेश्वरका व्यापारी हत्याकाण्डको मुद्दामा पुनः...,अदालत/प्रशासन,ratopati,https://www.ratopati.com/story/149323,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,कोटेश्वरका व्यापारी हत्याकाण्डको मुद्दामा पुनः...,"[कोटेश्वर, व्यापारी, हत्याकाण्ड, मुद्, पुनः, स...",कोटेश्वर व्यापारी हत्याकाण्ड मुद् पुनः सुनुवाइ...,NaN,NaN
23060,[],[काठमाडौं । प्राडा खगेन्द्रप्रसाद लुइँटेलविरुद...,2077-06-13,https://ratopati.prixacdn.net/media/albums/sar...,लुइँटेलविरुद्ध सर्वोच्च अदालतमा अवहेलनासम्बन्ध...,अदालत/प्रशासन,ratopati,https://www.ratopati.com/story/148950,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,लुइँटेलविरुद्ध सर्वोच्च अदालतमा अवहेलनासम्बन्ध...,"[लुइँटेलविरुद्ध, सर्वोच्च, अदालत, अवहेलनासम्बन...",लुइँटेलविरुद्ध सर्वोच्च अदालत अवहेलनासम्बन्धी ...,NaN,NaN
23188,[],[सर्वोच्च अदालतले कोरोना संक्रमण पत्ता लगाउन ग...,2077-06-15,https://ratopati.prixacdn.net/media/albums/Sup...,सरकारलाई पीसीआर परीक्षण निःशुल्क गर्न सर्वोच्च...,अदालत/प्रशासन,ratopati,https://www.ratopati.com/story/149318,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,सरकारलाई पीसीआर परीक्षण निःशुल्क गर्न सर्वोच्च...,"[सरकार, पीसीआर, परीक्षण, निःशुल्क, गर्न, सर्वो...",सरकार पीसीआर परीक्षण निःशुल्क गर्न सर्वोच्च पर...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26633,['https://ratopati.prixacdn.net/media/albums/H...,"[ , पछिल्लो समय रत्नपार्कमा कोरोना संकटका कार...",2077-07-23,https://ratopati.prixacdn.net/media/albums/Har...,महानगरका ‘प्रतिपक्षी’ उपमेयर : जसले आफ्नै संस्...,हेडलाइन,ratopati,https://www.ratopati.com/story/154022,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,महानगरका ‘प्रतिपक्षी’ उपमेयर : जसले आफ्नै संस्...,"[महानगर, उपमेयर, आफ्नै, संस्थाविरुद्ध, आन्दोलन...",महानगर उपमेयर आफ्नै संस्थाविरुद्ध आन्दोलन गरिन...,NaN,NaN
27353,['https://ratopati.prixacdn.net/media/albums/d...,[काठमाडौं । तिहारको तेस्रो दिन शनिबार (आज) सा...,2077-07-29,https://ratopati.prixacdn.net/media/albums/dip...,लक्ष्मी पूजामा यस्तो देखियो उपत्यका (फोटोफिचर),हेडलाइन,ratopati,https://www.ratopati.com/story/154890,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,लक्ष्मी पूजामा यस्तो देखियो उपत्यका (फोटोफिचर)...,"[लक्ष्मी, पूजा, यस्तो, उपत्य, काठमाडौं, तिहार,...",लक्ष्मी पूजा यस्तो उपत्य काठमाडौं तिहार तेस्रो...,NaN,NaN
27803,[],[काठमाडौं । आर्थिक वर्ष २०७६/७७ को बजेटले गरेक...,2077-08-05,https://ratopati.prixacdn.net/media/albums/fin...,"व्यवसायिक निरन्तरता कर्जा: कार्यविधि आयो, स्रो...",हेडलाइन,ratopati,https://www.ratopati.com/story/155538,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,"व्यवसायिक निरन्तरता कर्जा: कार्यविधि आयो, स्रो...","[व्यवसायिक, निरन्तरता, कर्जा:, कार्यविधि, आयो,...","व्यवसायिक निरन्तरता कर्जा: कार्यविधि आयो, स्रो...",NaN,NaN
27948,['https://ratopati.prixacdn.net/media/albums/r...,[काठमाडौं । झन्डै ४ दर्जन म्युजिक भिडियोमा अभि...,2077-08-06,https://ratopati.prixacdn.net/media/albums/raj...,"‘चपली हाइट’का हिरो राज घिमिरे व्यवसायमा, यस्तो...",हेडलाइन,ratopati,https://www.ratopati.com/story/155691,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,"‘चपली हाइट’का हिरो राज घिमिरे व्यवसायमा, यस्तो...","[हाइट’, हिरो, घिमिरे, व्यवसायमा,, यस्तो, ट्राउ...","हाइट’ हिरो घिमिरे व्यवसायमा, यस्तो ट्राउट फार्...",NaN,NaN
28102,['https://ratopati.prixacdn.net/media/albums/p...,[काठमाडौँ । गृह मन्त्रालयले नेपाल प्रहरीका ३३ ...,2077-08-05,https://ratopati.prixacdn.net/media/albums/ash...,"नेपाल प्रहरीका एसएसपीको सरुवा, काठमाडौँमा अशोक...",हेडलाइन,ratopati,https://www.ratopati.com/story/155529,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,"नेपाल प्रहरीका एसएसपीको सरुवा, काठमाडौँमा अशोक...","[नेपाल, प्रहरी, एसएसपी, सरुवा,, काठमाडौँ, अशोक...","नेपाल प्रहरी एसएसपी सरुवा, काठमाडौँ अशोक सिंह ...",NaN,NaN

In [33]:
combined_df.dropna(subset=['keywords'],inplace=True)
combined_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content,index,keywords
0,[],[पुस १५ गते आफ्नी प्रेमिकाको हत्या गरेको आरोप ...,2076-10-01,https://lktcdn.prixa.net/media/maninder-murder...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97873,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,"[व्यक्ति, टीभी, स्टुड, प्रेमि, हत्या, स्वीकारे...",व्यक्ति टीभी स्टुड प्रेमि हत्या स्वीकारे आफ्नी...,40025.0,"[हत्या, चक्कु, अपराध, टीभी, गरेर, प्रहरी, पक्र..."
1,['https://lktcdn.prixa.net/media/children_ZN2t...,[अमेरिकाको लस एन्जलस विमानस्थलबाट चीनको शांघाई...,2076-10-01,https://lktcdn.prixa.net/media/jet-fuel-kids-s...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97839,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...","[उडिरह, विमानबाट, इन्धन,, स्कूल, विद्यार्, बिज...","उडिरह विमानबाट इन्धन, स्कूल विद्यार् बिजोक अमे...",40033.0,"[विमान, बालबालिका, अवतरण, हजार, तत्कालै, आपतका..."
2,['https://lktcdn.prixa.net/media/hidden-shown_...,[गालाबिंगो डट्कमले एउटा पजल सार्वजनिक गर्दै चि...,2076-10-01,https://lktcdn.prixa.net/media/hidden-squirrel...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ?",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97859,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ? ग...","[चित्र, लोखर्के, पत्ता, लगाउ, गालाबिंगो, डट्कम...",चित्र लोखर्के पत्ता लगाउ गालाबिंगो डट्कम एउटा ...,40102.0,"[पत्ता, लगाउन, तपाईं, लगाउ, कुकुर, भेट्न, चुनौ..."
3,[],[एउटा कुकुरले हार्मोनियमको धुनमा लय मिलाउँदै ग...,2076-10-03,https://lktcdn.prixa.net/media/dog-sings_ePr5H...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98020,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो) ...,"[हार्मोनियम, कुकुर, एउटा, कुकुर, हार्मोनियम, म...",हार्मोनियम कुकुर एउटा कुकुर हार्मोनियम मिलाउँ ...,40104.0,"[कुकुर, एउटा, आनन्द, गाइरह, तिनै, मिलेर, अप्लो..."
4,[],[रुसको राजधानी मस्कोको दोमोदेदोभो विमानस्थलमा ...,2076-10-03,https://lktcdn.prixa.net/media/plane_VLczHtddX...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98023,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो...,"[धावनमार्ग, ओर्ल, विमान, राजधानी, मस्को, दोमोद...",धावनमार्ग ओर्ल विमान राजधानी मस्को दोमोदेदोभो ...,40106.0,"[धावनमार्ग, विमान, अवतरण, यात्रु, विमानस्थल, क..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,[],[पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको...,2077-12-29,https://ratopatis.prixacdn.net/media/albums/dr...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175315,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ पछ...,"[प्रतिरोधात्मक, क्षमता, बढाउ, पेयपदार्थ, पछिल्...",प्रतिरोधात्मक क्षमता बढाउ पेयपदार्थ पछिल्लो वि...,33547.0,"[प्रतिरोधात्मक, संक्रमण, पेयपदार्थ, बचाउँ, क्ष..."
365,[],[मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आ...,2077-10-17,https://ratopatis.prixacdn.net/media/albums/ma...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/165720,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,"[सबैभन्, सजिलो, तरिकाः, यौनसम्बन्ध, उत्कृष्ट, ...",सबैभन् सजिलो तरिकाः यौनसम्बन्ध उत्कृष्ट बनाउ म...,33724.0,"[पैसा, आर्थिक, जीवन, सम्बन्ध, स्थिती, आफ्नो, ऊ..."
366,[],[कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्...,2077-12-30,https://ratopatis.prixacdn.net/media/albums/co...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175493,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,"[भाइरस–फ्लूबाट, टाढा, लागि, डाइट, सामेल, खानेक...","भाइरस–फ्लूबाट टाढा लागि डाइट सामेल खानेकुरा, प...",33769.0,"[प्रतिरोधी, क्षमता, भाइरल, लड्न, स्टार, बेसार,..."
367,[],[गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै म...,2077-12-31,https://ratopatis.prixacdn.net/media/albums/pr...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175593,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक गर्भाध...,"[धेरै, सुत्, गर्भवती, महिला, लागि, खतरनाक, गर्...",धेरै सुत् गर्भवती महिला लागि खतरनाक गर्भाधान द...,33816.0,"[गर्भवती, निन्द्रा, महिला, गर्भपतन, सुत्, आराम..."
368,[],[प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवक...,2077-12-28,https://ratopatis.prixacdn.net/media/albums/co...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175234,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,"[यौनसम्बन्ध, प्रेमिका, अचम्म, तनाव, प्रेमी,, म...","यौनसम्बन्ध प्रेमिका अचम्म तनाव प्रेमी, मागे मद...",33831.0,"[युवक, प्रेमिका, आलोचना, बानी, सबैजना, अचम्म, ..."

In [34]:
combined_df.reset_index(drop=True,)
combined_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content,index,keywords
0,[],[पुस १५ गते आफ्नी प्रेमिकाको हत्या गरेको आरोप ...,2076-10-01,https://lktcdn.prixa.net/media/maninder-murder...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97873,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,"[व्यक्ति, टीभी, स्टुड, प्रेमि, हत्या, स्वीकारे...",व्यक्ति टीभी स्टुड प्रेमि हत्या स्वीकारे आफ्नी...,40025.0,"[हत्या, चक्कु, अपराध, टीभी, गरेर, प्रहरी, पक्र..."
1,['https://lktcdn.prixa.net/media/children_ZN2t...,[अमेरिकाको लस एन्जलस विमानस्थलबाट चीनको शांघाई...,2076-10-01,https://lktcdn.prixa.net/media/jet-fuel-kids-s...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97839,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...","[उडिरह, विमानबाट, इन्धन,, स्कूल, विद्यार्, बिज...","उडिरह विमानबाट इन्धन, स्कूल विद्यार् बिजोक अमे...",40033.0,"[विमान, बालबालिका, अवतरण, हजार, तत्कालै, आपतका..."
2,['https://lktcdn.prixa.net/media/hidden-shown_...,[गालाबिंगो डट्कमले एउटा पजल सार्वजनिक गर्दै चि...,2076-10-01,https://lktcdn.prixa.net/media/hidden-squirrel...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ?",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97859,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ? ग...","[चित्र, लोखर्के, पत्ता, लगाउ, गालाबिंगो, डट्कम...",चित्र लोखर्के पत्ता लगाउ गालाबिंगो डट्कम एउटा ...,40102.0,"[पत्ता, लगाउन, तपाईं, लगाउ, कुकुर, भेट्न, चुनौ..."
3,[],[एउटा कुकुरले हार्मोनियमको धुनमा लय मिलाउँदै ग...,2076-10-03,https://lktcdn.prixa.net/media/dog-sings_ePr5H...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98020,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो) ...,"[हार्मोनियम, कुकुर, एउटा, कुकुर, हार्मोनियम, म...",हार्मोनियम कुकुर एउटा कुकुर हार्मोनियम मिलाउँ ...,40104.0,"[कुकुर, एउटा, आनन्द, गाइरह, तिनै, मिलेर, अप्लो..."
4,[],[रुसको राजधानी मस्कोको दोमोदेदोभो विमानस्थलमा ...,2076-10-03,https://lktcdn.prixa.net/media/plane_VLczHtddX...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98023,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो...,"[धावनमार्ग, ओर्ल, विमान, राजधानी, मस्को, दोमोद...",धावनमार्ग ओर्ल विमान राजधानी मस्को दोमोदेदोभो ...,40106.0,"[धावनमार्ग, विमान, अवतरण, यात्रु, विमानस्थल, क..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,[],[पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको...,2077-12-29,https://ratopatis.prixacdn.net/media/albums/dr...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175315,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ पछ...,"[प्रतिरोधात्मक, क्षमता, बढाउ, पेयपदार्थ, पछिल्...",प्रतिरोधात्मक क्षमता बढाउ पेयपदार्थ पछिल्लो वि...,33547.0,"[प्रतिरोधात्मक, संक्रमण, पेयपदार्थ, बचाउँ, क्ष..."
365,[],[मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आ...,2077-10-17,https://ratopatis.prixacdn.net/media/albums/ma...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/165720,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,"[सबैभन्, सजिलो, तरिकाः, यौनसम्बन्ध, उत्कृष्ट, ...",सबैभन् सजिलो तरिकाः यौनसम्बन्ध उत्कृष्ट बनाउ म...,33724.0,"[पैसा, आर्थिक, जीवन, सम्बन्ध, स्थिती, आफ्नो, ऊ..."
366,[],[कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्...,2077-12-30,https://ratopatis.prixacdn.net/media/albums/co...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175493,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,"[भाइरस–फ्लूबाट, टाढा, लागि, डाइट, सामेल, खानेक...","भाइरस–फ्लूबाट टाढा लागि डाइट सामेल खानेकुरा, प...",33769.0,"[प्रतिरोधी, क्षमता, भाइरल, लड्न, स्टार, बेसार,..."
367,[],[गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै म...,2077-12-31,https://ratopatis.prixacdn.net/media/albums/pr...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175593,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक गर्भाध...,"[धेरै, सुत्, गर्भवती, महिला, लागि, खतरनाक, गर्...",धेरै सुत् गर्भवती महिला लागि खतरनाक गर्भाधान द...,33816.0,"[गर्भवती, निन्द्रा, महिला, गर्भपतन, सुत्, आराम..."
368,[],[प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवक...,2077-12-28,https://ratopatis.prixacdn.net/media/albums/co...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175234,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,"[यौनसम्बन्ध, प्रेमिका, अचम्म, तनाव, प्रेमी,, म...","यौनसम्बन्ध प्रेमिका अचम्म तनाव प्रेमी, मागे मद...",33831.0,"[युवक, प्रेमिका, आलोचना, बानी, सबैजना, अचम्म, ..."

In [35]:
combined_df.set_index('index')

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords
index,,,,,,,,,,,,,,
40025.0,[],[पुस १५ गते आफ्नी प्रेमिकाको हत्या गरेको आरोप ...,2076-10-01,https://lktcdn.prixa.net/media/maninder-murder...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97873,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,"[व्यक्ति, टीभी, स्टुड, प्रेमि, हत्या, स्वीकारे...",व्यक्ति टीभी स्टुड प्रेमि हत्या स्वीकारे आफ्नी...,"[हत्या, चक्कु, अपराध, टीभी, गरेर, प्रहरी, पक्र..."
40033.0,['https://lktcdn.prixa.net/media/children_ZN2t...,[अमेरिकाको लस एन्जलस विमानस्थलबाट चीनको शांघाई...,2076-10-01,https://lktcdn.prixa.net/media/jet-fuel-kids-s...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97839,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...","[उडिरह, विमानबाट, इन्धन,, स्कूल, विद्यार्, बिज...","उडिरह विमानबाट इन्धन, स्कूल विद्यार् बिजोक अमे...","[विमान, बालबालिका, अवतरण, हजार, तत्कालै, आपतका..."
40102.0,['https://lktcdn.prixa.net/media/hidden-shown_...,[गालाबिंगो डट्कमले एउटा पजल सार्वजनिक गर्दै चि...,2076-10-01,https://lktcdn.prixa.net/media/hidden-squirrel...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ?",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97859,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ? ग...","[चित्र, लोखर्के, पत्ता, लगाउ, गालाबिंगो, डट्कम...",चित्र लोखर्के पत्ता लगाउ गालाबिंगो डट्कम एउटा ...,"[पत्ता, लगाउन, तपाईं, लगाउ, कुकुर, भेट्न, चुनौ..."
40104.0,[],[एउटा कुकुरले हार्मोनियमको धुनमा लय मिलाउँदै ग...,2076-10-03,https://lktcdn.prixa.net/media/dog-sings_ePr5H...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98020,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो) ...,"[हार्मोनियम, कुकुर, एउटा, कुकुर, हार्मोनियम, म...",हार्मोनियम कुकुर एउटा कुकुर हार्मोनियम मिलाउँ ...,"[कुकुर, एउटा, आनन्द, गाइरह, तिनै, मिलेर, अप्लो..."
40106.0,[],[रुसको राजधानी मस्कोको दोमोदेदोभो विमानस्थलमा ...,2076-10-03,https://lktcdn.prixa.net/media/plane_VLczHtddX...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98023,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो...,"[धावनमार्ग, ओर्ल, विमान, राजधानी, मस्को, दोमोद...",धावनमार्ग ओर्ल विमान राजधानी मस्को दोमोदेदोभो ...,"[धावनमार्ग, विमान, अवतरण, यात्रु, विमानस्थल, क..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33547.0,[],[पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको...,2077-12-29,https://ratopatis.prixacdn.net/media/albums/dr...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175315,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ पछ...,"[प्रतिरोधात्मक, क्षमता, बढाउ, पेयपदार्थ, पछिल्...",प्रतिरोधात्मक क्षमता बढाउ पेयपदार्थ पछिल्लो वि...,"[प्रतिरोधात्मक, संक्रमण, पेयपदार्थ, बचाउँ, क्ष..."
33724.0,[],[मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आ...,2077-10-17,https://ratopatis.prixacdn.net/media/albums/ma...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/165720,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,"[सबैभन्, सजिलो, तरिकाः, यौनसम्बन्ध, उत्कृष्ट, ...",सबैभन् सजिलो तरिकाः यौनसम्बन्ध उत्कृष्ट बनाउ म...,"[पैसा, आर्थिक, जीवन, सम्बन्ध, स्थिती, आफ्नो, ऊ..."
33769.0,[],[कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्...,2077-12-30,https://ratopatis.prixacdn.net/media/albums/co...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175493,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,"[भाइरस–फ्लूबाट, टाढा, लागि, डाइट, सामेल, खानेक...","भाइरस–फ्लूबाट टाढा लागि डाइट सामेल खानेकुरा, प...","[प्रतिरोधी, क्षमता, भाइरल, लड्न, स्टार, बेसार,..."
33816.0,[],[गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै म...,2077-12-31,https://ratopatis.prixacdn.net/media/albums/pr...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175593,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक गर्भाध...,"[धेरै, सुत्, गर्भवती, महिला, लागि, खतरनाक, गर्...",धेरै सुत् गर्भवती महिला लागि खतरनाक गर्भाधान द...,"[गर्भवती, निन्द्रा, महिला, गर्भपतन, सुत्, आराम..."
33831.0,[],[प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवक...,2077-12-28,https://ratopatis.prixacdn.net/media/albums/co...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175234,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,"[यौनसम्बन्ध, प्रेमिका, अचम्म, तनाव, प्रेमी,, म...","यौनसम्बन्ध प्रेमिका अचम्म तनाव प्रेमी, मागे मद...","[युवक, प्रेमिका, आलोचना, बानी, सबैजना, अचम्म, ..."

In [36]:
combined_df.reset_index(drop=True, inplace = True)

In [37]:
combined_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content,index,keywords
0,[],[पुस १५ गते आफ्नी प्रेमिकाको हत्या गरेको आरोप ...,2076-10-01,https://lktcdn.prixa.net/media/maninder-murder...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97873,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,"[व्यक्ति, टीभी, स्टुड, प्रेमि, हत्या, स्वीकारे...",व्यक्ति टीभी स्टुड प्रेमि हत्या स्वीकारे आफ्नी...,40025.0,"[हत्या, चक्कु, अपराध, टीभी, गरेर, प्रहरी, पक्र..."
1,['https://lktcdn.prixa.net/media/children_ZN2t...,[अमेरिकाको लस एन्जलस विमानस्थलबाट चीनको शांघाई...,2076-10-01,https://lktcdn.prixa.net/media/jet-fuel-kids-s...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97839,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...","[उडिरह, विमानबाट, इन्धन,, स्कूल, विद्यार्, बिज...","उडिरह विमानबाट इन्धन, स्कूल विद्यार् बिजोक अमे...",40033.0,"[विमान, बालबालिका, अवतरण, हजार, तत्कालै, आपतका..."
2,['https://lktcdn.prixa.net/media/hidden-shown_...,[गालाबिंगो डट्कमले एउटा पजल सार्वजनिक गर्दै चि...,2076-10-01,https://lktcdn.prixa.net/media/hidden-squirrel...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ?",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97859,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ? ग...","[चित्र, लोखर्के, पत्ता, लगाउ, गालाबिंगो, डट्कम...",चित्र लोखर्के पत्ता लगाउ गालाबिंगो डट्कम एउटा ...,40102.0,"[पत्ता, लगाउन, तपाईं, लगाउ, कुकुर, भेट्न, चुनौ..."
3,[],[एउटा कुकुरले हार्मोनियमको धुनमा लय मिलाउँदै ग...,2076-10-03,https://lktcdn.prixa.net/media/dog-sings_ePr5H...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98020,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो) ...,"[हार्मोनियम, कुकुर, एउटा, कुकुर, हार्मोनियम, म...",हार्मोनियम कुकुर एउटा कुकुर हार्मोनियम मिलाउँ ...,40104.0,"[कुकुर, एउटा, आनन्द, गाइरह, तिनै, मिलेर, अप्लो..."
4,[],[रुसको राजधानी मस्कोको दोमोदेदोभो विमानस्थलमा ...,2076-10-03,https://lktcdn.prixa.net/media/plane_VLczHtddX...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98023,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो...,"[धावनमार्ग, ओर्ल, विमान, राजधानी, मस्को, दोमोद...",धावनमार्ग ओर्ल विमान राजधानी मस्को दोमोदेदोभो ...,40106.0,"[धावनमार्ग, विमान, अवतरण, यात्रु, विमानस्थल, क..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41364,[],[पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको...,2077-12-29,https://ratopatis.prixacdn.net/media/albums/dr...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175315,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ पछ...,"[प्रतिरोधात्मक, क्षमता, बढाउ, पेयपदार्थ, पछिल्...",प्रतिरोधात्मक क्षमता बढाउ पेयपदार्थ पछिल्लो वि...,33547.0,"[प्रतिरोधात्मक, संक्रमण, पेयपदार्थ, बचाउँ, क्ष..."
41365,[],[मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आ...,2077-10-17,https://ratopatis.prixacdn.net/media/albums/ma...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/165720,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,"[सबैभन्, सजिलो, तरिकाः, यौनसम्बन्ध, उत्कृष्ट, ...",सबैभन् सजिलो तरिकाः यौनसम्बन्ध उत्कृष्ट बनाउ म...,33724.0,"[पैसा, आर्थिक, जीवन, सम्बन्ध, स्थिती, आफ्नो, ऊ..."
41366,[],[कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्...,2077-12-30,https://ratopatis.prixacdn.net/media/albums/co...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175493,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,"[भाइरस–फ्लूबाट, टाढा, लागि, डाइट, सामेल, खानेक...","भाइरस–फ्लूबाट टाढा लागि डाइट सामेल खानेकुरा, प...",33769.0,"[प्रतिरोधी, क्षमता, भाइरल, लड्न, स्टार, बेसार,..."
41367,[],[गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै म...,2077-12-31,https://ratopatis.prixacdn.net/media/albums/pr...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175593,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक गर्भाध...,"[धेरै, सुत्, गर्भवती, महिला, लागि, खतरनाक, गर्...",धेरै सुत् गर्भवती महिला लागि खतरनाक गर्भाधान द...,33816.0,"[गर्भवती, निन्द्रा, महिला, गर्भपतन, सुत्, आराम..."
41368,[],[प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवक...,2077-12-28,https://ratopatis.prixacdn.net/media/albums/co...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175234,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,"[यौनसम्बन्ध, प्रेमिका, अचम्म, तनाव, प्रेमी,, म...","यौनसम्बन्ध प्रेमिका अचम्म तनाव प्रेमी, मागे मद...",33831.0,"[युवक, प्रेमिका, आलोचना, बानी, सबैजना, अचम्म, ..."

In [38]:
combined_df.drop(columns=['index'], inplace = True)
combined_df

,additional_images,content,date,head_image,heading,label,source,url,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords
0,[],[पुस १५ गते आफ्नी प्रेमिकाको हत्या गरेको आरोप ...,2076-10-01,https://lktcdn.prixa.net/media/maninder-murder...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97873,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,यी व्यक्तिले टीभी स्टुडियोमा गएर प्रेमिका हत्...,"[व्यक्ति, टीभी, स्टुड, प्रेमि, हत्या, स्वीकारे...",व्यक्ति टीभी स्टुड प्रेमि हत्या स्वीकारे आफ्नी...,"[हत्या, चक्कु, अपराध, टीभी, गरेर, प्रहरी, पक्र..."
1,['https://lktcdn.prixa.net/media/children_ZN2t...,[अमेरिकाको लस एन्जलस विमानस्थलबाट चीनको शांघाई...,2076-10-01,https://lktcdn.prixa.net/media/jet-fuel-kids-s...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97839,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"उडिरहेको विमानबाट खस्यो इन्धन, स्कूलका विद्या...","[उडिरह, विमानबाट, इन्धन,, स्कूल, विद्यार्, बिज...","उडिरह विमानबाट इन्धन, स्कूल विद्यार् बिजोक अमे...","[विमान, बालबालिका, अवतरण, हजार, तत्कालै, आपतका..."
2,['https://lktcdn.prixa.net/media/hidden-shown_...,[गालाबिंगो डट्कमले एउटा पजल सार्वजनिक गर्दै चि...,2076-10-01,https://lktcdn.prixa.net/media/hidden-squirrel...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ?",अनौठो संसार,lokaantar,https://www.lokaantar.com/story/97859,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,"यस चित्रमा लोखर्के पनि छ, पत्ता लगाउनुभयो ? ग...","[चित्र, लोखर्के, पत्ता, लगाउ, गालाबिंगो, डट्कम...",चित्र लोखर्के पत्ता लगाउ गालाबिंगो डट्कम एउटा ...,"[पत्ता, लगाउन, तपाईं, लगाउ, कुकुर, भेट्न, चुनौ..."
3,[],[एउटा कुकुरले हार्मोनियमको धुनमा लय मिलाउँदै ग...,2076-10-03,https://lktcdn.prixa.net/media/dog-sings_ePr5H...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98020,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,हार्मोनियमको धुनमा कुकुरले गायो गीत (भिडियो) ...,"[हार्मोनियम, कुकुर, एउटा, कुकुर, हार्मोनियम, म...",हार्मोनियम कुकुर एउटा कुकुर हार्मोनियम मिलाउँ ...,"[कुकुर, एउटा, आनन्द, गाइरह, तिनै, मिलेर, अप्लो..."
4,[],[रुसको राजधानी मस्कोको दोमोदेदोभो विमानस्थलमा ...,2076-10-03,https://lktcdn.prixa.net/media/plane_VLczHtddX...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो),अनौठो संसार,lokaantar,https://www.lokaantar.com/story/98023,लोकान्तर संवाददाता,https://lktcdn.prixacdn.net/media/facebook_pro...,बन्दै गरेको धावनमार्गमा ओर्लियो विमान (भिडियो...,"[धावनमार्ग, ओर्ल, विमान, राजधानी, मस्को, दोमोद...",धावनमार्ग ओर्ल विमान राजधानी मस्को दोमोदेदोभो ...,"[धावनमार्ग, विमान, अवतरण, यात्रु, विमानस्थल, क..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41364,[],[पछिल्लो समय विभिन्न प्रकारका संक्रमण बढिरहेको...,2077-12-29,https://ratopatis.prixacdn.net/media/albums/dr...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175315,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,रोग प्रतिरोधात्मक क्षमता बढाउने ५ पेयपदार्थ पछ...,"[प्रतिरोधात्मक, क्षमता, बढाउ, पेयपदार्थ, पछिल्...",प्रतिरोधात्मक क्षमता बढाउ पेयपदार्थ पछिल्लो वि...,"[प्रतिरोधात्मक, संक्रमण, पेयपदार्थ, बचाउँ, क्ष..."
41365,[],[मानिसको जीवन विभिन्न भागमा बाँडिएको हुन्छ । आ...,2077-10-17,https://ratopatis.prixacdn.net/media/albums/ma...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/165720,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धनी हुने सबैभन्दा सजिलो तरिकाः यौनसम्बन्धलाई उ...,"[सबैभन्, सजिलो, तरिकाः, यौनसम्बन्ध, उत्कृष्ट, ...",सबैभन् सजिलो तरिकाः यौनसम्बन्ध उत्कृष्ट बनाउ म...,"[पैसा, आर्थिक, जीवन, सम्बन्ध, स्थिती, आफ्नो, ऊ..."
41366,[],[कोरोनाको कहर बढ्दो छ । यसबाट बच्नका लागि मास्...,2077-12-30,https://ratopatis.prixacdn.net/media/albums/co...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175493,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,भाइरस–फ्लूबाट टाढा रहनका लागि डाइटमा सामेल गर्...,"[भाइरस–फ्लूबाट, टाढा, लागि, डाइट, सामेल, खानेक...","भाइरस–फ्लूबाट टाढा लागि डाइट सामेल खानेकुरा, प...","[प्रतिरोधी, क्षमता, भाइरल, लड्न, स्टार, बेसार,..."
41367,[],[गर्भाधानको दौरान थकान महसुस हुनु सामान्य नै म...,2077-12-31,https://ratopatis.prixacdn.net/media/albums/pr...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175593,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,धेरै सुत्नु गर्भवती महिलाका लागि खतरनाक गर्भाध...,"[धेरै, सुत्, गर्भवती, महिला, लागि, खतरनाक, गर्...",धेरै सुत् गर्भवती महिला लागि खतरनाक गर्भाधान द...,"[गर्भवती, निन्द्रा, महिला, गर्भपतन, सुत्, आराम..."
41368,[],[प्रेमिकाको अचम्मको मागले तनावमा परेका एक युवक...,2077-12-28,https://ratopatis.prixacdn.net/media/albums/co...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,स्वास्थ्य/जीवनशैली,ratopati,https://www.ratopati.com/story/175234,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यौनसम्बन्ध पछि प्रेमिकाको अचम्मको मागले तनावमा...,"[यौनसम्बन्ध, प्रेमिका, अचम्म, तनाव, प्रेमी,, म...","यौनसम्बन्ध प्रेमिका अचम्म तनाव प्रेमी, मागे मद...","[युवक, प्रेमिका, आलोचना, बानी, सबैजना, अचम्म, ..."

In [39]:
combined_df.to_csv('processed_data/df_with_keywords.csv')

In [1]:
import pickle

In [2]:
with open('processed_data/df_with_tfidf_keywords.pickle', 'wb') as f:
    pickle.dump(combined_df, f)

NameError: name 'combined_df' is not defined

In [40]:
from pprint import pprint# Gensim
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel# spaCy for preprocessing
import spacy# Plotting tools
import pyLDAvis

import pyLDAvis.gensim_models  # don't skip this
import matplotlib.pyplot as plt
%matplotlib inline


# Enable logging for gensim - optional
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.ERROR)

import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

2022-02-18 15:46:36.261272: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

In [43]:
corpus = combined_df["all_heading_content"].tolist()
documents = combined_df["all_heading_content_list"].tolist()

In [44]:
%%time
# Build the bigram and trigram models
bigram = gensim.models.Phrases(documents, min_count=5, threshold=5) # higher threshold fewer phrases.
# trigram = gensim.models.Phrases(bigram[documents], threshold=8)  

# Faster way to get a sentence clubbed as a trigram/bigram
bigram_mod = gensim.models.phrases.Phraser(bigram)
# trigram_mod = gensim.models.phrases.Phraser(trigram)

# See trigram example
# print(bigram_mod[documents[0]],trigram_mod[bigram_mod[documents[0]]])

CPU times: user 15 s, sys: 152 ms, total: 15.1 s
Wall time: 15.1 s

In [45]:
len(documents[0]),len(bigram_mod[documents[0]])

(137, 122)

In [46]:
def make_bigrams(articles):
    return [bigram_mod[doc] for doc in articles]

In [47]:
%%time
article_bigrams = make_bigrams(documents)

CPU times: user 4.59 s, sys: 48 ms, total: 4.64 s
Wall time: 4.64 s

In [48]:
%%time
# Create Dictionary
# article_bigrams = documents
id2word = corpora.Dictionary(article_bigrams)

# Create Corpus
# texts = article_bigrams

# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in article_bigrams]

# View
print(corpus[:1])

[[(0, 1), (1, 2), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 3), (15, 2), (16, 1), (17, 1), (18, 1), (19, 1), (20, 2), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 2), (27, 1), (28, 2), (29, 3), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1), (38, 1), (39, 2), (40, 2), (41, 1), (42, 1), (43, 3), (44, 1), (45, 1), (46, 1), (47, 1), (48, 1), (49, 2), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1), (57, 11), (58, 1), (59, 1), (60, 1), (61, 1), (62, 1), (63, 1), (64, 1), (65, 3), (66, 1), (67, 1), (68, 4), (69, 4), (70, 1), (71, 4), (72, 1), (73, 4), (74, 1), (75, 1), (76, 1), (77, 4), (78, 1), (79, 1), (80, 1)]]
CPU times: user 8.31 s, sys: 83.9 ms, total: 8.39 s
Wall time: 8.4 s

In [49]:
%%time
# Build LDA model
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=13, 
                                           random_state=108,
                                           update_every=2,
                                           chunksize=64,
                                           iterations = 18,
                                           passes=5,
                                           alpha='auto',
                                           per_word_topics=True)

CPU times: user 15min 16s, sys: 7min 7s, total: 22min 24s
Wall time: 12min 25s

In [50]:
# Print the Keyword in the 10 topics
pprint(lda_model.print_topics())
doc_lda = lda_model[corpus]

[(0,
  '0.024*"सरकार" + 0.023*"नेपाल" + 0.022*"लागि" + 0.021*"गर्न" + 0.010*"बताए" '
  '+ 0.010*"बिरामी" + 0.008*"अवस्था" + 0.008*"समेत" + 0.007*"कोरोना_भाइरस" + '
  '0.007*"आवश्यक"'),
 (1,
  '0.031*"नकारात्मक" + 0.028*"सवारी_साधन" + 0.026*"तरकारी" + 0.025*"सवारी" + '
  '0.024*"ग्राम" + 0.018*"ग्यास" + 0.016*"वाइन" + 0.016*"बजार" + 0.015*"मूल्य" '
  '+ 0.015*"प्याज"'),
 (2,
  '0.018*"धेरै" + 0.016*"कुरा" + 0.015*"हामी" + 0.013*"त्यस" + 0.013*"तपाईं" + '
  '0.013*"लागि" + 0.013*"मानिस" + 0.013*"केही" + 0.012*"कारण" + 0.011*"आफ्नो"'),
 (3,
  '0.039*"लागि" + 0.013*"वर्ष" + 0.012*"नेपाल" + 0.011*"अनुसार" + 0.011*"उक्त" '
  '+ 0.011*"क्षेत्र" + 0.011*"प्रतिशत" + 0.010*"समेत" + 0.010*"विभिन्न" + '
  '0.009*"प्रयोग"'),
 (4,
  '0.014*"गर्छन्।" + 0.004*"अभिनय" + 0.003*"रोमान्स" + 0.002*"सक्छन्।" + '
  '0.002*"नातेदार" + 0.001*"प्रमोद" + 0.001*"सौरभ" + 0.001*"फिल्म_अभिनय" + '
  '0.001*"गीत," + 0.001*"दर्ता_गराउ"'),
 (5,
  '0.014*"पाटन" + 0.006*"हङकङ" + 0.002*"अदालत_न्यायाधीश" + 0.001*"खिच्" + '
  '0.001*"सजाय_सुना" + 0.000*"जडीबुटी" + 0.000*"ब्यापारी" + '
  '0.000*"कुकुर_बिरालो" + 0.000*"घरपालुवा_जनावर" + 0.000*"बसपार्क"'),
 (6,
  '0.039*"प्रहरी" + 0.036*"छन्।" + 0.023*"थियो।" + 0.020*"बताए।" + '
  '0.017*"थिए।" + 0.016*"पक्राउ" + 0.012*"स्थानीय" + 0.011*"कार्यालय" + '
  '0.011*"अनुसार" + 0.010*"सेवन"'),
 (7,
  '0.010*"स्पेन" + 0.006*"महासङ्घ" + 0.001*"भिड्" + 0.001*"दुई–दुई" + '
  '0.001*"ईरान" + 0.000*"घुमेर" + 0.000*"इसाइ_धर्मावलम्बी" + '
  '0.000*"पत्रकार_महासङ्घ" + 0.000*"सार्वजनिक_यातायात" + '
  '0.000*"पशुपति_क्षेत्र"'),
 (8,
  '0.205*"महिला" + 0.056*"पुरुष" + 0.038*"महिनावारी" + 0.018*"पाठेघर" + '
  '0.013*"हिंसा" + 0.005*"महिला_पुरुष" + 0.004*"पुरुष_महिला" + '
  '0.002*"आक्रमणकारी" + 0.001*"भिडन्त" + 0.001*"महिला_बलात्कार"'),
 (9,
  '0.007*"मोटर" + 0.006*"बाइक" + 0.005*"बेल्जियम" + 0.005*"नम्बर_प्लेट" + '
  '0.004*"न्यू" + 0.003*"लम्बाई" + 0.002*"प्रजापति" + 0.002*"गुड्" + '
  '0.001*"म्याक्स" + 0.001*"क्लिप"'),
 (10,
  '0.053*"मृत्यु" + 0.036*"मधुमेह" + 0.027*"फोक्सो" + 0.025*"मिर्गौला" + '
  '0.024*"आफन्त" + 0.024*"दुर्घटना" + 0.024*"प्रहरी_निरीक्षक" + 0.021*"निधन" + '
  '0.021*"बालबालिका" + 0.020*"उपचार_क्रम"'),
 (11,
  '0.043*"अस्पताल" + 0.031*"उपचार" + 0.025*"संक्रमण" + 0.025*"कोरोना" + '
  '0.023*"परीक्षण" + 0.020*"स्वास्थ्य" + 0.017*"संक्रमित" + 0.015*"हजार" + '
  '0.014*"मृत्यु" + 0.013*"व्यक्ति"'),
 (12,
  '0.019*"जवान" + 0.003*"पुटिन" + 0.000*"राष्ट्रपति_भ्लादिमिर" + '
  '0.000*"रेस्टुराँ" + 0.000*"मेवा" + 0.000*"निर्घात_कुटपिट" + '
  '0.000*"राष्ट्रपति_पुटिन" + 0.000*"सैनिक_जवान" + 0.000*"कंगो" + '
  '0.000*"रत्न"')]

In [ ]:
# Compute Perplexity
print('\nPerplexity: ', lda_model.log_perplexity(corpus))  # a measure of how good the model is. lower the better.

# Compute Coherence Score
coherence_model_lda = CoherenceModel(model=lda_model, texts=documents, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence() 
print('\nCoherence Score: ', coherence_lda)

Perplexity:  -16.042504363631487

In [ ]:
pyLDAvis.enable_notebook(local=True)
vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
pyLDAvis.show(vis)

In [ ]:
import os
import time
# from gensim.models.wrappers import LdaMallet
import ldamallet

os.environ['MALLET_HOME'] = 'mallet-2.0.8'
mallet_path = 'mallet-2.0.8/bin/mallet'

In [ ]:
model_topics = lda_model.show_topics(formatted=False)
pprint(lda_model.print_topics(num_words=20))

In [3]:
def format_topics_sentences(ldamodel, corpus=corpus, texts=documents):
    # Init output
    sent_topics_df = pd.DataFrame()

    # Get main topic in each document
    for i, row in enumerate(ldamodel[corpus]):
        # print(row, type(row))
        row = sorted(row, key=lambda x: (x[1]), reverse=True)
        # Get the Dominant topic, Perc Contribution and Keywords for each document
        for j, (topic_num, prop_topic) in enumerate(row):
            if j == 0:  # => dominant topic
                wp = ldamodel.show_topic(topic_num)
                topic_keywords = ", ".join([word for word, prop in wp])
                sent_topics_df = sent_topics_df.append(pd.Series([int(topic_num), round(prop_topic,4), topic_keywords]), ignore_index=True)
            else:
                break
    sent_topics_df.columns = ['Dominant_Topic', 'Perc_Contribution', 'Topic_Keywords']

    # Add original text to the end of the output
    contents = pd.Series(texts)
    sent_topics_df = pd.concat([sent_topics_df, contents], axis=1)
    return(sent_topics_df)


df_topic_sents_keywords = format_topics_sentences(ldamodel=lda_model, corpus=corpus, texts=documents)

# Format
df_dominant_topic = df_topic_sents_keywords.reset_index()
df_dominant_topic.columns = ['Document_No', 'Dominant_Topic', 'Topic_Perc_Contrib', 'Keywords', 'Text']

# Show
df_dominant_topic.head(10)

NameError: name 'corpus' is not defined

In [ ]:
df_topic_sents_keywords = format_topics_sentences(ldamodel=optimal_model, corpus=corpus, texts=documents)

# Format
df_dominant_topic = df_topic_sents_keywords.reset_index()
df_dominant_topic.columns = ['Document_No', 'Dominant_Topic', 'Topic_Perc_Contrib', 'Keywords', 'Text']

# Show
df_dominant_topic.head(10)

In [ ]:
# Group top 5 sentences under each topic
sent_topics_sorteddf_mallet = pd.DataFrame()

sent_topics_outdf_grpd = df_topic_sents_keywords.groupby('Dominant_Topic')

for i, grp in sent_topics_outdf_grpd:
    sent_topics_sorteddf_mallet = pd.concat([sent_topics_sorteddf_mallet, 
                                             grp.sort_values(['Perc_Contribution'], ascending=[0]).head(1)], 
                                            axis=0)

# Reset Index    
sent_topics_sorteddf_mallet.reset_index(drop=True, inplace=True)

# Format
sent_topics_sorteddf_mallet.columns = ['Topic_Num', "Topic_Perc_Contrib", "Keywords", "Text"]

# Show
sent_topics_sorteddf_mallet

In [ ]:
# Number of Documents for Each Topic
topic_counts = df_topic_sents_keywords['Dominant_Topic'].value_counts()

# Percentage of Documents for Each Topic
topic_contribution = round(topic_counts/topic_counts.sum(), 4)

# Topic Number and Keywords
topic_num_keywords = df_topic_sents_keywords[['Dominant_Topic', 'Topic_Keywords']]

# Concatenate Column wise
df_dominant_topics = pd.concat([topic_num_keywords, topic_counts, topic_contribution], axis=1)

# Change Column names
df_dominant_topics.columns = ['Dominant_Topic', 'Topic_Keywords', 'Num_Documents', 'Perc_Documents']

# Show
df_dominant_topics

In [ ]:
df_dominant_topics.to_csv('all_df_with_label_after_step_3.csv',index=False)