In [100]:
import numpy as np
import pandas as pd

from datetime import date, timedelta, datetime, time
import datetime
import nepali_datetime
from sklearn import metrics, preprocessing
from tqdm.notebook import tqdm
from utils import load_pkl, save_pkl

In [3]:
data_path = 'processed_data/pkl_data/user_url_keyword_lda.pkl'
df = load_pkl(data_path)
df['click'] = 1
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1

In [4]:
df_sum = df.groupby('url').agg({'user':'first', 'click':'sum'}).reset_index()
df_sum.describe()

              click
count  38054.000000
mean      18.584038
std       82.757952
min        1.000000
25%        1.000000
50%        2.000000
75%        8.000000
max     3610.000000

In [5]:
len(df_sum.url.unique())

38054

In [7]:
#df_sum[df_sum['url']=='https://corporatenepal.com/news/detail/208724/']
df_sum

,url,user,click
0,https://www.lokaantar.com/story/100009,4eb40be9468414cd5c555020c67eb062,1
1,https://www.lokaantar.com/story/100010,384ee547216ab80de0b5ac2d99415595,7
2,https://www.lokaantar.com/story/100011,837ed48107729a40772cd3b2db2994b0,2
3,https://www.lokaantar.com/story/100014,5cf6b72298c1772b2b6c3b8627e62ef4,3
4,https://www.lokaantar.com/story/100017,5715f636e00f3efa4a2b9d3992c09376,2
...,...,...,...
38049,https://www.thahakhabar.com/news/99938,ac2a5721cd6b00a99d89e035568422f4,1
38050,https://www.thahakhabar.com/news/99940,705fbdb9411b93ab785faa40ba8d3ca9,1
38051,https://www.thahakhabar.com/news/99963,19df8e6b2e751a25e43435407aa87e47,1
38052,https://www.thahakhabar.com/news/99971,b749ea1738005576f770b0cbc375d77b,2
38053,https://www.thahakhabar.com/news/99991,b661c7928e5e8cb88208c717a0ff07ca,2

In [8]:
def cut_click(clicks):
  threshold = 108.0
  if float(clicks) > threshold:
    return 108  + (clicks//108)
  else:
     return clicks

In [9]:
df_sum.click = df_sum.click.apply(cut_click)

In [10]:
df_sum.describe()

              click
count  38054.000000
mean      11.588322
std       23.766162
min        1.000000
25%        1.000000
50%        2.000000
75%        8.000000
max      141.000000

In [11]:
df_sum[['url','click']].set_index('url')

                                        click
url
https://www.lokaantar.com/story/100009      1
https://www.lokaantar.com/story/100010      7
https://www.lokaantar.com/story/100011      2
https://www.lokaantar.com/story/100014      3
https://www.lokaantar.com/story/100017      2
...                                       ...
https://www.thahakhabar.com/news/99938      1
https://www.thahakhabar.com/news/99940      1
https://www.thahakhabar.com/news/99963      1
https://www.thahakhabar.com/news/99971      2
https://www.thahakhabar.com/news/99991      2

[38054 rows x 1 columns]

In [12]:
click_dict  = df_sum[['url','click']].set_index('url').T.to_dict(orient="records")
#click_dict

In [13]:
sum_val = df_sum.click.values #returns a numpy array
sum_val = sum_val.reshape(-1, 1)
min = 0.5
max = 2.8

X_std = (sum_val - sum_val.min(axis=0)) / (sum_val.max(axis=0) - sum_val.min(axis=0))
X_scaled = X_std * (max - min) + min
df_sum.click = pd.DataFrame(X_scaled)

In [14]:
click_dict  = df_sum[['url','click']].set_index('url').T.to_dict(orient="records")
# click_dict

In [15]:
def to_nepali_date(date):
  nepali_date = nepali_datetime.datetime.strptime(date.split()[0], '%Y-%m-%d')
  return nepali_date

In [16]:
df = df.reset_index(drop=True)
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1

In [17]:
df.date =  df.date.apply(to_nepali_date)

In [18]:
diff_df = df.date- nepali_datetime.datetime.now()

In [19]:
diff_df.max(),diff_df.min()

(Timedelta('-204 days +10:49:01.877716'),
 Timedelta('-2052 days +10:49:01.877716'))

In [20]:
diff_df.describe()

count                           707197
mean     -528 days +20:43:31.594640688
std        161 days 03:01:00.557429684
min        -2052 days +10:49:01.877716
25%         -575 days +10:49:01.877716
50%         -495 days +10:49:01.877716
75%         -448 days +10:49:01.877716
max         -204 days +10:49:01.877716
Name: date, dtype: object

In [21]:
df.date.max()

nepali_datetime.datetime(2078, 4, 19, 0, 0, tzinfo=<nepali_datetime.UTC0545 object at 0x7f27aabd6df0>)

In [20]:
# nepali_datetime.datetime.now()

In [21]:
# nepali_datetime.datetime(2078,3,14)

In [24]:
len(df[df.date >nepali_datetime.datetime(2078,4,14)])

59

In [25]:
df = df[~(df.date >nepali_datetime.datetime(2078,4,19))].reset_index(drop=True)

In [26]:
df.iloc[5:9]

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click
5,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
6,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
7,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1
8,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1

In [27]:
diff_df = df.date- nepali_datetime.datetime.now()
diff_df.describe()

count                           707197
mean     -528 days +20:40:38.676068712
std        161 days 03:01:00.557429678
min        -2052 days +10:46:08.959144
25%         -575 days +10:46:08.959144
50%         -495 days +10:46:08.959144
75%         -448 days +10:46:08.959144
max         -204 days +10:46:08.959144
Name: date, dtype: object

In [28]:
diff_df

0        -946 days +10:46:08.959144
1        -946 days +10:46:08.959144
2        -946 days +10:46:08.959144
3        -946 days +10:46:08.959144
4        -946 days +10:46:08.959144
                    ...
707192   -261 days +10:46:08.959144
707193   -265 days +10:46:08.959144
707194   -259 days +10:46:08.959144
707195   -260 days +10:46:08.959144
707196   -259 days +10:46:08.959144
Name: date, Length: 707197, dtype: timedelta64[ns]

In [29]:
108*2

216

In [32]:
diff_df.max()

Timedelta('-204 days +10:46:08.959144')

In [33]:
diff_df = diff_df.dt.days + 204

In [34]:
diff_df.describe()

count    707197.000000
mean       -323.587156
std         161.125701
min       -1848.000000
25%        -371.000000
50%        -291.000000
75%        -244.000000
max           0.000000
Name: date, dtype: float64

In [35]:
x = diff_df.values #returns a numpy array
x = x.reshape(-1, 1)

min = -2
max = 2

X_std = (x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0))
print(X_std)
X_scaled = X_std * (max - min) + min
df['time_rating'] = pd.DataFrame(X_scaled)

[[0.59848485]
 [0.59848485]
 [0.59848485]
 ...
 [0.9702381 ]
 [0.96969697]
 [0.9702381 ]]

In [36]:
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click,time_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952

In [37]:
df.time_rating.describe()

count    707197.000000
mean          1.299595
std           0.348757
min          -2.000000
25%           1.196970
50%           1.370130
75%           1.471861
max           2.000000
Name: time_rating, dtype: float64

In [38]:
type(click_dict[0])

dict

In [39]:
df['url'].map(click_dict[0])

0         0.664286
1         0.664286
2         0.664286
3         0.664286
4         0.664286
            ...
707192    0.500000
707193    0.500000
707194    0.500000
707195    0.500000
707196    0.500000
Name: url, Length: 707197, dtype: float64

In [40]:
df['url_click_rating']= df['url'].map(click_dict[0])

In [41]:
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click,time_rating,url_click_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623,0.500000
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965,0.500000
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952,0.500000
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788,0.500000
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952,0.500000

In [45]:
df.columns

Index(['user', 'url', 'additional_images', 'content', 'date', 'head_image',
       'heading', 'label', 'source', 'author', 'author_img', 'all_content',
       'all_heading_content_list', 'all_heading_content', 'keywords',
       'Dominant_Topic', 'Topic_Keywords', 'click', 'time_rating',
       'url_click_rating'],
      dtype='object')

In [46]:
user_url_df = df[['user','url','label','Dominant_Topic']]
user_url_df

,user,url,label,Dominant_Topic
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,अर्थ,1.0
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,अर्थ,1.0
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,अर्थ,1.0
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,अर्थ,1.0
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,अर्थ,1.0
...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,राजनीति,11.0
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,राजनीति,7.0
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,राजनीति,2.0
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,विश्व,9.0
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,राजनीति,11.0

In [47]:
user_url_df.Dominant_Topic.describe()

count    707197.000000
mean          6.166105
std           4.066145
min           0.000000
25%           2.000000
50%           6.000000
75%          10.000000
max          13.000000
Name: Dominant_Topic, dtype: float64

In [48]:
# user_url = (df.groupby(['user', 'url'],as_index=False).size().reset_index(name='count'))
user_url = (df.groupby(['user', 'url'],as_index=False).size().reset_index())
user_url

,index,user,url,size
0,0,00003762db942cabd188b2984897e5c5,https://www.ratopati.com/story/175346,4
1,1,00005513d5d145d61be64de14ab4b56e,https://www.ratopati.com/story/149465,1
2,2,00005513d5d145d61be64de14ab4b56e,https://www.ratopati.com/story/157407,1
3,3,0002eabd63d3cde55b2c77f2dcaa6ce0,https://www.ratopati.com/story/125765,1
4,4,0002eabd63d3cde55b2c77f2dcaa6ce0,https://www.ratopati.com/story/125901,1
...,...,...,...,...
490290,490290,fffe89d5e23fe936c45214fd1c52a7ce,https://www.ratopati.com/story/153831,1
490291,490291,fffec3687bd49131897f5f0d9e004e31,https://www.lokaantar.com/story/100897,1
490292,490292,ffff938c69315daed47dc99398d9d15f,https://www.ratopati.com/story/106563,1
490293,490293,ffffbed8db2a2fdd7e42372934f42cf2,https://www.ratopati.com/story/163913,1
490294,490294,ffffff2559629ae1ae4d161a24e2cdbe,https://www.ratopati.com/story/141695,1

In [49]:
len(df.user.unique())

185317

In [40]:
user_url['size'].describe()

count    207745.000000
mean          1.509928
std           1.390006
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         206.000000
Name: size, dtype: float64

In [50]:
user_url['size'].describe()

count    490295.000000
mean          1.442391
std           1.433980
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         507.000000
Name: size, dtype: float64

In [53]:
108/1.5

72.0

In [54]:
def cut_count(count):
  threshold = 72.0
  if float(count) > threshold:
    return 72  + (count//72)
  else:
     return count
  # return count//14


user_url['size'] = user_url['size'].apply(cut_count)

In [55]:
X = user_url['size'].values #returns a numpy array
X = X.reshape(-1, 1)
min = 0.5
max = 1.8
# min_max_scaler = preprocessing.StandardScaler()
# x_scaled = min_max_scaler.fit_transform(x)

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min
user_url['size'] = pd.DataFrame(X_scaled)

In [56]:
user_url['size'].describe()

count    490295.00000
mean          0.50735
std           0.01987
min           0.50000
25%           0.50000
50%           0.50000
75%           0.50000
max           1.80000
Name: size, dtype: float64

In [57]:
user_url

,index,user,url,size
0,0,00003762db942cabd188b2984897e5c5,https://www.ratopati.com/story/175346,0.55
1,1,00005513d5d145d61be64de14ab4b56e,https://www.ratopati.com/story/149465,0.50
2,2,00005513d5d145d61be64de14ab4b56e,https://www.ratopati.com/story/157407,0.50
3,3,0002eabd63d3cde55b2c77f2dcaa6ce0,https://www.ratopati.com/story/125765,0.50
4,4,0002eabd63d3cde55b2c77f2dcaa6ce0,https://www.ratopati.com/story/125901,0.50
...,...,...,...,...
490290,490290,fffe89d5e23fe936c45214fd1c52a7ce,https://www.ratopati.com/story/153831,0.50
490291,490291,fffec3687bd49131897f5f0d9e004e31,https://www.lokaantar.com/story/100897,0.50
490292,490292,ffff938c69315daed47dc99398d9d15f,https://www.ratopati.com/story/106563,0.50
490293,490293,ffffbed8db2a2fdd7e42372934f42cf2,https://www.ratopati.com/story/163913,0.50
490294,490294,ffffff2559629ae1ae4d161a24e2cdbe,https://www.ratopati.com/story/141695,0.50

In [58]:
user_url_dict = user_url.set_index(['user','url']).to_dict()['size']
# user_url_dict

In [59]:
def rate_giver(user,url):
    return user_url_dict.get((user,url))

In [60]:
df["user_url_rating"] = (df.apply(lambda x: rate_giver(x.user,x.url), axis=1))

In [61]:
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click,time_rating,url_click_rating,user_url_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623,0.500000,0.500000
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965,0.500000,0.500000
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952,0.500000,0.500000
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788,0.500000,0.500000
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952,0.500000,0.500000

In [62]:
# user_Dominant_Topic_df = (df.groupby(['user', 'Dominant_Topic'],as_index=False).size().reset_index(name='count'))
user_Dominant_Topic_df = (df.groupby(['user', 'Dominant_Topic'],as_index=False).size().reset_index())
user_Dominant_Topic_df

         index                              user  Dominant_Topic  size
0            0  00003762db942cabd188b2984897e5c5             2.0     4
1            1  00005513d5d145d61be64de14ab4b56e            10.0     1
2            2  00005513d5d145d61be64de14ab4b56e            13.0     1
3            3  0002eabd63d3cde55b2c77f2dcaa6ce0             2.0     1
4            4  0002eabd63d3cde55b2c77f2dcaa6ce0             4.0     2
...        ...                               ...             ...   ...
331122  331122  fffe89d5e23fe936c45214fd1c52a7ce             5.0     1
331123  331123  fffec3687bd49131897f5f0d9e004e31             2.0     1
331124  331124  ffff938c69315daed47dc99398d9d15f            11.0     1
331125  331125  ffffbed8db2a2fdd7e42372934f42cf2             7.0     1
331126  331126  ffffff2559629ae1ae4d161a24e2cdbe            12.0     1

[331127 rows x 4 columns]

In [63]:
user_Dominant_Topic_df.describe()

              index  Dominant_Topic           size
count  331127.00000   331127.000000  331127.000000
mean   165563.00000        6.314900       2.135727
std     95588.27563        4.053404       4.375717
min         0.00000        0.000000       1.000000
25%     82781.50000        2.000000       1.000000
50%    165563.00000        7.000000       1.000000
75%    248344.50000       10.000000       2.000000
max    331126.00000       13.000000     507.000000

In [64]:
def cut_size(size):
  threshold = 36.0
  if float(size) > threshold:
    return 36  + (size//36)
  else:
    return size
  # return size//14


user_Dominant_Topic_df['size'] = user_Dominant_Topic_df['size'].apply(cut_size)

In [65]:
from sklearn import preprocessing

X = user_Dominant_Topic_df['size'].values #returns a numpy array
X = X.reshape(-1, 1)
min = 0
max = 1.8
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min


user_Dominant_Topic_df['size'] = pd.DataFrame(X_scaled)

In [66]:
user_Dominant_Topic_df

         index                              user  Dominant_Topic      size
0            0  00003762db942cabd188b2984897e5c5             2.0  0.110204
1            1  00005513d5d145d61be64de14ab4b56e            10.0  0.000000
2            2  00005513d5d145d61be64de14ab4b56e            13.0  0.000000
3            3  0002eabd63d3cde55b2c77f2dcaa6ce0             2.0  0.000000
4            4  0002eabd63d3cde55b2c77f2dcaa6ce0             4.0  0.036735
...        ...                               ...             ...       ...
331122  331122  fffe89d5e23fe936c45214fd1c52a7ce             5.0  0.000000
331123  331123  fffec3687bd49131897f5f0d9e004e31             2.0  0.000000
331124  331124  ffff938c69315daed47dc99398d9d15f            11.0  0.000000
331125  331125  ffffbed8db2a2fdd7e42372934f42cf2             7.0  0.000000
331126  331126  ffffff2559629ae1ae4d161a24e2cdbe            12.0  0.000000

[331127 rows x 4 columns]

In [89]:
user_Dominant_Topic_df.describe()

              index  Dominant_Topic           size
count  331127.00000   331127.000000  331127.000000
mean   165563.00000        6.314900       0.039560
std     95588.27563        4.053404       0.120474
min         0.00000        0.000000       0.000000
25%     82781.50000        2.000000       0.000000
50%    165563.00000        7.000000       0.000000
75%    248344.50000       10.000000       0.036735
max    331126.00000       13.000000       1.800000

In [90]:
user_Dominant_Topic_dict = user_Dominant_Topic_df.set_index(['user','Dominant_Topic']).to_dict()['size']

In [91]:
def url_rate_giver(user,Dominant_Topic):
    return user_Dominant_Topic_dict.get((user,Dominant_Topic))

In [92]:
df["user_Dominant_Topic_rating"] = (df.apply(lambda x: url_rate_giver(x.user,x.Dominant_Topic), axis=1))
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,keywords,Dominant_Topic,Topic_Keywords,click,time_rating,url_click_rating,user_url_rating,user_Dominant_Topic_rating,user_label_rating,user_main_topic_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623,0.500000,0.500000,0.000000,0.000000,0.000000
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965,0.500000,0.500000,0.000000,0.000000,0.000000
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952,0.500000,0.500000,0.000000,0.000000,0.000000
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788,0.500000,0.500000,0.000000,0.000000,0.000000
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952,0.500000,0.500000,0.000000,0.000000,0.000000

In [70]:
# user_label_df = (df.groupby(['user', 'label'],as_index=False).size().reset_index(name='count'))
user_label_df = (df.groupby(['user', 'label'],as_index=False).size().reset_index())
user_label_df

         index                              user               label  size
0            0  00003762db942cabd188b2984897e5c5              समाचार     4
1            1  00005513d5d145d61be64de14ab4b56e        मुख्य समाचार     1
2            2  00005513d5d145d61be64de14ab4b56e              समाचार     1
3            3  0002eabd63d3cde55b2c77f2dcaa6ce0                अर्थ     1
4            4  0002eabd63d3cde55b2c77f2dcaa6ce0        मुख्य समाचार     1
...        ...                               ...                 ...   ...
293823  293823  fffe89d5e23fe936c45214fd1c52a7ce  स्वास्थ्य/जीवनशैली     1
293824  293824  fffec3687bd49131897f5f0d9e004e31        मुख्य समाचार     1
293825  293825  ffff938c69315daed47dc99398d9d15f              खेलकुद     1
293826  293826  ffffbed8db2a2fdd7e42372934f42cf2            मनोरञ्जन     1
293827  293827  ffffff2559629ae1ae4d161a24e2cdbe        मुख्य समाचार     1

[293828 rows x 4 columns]

In [71]:
user_label_df.describe()

               index          size
count  293828.000000  293828.00000
mean   146913.500000       2.40684
std     84820.981785       7.14472
min         0.000000       1.00000
25%     73456.750000       1.00000
50%    146913.500000       1.00000
75%    220370.250000       2.00000
max    293827.000000     827.00000

In [72]:
user_label_df['size'] = user_label_df['size'].apply(cut_size)

In [73]:
X = user_label_df['size'].values #returns a numpy array
X = X.reshape(-1, 1)
min = 0
max = 1.8
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min


user_label_df['size'] = pd.DataFrame(X_scaled)

In [74]:
user_label_df

         index                              user               label      size
0            0  00003762db942cabd188b2984897e5c5              समाचार  0.094737
1            1  00005513d5d145d61be64de14ab4b56e        मुख्य समाचार  0.000000
2            2  00005513d5d145d61be64de14ab4b56e              समाचार  0.000000
3            3  0002eabd63d3cde55b2c77f2dcaa6ce0                अर्थ  0.000000
4            4  0002eabd63d3cde55b2c77f2dcaa6ce0        मुख्य समाचार  0.000000
...        ...                               ...                 ...       ...
293823  293823  fffe89d5e23fe936c45214fd1c52a7ce  स्वास्थ्य/जीवनशैली  0.000000
293824  293824  fffec3687bd49131897f5f0d9e004e31        मुख्य समाचार  0.000000
293825  293825  ffff938c69315daed47dc99398d9d15f              खेलकुद  0.000000
293826  293826  ffffbed8db2a2fdd7e42372934f42cf2            मनोरञ्जन  0.000000
293827  293827  ffffff2559629ae1ae4d161a24e2cdbe        मुख्य समाचार  0.000000

[293828 rows x 4 columns]

In [75]:
user_label_dict = user_label_df.set_index(['user','label']).to_dict()['size']
# user_label_dict

In [76]:
def url_rate_giver(user,label):
    return user_label_dict.get((user,label))

In [77]:
df["user_label_rating"] = (df.apply(lambda x: url_rate_giver(x.user,x.label), axis=1))
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,Topic_Keywords,click,time_rating,url_click_rating,user_url_rating,user_Dominant_Topic_rating,user_label_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623,0.500000,0.500000,0.000000,0.000000
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965,0.500000,0.500000,0.000000,0.000000
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952,0.500000,0.500000,0.000000,0.000000
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788,0.500000,0.500000,0.000000,0.000000
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952,0.500000,0.500000,0.000000,0.000000

In [78]:
df.columns

Index(['user', 'url', 'additional_images', 'content', 'date', 'head_image',
       'heading', 'label', 'source', 'author', 'author_img', 'all_content',
       'all_heading_content_list', 'all_heading_content', 'keywords',
       'Dominant_Topic', 'Topic_Keywords', 'click', 'time_rating',
       'url_click_rating', 'user_url_rating', 'user_Dominant_Topic_rating',
       'user_label_rating'],
      dtype='object')

In [80]:
user_main_topic_df = (df.groupby(['user', 'label'],as_index=False).size().reset_index())
user_main_topic_df

         index                              user               label  size
0            0  00003762db942cabd188b2984897e5c5              समाचार     4
1            1  00005513d5d145d61be64de14ab4b56e        मुख्य समाचार     1
2            2  00005513d5d145d61be64de14ab4b56e              समाचार     1
3            3  0002eabd63d3cde55b2c77f2dcaa6ce0                अर्थ     1
4            4  0002eabd63d3cde55b2c77f2dcaa6ce0        मुख्य समाचार     1
...        ...                               ...                 ...   ...
293823  293823  fffe89d5e23fe936c45214fd1c52a7ce  स्वास्थ्य/जीवनशैली     1
293824  293824  fffec3687bd49131897f5f0d9e004e31        मुख्य समाचार     1
293825  293825  ffff938c69315daed47dc99398d9d15f              खेलकुद     1
293826  293826  ffffbed8db2a2fdd7e42372934f42cf2            मनोरञ्जन     1
293827  293827  ffffff2559629ae1ae4d161a24e2cdbe        मुख्य समाचार     1

[293828 rows x 4 columns]

In [81]:
user_main_topic_df.describe()

               index          size
count  293828.000000  293828.00000
mean   146913.500000       2.40684
std     84820.981785       7.14472
min         0.000000       1.00000
25%     73456.750000       1.00000
50%    146913.500000       1.00000
75%    220370.250000       2.00000
max    293827.000000     827.00000

In [82]:
user_main_topic_df['size'] = user_main_topic_df['size'].apply(cut_size)

In [83]:
X = user_main_topic_df['size'].values #returns a numpy array
X = X.reshape(-1, 1)
min = 0
max = 1.8
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min


user_main_topic_df['size'] = pd.DataFrame(X_scaled)

In [85]:
user_main_topic_dict = user_main_topic_df.set_index(['user','label']).to_dict()['size']

In [86]:
def url_topic_rate_giver(user,main_topic):
    return user_main_topic_dict.get((user,main_topic))

In [87]:
df["user_main_topic_rating"] = (df.apply(lambda x: url_topic_rate_giver(x.user,x.label), axis=1))
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,keywords,Dominant_Topic,Topic_Keywords,click,time_rating,url_click_rating,user_url_rating,user_Dominant_Topic_rating,user_label_rating,user_main_topic_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623,0.500000,0.500000,0.000000,0.000000,0.000000
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965,0.500000,0.500000,0.000000,0.000000,0.000000
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952,0.500000,0.500000,0.000000,0.000000,0.000000
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788,0.500000,0.500000,0.000000,0.000000,0.000000
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952,0.500000,0.500000,0.000000,0.000000,0.000000

In [94]:
df.describe()

,Dominant_Topic,click,time_rating,url_click_rating,user_url_rating,user_Dominant_Topic_rating,user_label_rating,user_main_topic_rating
count,707197.000000,707197.0,707197.000000,707197.000000,707197.000000,707197.000000,707197.000000,707197.000000
mean,6.166105,1.0,1.299595,1.812948,0.524986,0.261453,0.321919,0.321919
std,4.066145,0.0,0.348757,0.707710,0.067327,0.399199,0.433703,0.433703
min,0.000000,1.0,-2.000000,0.500000,0.500000,0.000000,0.000000,0.000000
25%,2.000000,1.0,1.196970,1.107857,0.500000,0.000000,0.000000,0.000000
50%,6.000000,1.0,1.370130,2.274286,0.500000,0.073469,0.094737,0.094737
75%,10.000000,1.0,1.471861,2.323571,0.533333,0.330612,0.473684,0.473684
max,13.000000,1.0,2.000000,2.800000,1.800000,1.800000,1.800000,1.800000

In [95]:
df['final_rating'] = (df.apply(lambda x: (x['time_rating'] + x['url_click_rating'] + x['user_url_rating'] + x['user_Dominant_Topic_rating'] + x['user_label_rating'] + x['user_main_topic_rating'] ), axis=1 ))
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,Dominant_Topic,Topic_Keywords,click,time_rating,url_click_rating,user_url_rating,user_Dominant_Topic_rating,user_label_rating,user_main_topic_rating,final_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789,2.723818
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789,2.723818
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789,2.723818
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789,2.723818
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,1.0,बैंक करोड हजार रुपैयाँ प्रतिशत कम्पनी भिटामिन ...,1,0.393939,0.664286,0.666667,0.367347,0.315789,0.315789,2.723818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.876623,0.500000,0.500000,0.000000,0.000000,0.000000,2.876623
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,7.0,फिल्म थिइन् महिला विवाह आफ्नो छोरा परिवार छोरी...,1,1.867965,0.500000,0.500000,0.000000,0.000000,0.000000,2.867965
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,2.0,पार्टी नेता प्रधानमन्त्री बैठक नेकपा अध्यक्ष स...,1,1.880952,0.500000,0.500000,0.000000,0.000000,0.000000,2.880952
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,9.0,कोरोना अस्पताल संक्रमण संक्रमित परीक्षण भाइरस ...,1,1.878788,0.500000,0.500000,0.000000,0.000000,0.000000,2.878788
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,11.0,स्थान मौसम वर्षा सम्भावना महाशाखा पहाडी सामान्...,1,1.880952,0.500000,0.500000,0.000000,0.000000,0.000000,2.880952

In [96]:
df.describe()

,Dominant_Topic,click,time_rating,url_click_rating,user_url_rating,user_Dominant_Topic_rating,user_label_rating,user_main_topic_rating,final_rating
count,707197.000000,707197.0,707197.000000,707197.000000,707197.000000,707197.000000,707197.000000,707197.000000,707197.000000
mean,6.166105,1.0,1.299595,1.812948,0.524986,0.261453,0.321919,0.321919,4.542821
std,4.066145,0.0,0.348757,0.707710,0.067327,0.399199,0.433703,0.433703,1.693823
min,0.000000,1.0,-2.000000,0.500000,0.500000,0.000000,0.000000,0.000000,-1.000000
25%,2.000000,1.0,1.196970,1.107857,0.500000,0.000000,0.000000,0.000000,3.399890
50%,6.000000,1.0,1.370130,2.274286,0.500000,0.073469,0.094737,0.094737,4.409198
75%,10.000000,1.0,1.471861,2.323571,0.533333,0.330612,0.473684,0.473684,5.398528
max,13.000000,1.0,2.000000,2.800000,1.800000,1.800000,1.800000,1.800000,10.130862

In [97]:
df.columns

Index(['user', 'url', 'additional_images', 'content', 'date', 'head_image',
       'heading', 'label', 'source', 'author', 'author_img', 'all_content',
       'all_heading_content_list', 'all_heading_content', 'keywords',
       'Dominant_Topic', 'Topic_Keywords', 'click', 'time_rating',
       'url_click_rating', 'user_url_rating', 'user_Dominant_Topic_rating',
       'user_label_rating', 'user_main_topic_rating', 'final_rating'],
      dtype='object')

In [98]:
# columns = ['user', 'url','date', 'keywords','label','Dominant_Topic','content_list','all_content' ,'main_topic','final_rating']
columns = ['user', 'url', 'additional_images', 'content', 'date', 'head_image',
       'heading', 'label', 'source', 'author', 'author_img', 'all_content',
       'all_heading_content_list', 'all_heading_content', 'keywords',
       'Dominant_Topic', 'final_rating']
df = df[columns]
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,2.876623
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,2.867965
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,2.880952
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,2.878788
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,2.880952

In [99]:
df.to_csv('processed_data/train_data/train.csv', index = False)

In [104]:
df

,user,url,additional_images,content,date,head_image,heading,label,source,author,author_img,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,https://ratopatis.prixacdn.net/media/Untitled-...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"[यस्तो, विनिमयदरः, अमेरि, कतारी, रियालसम्म, ने...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",1.0,2.723818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"[खनाल-नेपाल, समूह, नेता, सरकार, सहभागी, नेकपा,...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",11.0,2.876623
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"[बाबुरामप्रति, लिङ्देन, कटाक्ष, आखिर, तपाईं, भ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",7.0,2.867965
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"[प्रदेश, कांग्रेस, माओवा, सरकार, प्रदेश, नेपाल...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[कांग्रेस, माओवा, मन्त्रालय, रामसरोज, ओमप्रकाश...",2.0,2.880952
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,https://thahacdn.prixacdn.net/media/Logo_Thaha...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"[कोरोना, संक्रमण, उच्च, विश्व, कोरोना, संक्रमण...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...",9.0,2.878788
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,https://thahacdn.prixacdn.net/media/teksimha-d...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","[सुदूरपश्चिम, रावल, शक्ति,, पक्ष, पटक–पटक, असफ...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",11.0,2.880952

In [105]:
save_pkl(df,'processed_data/train_data/train.pkl')

PicklingError: __reduce__ must return a string or tuple